### ISSUE TITLE
Add example API usage to the README

### ISSUE THREAD

**Issue by leibovic** [mozilla/readability#10]

**Comment by geotheory** [comment]
Difficult to tell if this is considered to have been actioned. But IMO the README does not specify the process very clearly. An example script would be really helpful.

**Comment by gijsk** [comment]
> Difficult to tell if this is considered to have been actioned. But IMO the README does not specify the process very clearly. An example script would be really helpful.

There's https://github.com/mozilla/readability#usage  now. If you could file a new issue with what you think is missing in that section, that'd be really helpful.

**Comment by geotheory** [comment]
Thanks. Basically a minimal complete script that actually works would be the sort of thing that is really good for e.g. non-advanced node users to start with.  As it is there is a fair bit of hacking with js-sha1 for relative newcomers to just achieve that first step.  Happy register a new issue, but really I think it's essentially the same as this one.

**Comment by geotheory** [comment]
Thanks. Basically a minimal complete script that actually works would be the sort of thing that is really good for e.g. non-advanced node users to start with.  As it is there is a fair bit of hacking with `readability` and e.g. `jsdom` for relative newcomers to just achieve that first step.  Happy register a new issue, but really I think it's essentially the same as this one.
