### ISSUE TITLE
Readability fails on a Gawker/Kinja/Deadspin article.

### ISSUE THREAD

**Issue by arusahni** [mozilla/readability#103]
Readability grabs a comment from [this Deadspin article](http://regressing.deadspin.com/a-highly-scientific-analysis-of-grrms-progress-on-the-1693622058) instead of the article itself.

Here's what the misparsed page looks like:

![reader-error](https://cloud.githubusercontent.com/assets/139487/7010243/ab081fde-dc6d-11e4-8c70-2a51d44ca051.png)

[Cross-filed in Bugzilla: [1148840](https://bugzilla.mozilla.org/show_bug.cgi?id=1148840)]

**Comment by arusahni** [comment]
This might be a dupe of/related to #76.

**Comment by n1k0** [comment]
Fixed with latest master + latest fx-team

![screen shot 2015-04-07 at 18 02 41](https://cloud.githubusercontent.com/assets/41547/7027557/5b7169c4-dd50-11e4-98d5-2937416193e6.png)
