### ISSUE TITLE
Pages with reasonable amount of text from *.blogspot.com can't be displayed in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#108]
**Reproducible on**: 
Beta 38.0b1-build1 (20150330154247)

**Sample page showing this issue**:
http://googleblog.blogspot.ro/2015/04/through-google-lens-search-trends-march.html

**Comment by n1k0** [comment]
This is a readerability detection issue. Article contents render just fines using latest master + latest fx-team.

**Comment by avaida** [comment]
Here's another sample showing the same thing: http://hatsukiyurafansite.blogspot.com/2015/03/eliminacion-de-links-de-descargas.html - although the issue here might be the way paragraphs are displayed, with <br /> instead of <p>.

**Comment by n1k0** [comment]
Yeah, we definitely want to improve the readerability algorithm, the question is how.

**Comment by gijsk** [comment]
This was fixed in #310.
