### ISSUE TITLE
Cannot scrape/display certain domains due to cross-origin or framing policies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#11]
I'm running the compare-view script locally at http://localhost:3000/compare-view/ and it seems to be failing to display/scrape certain pages due to `X-Frame-Options` restrictions. Not entirely sure if that is because we're trying to iframe amazon.com and github.com, or if there is something deeper, but it'd be nice if we could still show the scraped contents on the right and maybe an empty frame on the left.

| TIME | DESC | LOCATION |
|----:|----|----|
| 15:16:39.640 | Load denied by X-Frame-Options: http://www.amazon.com/ does not permit cross-origin framing. | \<unknown\>
| 15:16:39.778 | TypeError: Argument 1 of XMLSerializer.serializeToString is not an object. | compare.js:7:19
| 15:17:53.921 | Load denied by X-Frame-Options: https://github.com/mozilla/readability does not permit framing. | \<unknown\>
| 15:17:54.039 | TypeError: Argument 1 of XMLSerializer.serializeToString is not an object. | compare.js:7:19
| 15:24:28.204 | Load denied by X-Frame-Options: https://www.mozilla.org/en-US/ does not permit framing. | \<unknown\>
| 15:24:28.294 | TypeError: Argument 1 of XMLSerializer.serializeToString is not an object. | compare.js:7:19

**Comment by leibovic** [comment]
Yes, unfortunately you also need to host your test page locally. @n1k0 has plans to try to incorporate his [readable-proxy](https://github.com/n1k0/readable-proxy/) proxy server into this to avoid this issue, but in the meantime, you just need to save a test page locally (or run your own local proxy server).

**Comment by n1k0** [comment]
I've landed https://github.com/n1k0/readable-proxy/pull/3. If you install it locally, you can run it that way:

    $ READABILITY_LIB_PATH=/path/to/Readibility.js npm start

Where `READABILITY_LIB_PATH` is the path to the version of the lib you're hacking on.

**Comment by leibovic** [comment]
I think we should consider reverting my commit to add this compare-view tool, and then readable-proxy could just be the supported way of doing this before/after comparison (we can talk about that in the README for this repo). Converging on a single tool seems like the best way to go :)

**Comment by leibovic** [comment]
I decided to go ahead and remove the compare-view page, since it was just a worse version of readable-proxy. You should use readable-proxy instead, it's really easy to set up and run!
