### ISSUE TITLE
The pages from huffingtonpost.com are missing their byline information in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#111]
**Reproducible on**: 
Beta 38.0b1-build1 (20150330154247)

**Sample page showing this issue**:
http://www.huffingtonpost.com/2015/04/05/obama-doctrine-iran_n_7008142.html

**Comment by n1k0** [comment]
Author info has this markup:

```html
<div class="byline vcard group ">
  <div class="info">
    <span class="thirdparty-logo">The Huffington Post</span>
    <span class="name fn">
      &nbsp;|&nbsp;By <a sl-processed="1" rel="author" href="/igor-bobic/">Igor Bobic</a>
                            
    </span>
  </div>
</div>
```

Amazing we don't detect it :)

**Comment by n1k0** [comment]
This is actually fixed in latest master + latest fx-team:

![screen shot 2015-04-07 at 18 19 16](https://cloud.githubusercontent.com/assets/41547/7027915/ab5a61c8-dd52-11e4-9d86-439eb28305c2.png)
