### ISSUE TITLE
Specific pages from ehow.com are displaying the navigation menu in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#112]
**Reproducible on**: 
Beta 38.0b1-build1 (20150330154247)

**Screenshot**:
http://i.imgur.com/yaebve2.png

**Sample page showing this issue**:
http://www.ehow.com/how_7853040_diy-own-living-room-furniture.html

**Comment by gijsk** [comment]
This fails outright right now.

**Comment by n1k0** [comment]
Fixed by #193.
