### ISSUE TITLE
Specific pages from bbc.com cannot be displayed in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#115]
**Reproducible on**: 
Beta 38.0b2-build1 (20150406174117)

**Sample page showing this issue**:
http://www.bbc.com/news/world-middle-east-32198576

**Comment by n1k0** [comment]
Fixed with latest fx-team and latest master:

![screen shot 2015-04-07 at 15 44 44](https://cloud.githubusercontent.com/assets/41547/7024432/2118b740-dd3d-11e4-8c09-c4de66cf5ba5.png)
