### ISSUE TITLE
Specific pages from usatoday.com are displaying image captions but not the image themselves in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#125]
**Affected branches**:
Beta 38.0b2-build1 (20150406174117), Aurora 39.0a2 (2015-04-08), Nightly 40.0a1 (2015-04-07)

**Sample page showing this issue**:
http://www.usatoday.com/story/news/2015/04/07/dea-bulk-telephone-surveillance-operation/70808616/

**Note**:
The second paragraph - "Staring in 1992, the Justice Department amassed logs of [...]" is the caption of an image that's *not* displayed in Reader View.

**Comment by n1k0** [comment]
Caption markup is as following:

```html
… Article content starts, then…
<p class="image-credit-wrap">
  <span class="js-caption-wrapper">
    <span class="cutline js-caption">Starting in 1992, the Justice Department amassed logs of virtually all telephone calls from the USA to as many as 116 countries, a model for anti-terror surveillance after Sept. 11, 2001.</span>
    <meta itemprop="copyrightHolder" content="">
    <span class="credit">(Photo: Photo: Mike Christy, AP)</span>
  </span>
</p>
… Article content goes on…
```

I can't identify how we could detect this from being unwanted, in a reliable fashion. Maybe that's where site-specific rules could shine, though I keep opened to suggestions and ideas.

**Comment by gijsk** [comment]
Shouldn't we be trying to keep the *image* inside this paragraph? Why aren't we doing that?

**Comment by gijsk** [comment]
Interestingly, #75 is the opposite problem: images get put in the article which shouldn't be...

**Comment by n1k0** [comment]
> Shouldn't we be trying to keep the image inside this paragraph? Why aren't we doing that?

The image isn't in the paragraph. I've updated the markup snippet to include more outer context.

**Comment by gijsk** [comment]
I wonder if marking 'photo' positive would help here.

**Comment by n1k0** [comment]
Strangely, it seems this is now fixed using latest master + latest fx-team:

![screen shot 2015-04-10 at 12 20 28](https://cloud.githubusercontent.com/assets/41547/7085962/234a433a-df7c-11e4-9204-277457cd31a2.png)

I wish we could identify image captions better, though let's not get too picky. I'm hesitating marking this as fixed as I don't clearly grasp how it's been suddenly fixed.

**Comment by gijsk** [comment]
I mean, it's hard to debug now that it's fixed, so let's mark it fixed and if there's a new testcase on the same site we can reopen.
