### ISSUE TITLE
Implement relaxed, fallback parsing strategy

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#136]
As discussed lately, we need to investigate a way to ensure `parse()` always returns "something". This could be processing page contents a little like how [node-unfluff](https://github.com/ageitgey/node-unfluff) does, as a last-resort fallback strategy.

**Comment by n1k0** [comment]
While reading the code flow today, I've noticed that relaxing the number of chars considered not enough for generated page contents to be acceptable[0] avoids having `null` returned as a result.

[0]: https://github.com/mozilla/readability/blob/0ff82de0f453c3b8ae16cf9e5b2bd11d6ad2eb7d/Readability.js#L863

**Comment by gijsk** [comment]
#423 eventually ended up implementing this. Took a while, but much better now! \o/
