### ISSUE TITLE
Text wrapping issue on some msn.com pages

### ISSUE THREAD

**Issue by gijsk** [mozilla/readability#137]
http://www.msn.com/en-us/news/other/ex-marine-ordered-to-trial-in-killing-of-other-marines-wife/ar-AAao84a

Shows a long run of text, instead of per-paragraph things. No idea why.

**Comment by n1k0** [comment]
Hmm this is completely failing in latest fx-team+latest master, with no obvious message even with debug set to true. Weirdly, this page parses just fine in our nodejs environment… :(

**Comment by gijsk** [comment]
This looks fixed. :-)
