### ISSUE TITLE
Some wikipedia pages don't display in reader mode at all (icon does appear)

### ISSUE THREAD

**Issue by gijsk** [mozilla/readability#138]
Cross-ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1149418

https://en.wikipedia.org/wiki/New_Zealand
http://en.wikipedia.org/wiki/Sonic_X

Both fail completely.

**Comment by n1k0** [comment]
FWIW, latest master parses these pages just fine, though in browser we're hitting the `MAX_ELEMS_TO_PARSE` limit of 3000 elements:

> Reader: Aborting parse for http://en.wikipedia.org/wiki/Sonic_X; 3630 elements found

This is a gecko side issue to me.

**Comment by gijsk** [comment]
Yes, we can track this in https://bugzilla.mozilla.org/show_bug.cgi?id=1152219 .
