### ISSUE TITLE
No reader view results for https://www.mozilla.org/en-US/firefox/desktop/customize/

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#139]
### Steps to reproduce:
1. Go to https://www.mozilla.org/en-US/firefox/desktop/customize/ (one of the default bookmarks in a new profile).
2. Enter reader view.

### Actual results

> #### Failed to load article from page

### Expected results
Reader view not available, or a scraped page.

---

![failed_to_load_article_from_page_and_new_issue_ _mozilla_readability](https://cloud.githubusercontent.com/assets/557895/7144113/14596a80-e298-11e4-89c7-29b32894b6f5.png)

**Comment by n1k0** [comment]
Error in te console is `Reader: Worker did not return an article`.

I'll investigate this one today.

**Comment by n1k0** [comment]
Started investigation in #142, which also covers other issues. Good news is this WiP patch now allows retrieving something for this very page. Bad news is that it breaks some other ones. Will continue this investigation tomorrow.
