### ISSUE TITLE
No readability results for https://www.mozilla.org/en-US/firefox/39.0a2/firstrun/

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#143]
Was testing something in Aurora and noticed that https://www.mozilla.org/en-US/firefox/39.0a2/firstrun/ (default page for new profile) shows me a reader view icon in the address bar, but clicking it shows:

> #### _"Failed to load article from page"_

---

![failed_to_load_article_from_page_and_new_issue_ _mozilla_readability_and_untitled_3](https://cloud.githubusercontent.com/assets/557895/7171003/14f08c6c-e388-11e4-85c6-a0c534aabfca.png)

**Comment by n1k0** [comment]
My WIP patch in #142 seems to fix this:

![screen shot 2015-04-16 at 08 53 27](https://cloud.githubusercontent.com/assets/41547/7175551/27fdba94-e416-11e4-8d48-282a933a5d4e.png)

**Comment by n1k0** [comment]
This has been fixed by #185.
