### ISSUE TITLE
Cannot add page to reading list

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#144]
Related to my previous bug, #143.

### Steps to reproduce:
1. Go to https://www.mozilla.org/en-US/firefox/39.0a2/firstrun/
2. Enter reader view mode (it should display _"Failed to load article from page"_, unless that bug was fixed first).
3. Click the giant **(+)** button in the reader mode to add the page to your reading list.

### Actual results:
Nothing happens. Page isn't added to your reading list.

### Expected results:
Page can be added to your reading list, despite not being reader-able.

### Workaround:
Click the smaller <sup>(+)</sup> icon in the address bar.

---

![failed_to_load_article_from_page_and_new_issue_ _mozilla_readability_and_untitled_3](https://cloud.githubusercontent.com/assets/557895/7171097/fdf88324-e388-11e4-95d3-4e3de507ebec.png)

**Comment by gijsk** [comment]
I hate to say this, but this needs to be in Firefox :: Reading List in bugzilla. Needinfo :markh and/or :adw to see if they can have a look at what's going on there. We can't fix this from within Readability (though we should obviously fix the "failed to load" bit where appropriate, but it sounds like that's #143 .

**Comment by pdehaan** [comment]
Thanks @gijsk. Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1154999
