### ISSUE TITLE
 No reader mode offered for IETF draft spec page

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#145]
http://tools.ietf.org/html/draft-dejong-remotestorage-04

**Comment by ametaireau** [comment]
It seems the issue is not with the readability.js implementation, but rather with the article detection. I don't know where this code leaves though, and any pointers would be appreciated (because obviously, this is behaving in a wrong way).

**Comment by ametaireau** [comment]
(I cannot close here but please do ;))

**Comment by leibovic** [comment]
This sounds similar to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1154295

**Comment by gijsk** [comment]
Yeah... not sure what to do about this. :-\

**Comment by msujaws** [comment]
We can detect if it is a .txt document pretty easily. We will need the parser though to break up the blocks of text and create paragraphs out of them. Could we just look for consecutive line-breaks (more than 1)?

**Comment by msujaws** [comment]
In privileged JS, you can check to see if document.mozSyntheticDocument is true. If so, then check that the body only has one child (<pre>) and that the <pre> has no children.

I don't think we should care about the length of these documents. Checking <pre>.textContent.length is gonna be a very long string for most .txt documents.

**Comment by gijsk** [comment]
This isn't a .txt document though...

**Comment by n1k0** [comment]
Fixed by #188.
