### ISSUE TITLE
'Failed to load article from page' when entering Reader View via bbc.com

### ISSUE THREAD

**Issue by adalucinet** [mozilla/readability#149]
Affected branches:
Beta 38.0b4 (20150415030206), Aurora 39.0a2 (2015-04-16) and Nightly 40.0a1 (2015-04-15)

Sample pages showing this issue:
http://www.bbc.com/sport/0/
http://www.bbc.com/culture

**Comment by n1k0** [comment]
These portal-type pages shouldn't be detected as *readerable* if you ask me.

FWIW, Safari doesn't.

**Comment by n1k0** [comment]
Fixed by #188.
