### ISSUE TITLE
Specific pages from tumblr.com are displaying incorrect headlines

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#159]
**Affected**:
* 38.0b5-build1
* 39.0a2 (2015-04-16)
* 40.0a1 (2015-04-16)

**Sample page**:
* http://jennypizzas.tumblr.com/post/116606491766/shirt-club-analysis

**Screenshot**:
![screenshot from 2015-04-17 14 59 42](https://cloud.githubusercontent.com/assets/5707237/7201659/7153c27c-e512-11e4-9043-6bc06dbf5afd.png)

**Comment by n1k0** [comment]
This is now fixed by #167.
