### ISSUE TITLE
Specific pages from makeuseof.com are displaying the wrong headline in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#164]
**Affected**:
* 38.0b5-build1
* 39.0a2 (2015-04-16)
* 40.0a1 (2015-04-16)

**Sample pages**:
* http://www.makeuseof.com/tag/use-onenote-school-10-tips-students-teachers/
* http://www.makeuseof.com/tag/cinema-dying-movie-theaters-ensure-survival/

**Screenshot**:
![screenshot from 2015-04-17 15 14 51](https://cloud.githubusercontent.com/assets/5707237/7201825/832b9888-e514-11e4-8656-fad3372181c2.png)

**Comment by n1k0** [comment]
Quite interestingly:

```
$ node test/generate-testcase.js makeuseof-1 http://www.makeuseof.com/tag/cinema-dying-movie-theaters-ensure-survival/
JSDOMParser error: expected '</wbr>'

JSDOMParser error: expected '</wbr>'

JSDOMParser error: expected '</wbr>'
```

**Comment by gijsk** [comment]
We really need to make an easy way to export the thing Firefox feeds to Readability, because that will be valid XML and won't have the JSDOMParser parse errors.

**Comment by n1k0** [comment]
Agreed, though while we get errors, expected content is still generated, so no real blocker here.

For the title bug, it seems we strip out whatever exists after a `: ` sequence in the title tag content, which is probably a bit too aggressive. I'll send a patch.
