### ISSUE TITLE
Reader View should not be available for the *.yahoo.com index page

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#173]
**Affected**:
* 38.0b6-build1 (20150420134330)
* 39.0a2 (2015-04-20)
* 40.0a1 (2015-04-20)

**Sample page showing this issue**:
https://ro.yahoo.com/?p=us

**Notes**:
The "Enter Reader View" button is available for the sample page, but clicking it results in an error page stating `Failed to load article from page`. I think Reader View shouldn't be available *at all* for this kind of index/main/portal pages.

**Comment by n1k0** [comment]
This is tracked in [1151087](https://bugzilla.mozilla.org/show_bug.cgi?id=1151087).

**Comment by gijsk** [comment]
Huh, this is just an issue with our detection of main pages, it seems... but would potentially be better off in bugzilla as the logic is in hg. :-\

**Comment by gijsk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1157682, closing this.
