### ISSUE TITLE
CleanPrint toolbar not removed on Wordpress site

### ISSUE THREAD

**Issue by leplatrem** [mozilla/readability#178]
http://bugbrother.blog.lemonde.fr/2015/01/03/de-la-surveillance-de-masse-a-la-paranoia-generalisee/

![selection_554](https://cloud.githubusercontent.com/assets/546692/7292331/70bf5406-e99b-11e4-9037-7e07903cb283.png)

Markup is:

``` html
<a href="." onclick="CleanPrintPrintHtml();return false;"><img src=
    "http://cache-02.cleanprint.net/media/pfviewer/images/CleanPrintBtn_text.png"></a><a href="."
    onclick="CleanPrintGeneratePdf();return false;"><img src=
    "http://cache-02.cleanprint.net/media/pfviewer/images/PdfBtn_text.png"></a><a href="."
    onclick="CleanPrintSendEmail();return false;"><img src=
    "http://cache-02.cleanprint.net/media/pfviewer/images/EmailBtn_text.png"></a>
```

Plugin usage stats https://wordpress.org/plugins/cleanprint-lt/stats/

**Comment by gijsk** [comment]
No longer happening on the linked page, and the WP plugin says:

> This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

So let's close this out.
