### ISSUE TITLE
Images missing from specific buzfeed.com pages in Reader View

### ISSUE THREAD

**Issue by petruta** [mozilla/readability#180]
Affected:
38.0b6-build1 (20150420134330)
39.0a2 (2015-04-22)
40.0a1 (2015-04-22)

Page: http://www.buzzfeed.com/markdistefano/diet-pills-burns-up

**Comment by aehlke** [comment]
I've just tried this article in the latest version of Firefox and it is missing images again.

**Comment by gijsk** [comment]
> I've just tried this article in the latest version of Firefox and it is missing images again.

I filed #584 to track this again.

**Comment by aehlke** [comment]
Any suggested avenues for finding someone to sponsor to solve this? Or is there a preprocessing step workaround?

**Comment by gijsk** [comment]
> Any suggested avenues for finding someone to sponsor to solve this? Or is there a preprocessing step workaround?

I've responded in #180 - let's do further discussion there as this ticket is closed.
