### ISSUE TITLE
Daring Fireball "Colophon" readable version misses list items

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#183]
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/7302979/28aa2cca-e9a2-11e4-98f9-96d3e9afcbbd.png)

### Steps to reproduce:
1. Go to http://daringfireball.net/colophon/
2. Note there is no reader view icon available (at least in Aurora)

### Actual results:
![daring_fireball__colophon](https://cloud.githubusercontent.com/assets/557895/7303016/70d77a02-e9a2-11e4-818a-7598f3c42e30.png)

### Expected results:
A reader-view capable page. I did notice there is a `<div id="Main"><div class="article">...</div></div>` which i thought may be enough to search and scrape on.

Oddly, I did notice that this page is reader-viewable in Safari (go figure):

![daring_fireball__colophon](https://cloud.githubusercontent.com/assets/557895/7303311/9a54aa2e-e9a4-11e4-87cd-c627ec51a674.png)

**Comment by n1k0** [comment]
This works using latest fx-team+master:

![screen shot 2015-04-28 at 14 11 52](https://cloud.githubusercontent.com/assets/41547/7369231/94043f58-edb0-11e4-85ed-3e76f0f598ce.png)

**Comment by n1k0** [comment]
(hmm well, just noticed we're missing the list items, reopening and updating bug title)
