### ISSUE TITLE
No readability results for theonion

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#200]
### Steps to reproduce:
1. Go to http://www.theonion.com/article/health-experts-recommend-standing-up-at-desk-leavi-37957
2. Laugh. Cry. Question all your life decisions.
3. Note that there is no reader view button in the address bar.

As you scroll, you'll notice newer articles appear at the bottom of the page. I don't imagine that'd be a root cause, but maybe there is some magical async article loading. Although if I do view-source and search around the HTML, I can see this which looks like it should be scraper-able:

```html
      <div class="large-thing content-main">
        
          <div class="content-text">
            <div><p>ROCHESTER, MN&#8212;In an effort to help working individuals improve their fitness and well-being, experts at the Mayo Clinic issued a new set of health guidelines Thursday recommending that Americans stand up at their desk, leave their office, and never return. &#8220;Many Americans spend a minimum of eight hours per day sitting in an office, but we observed significant physical and mental health benefits in subjects after just one instance of standing up, walking out the door, and never coming back to their place of work again,&#8221; said researcher Claudine Sparks, who explained that those who implemented the practice in their lives reported an improvement in mood and reduced stress that lasted for the remainder of the day, and which appeared to persist even into subsequent weeks. &#8220;We encourage Americans to experiment with stretching their legs by strolling across their office and leaving all their responsibilities behind forever just one time to see how much better they feel. People tend to become more productive, motivated, and happy almost immediately. We found that you can also really get the blood flowing by pairing this activity with hurling your staff ID across the parking lot.&#8221; Sparks added that Americans could maximize positive effects by using their lunch break to walk until nothing looks familiar anymore and your old life is a distant memory.</p></div>
          </div>
```

... although it looks like the entire article is one long `<p>`.

### Expected results:
Reader view available. Coincidentally, if I save this to Pocket, they have a reader view available.

### Actual results:
No reader view available.

**Comment by pdehaan** [comment]
Even weirder, if I keep scrolling down the page, and newer articles get shim loaded in, then a reader view icon suddenly becomes available, and shows the right article title, but the _wrong_ article contents:

![health_experts_recommend_standing_up_at_desk__leaving_office__never_coming_back](https://cloud.githubusercontent.com/assets/557895/7438804/75746be6-f01f-11e4-9d81-5eda8fd67c6e.png)

**Comment by pdehaan** [comment]
This article seems to load as expected: http://www.theonion.com/article/aerospace-engineers-warn-first-graders-design-for--38523

**Comment by n1k0** [comment]
This is fixed using latest fx-team+latest master:

![screen shot 2015-05-02 at 10 06 51](https://cloud.githubusercontent.com/assets/41547/7440407/0d9fed4e-f0b3-11e4-99a4-9d7992948e63.png)
