### ISSUE TITLE
Reader view available for getpocket.com articles

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#201]
Reader-mode-ception!

I added http://espn.go.com/los-angeles/nba/story/_/id/12801223/los-angeles-clippers-big-man-glen-davis-ankle-questionable-game-7-vs-san-antonio-spurs to my Pocket reading list, then went to getpocket.com and noticed that I could click the article, get a nice reader view version of it from Pocket, and that Firefox's reader mode was available for Pocket's reader view.

Not sure if we just want to try and exclude "getpocket.com" and similar sites from reader view mode since it leads we weird flows like reader viewing a pocket article and then having the pocket button available in FF reader mode.

![los_angeles_clippers_big_man_glen_davis__ankle__questionable_for_game_7_vs__san_antonio_spurs](https://cloud.githubusercontent.com/assets/557895/7438988/40cfcda0-f023-11e4-8621-670deadeeabc.png)

**Comment by n1k0** [comment]
Whatever being domain-{white|black}listing should be filed on Bugzilla imho.

**Comment by leibovic** [comment]
I agree this is a Firefox-specific issue. I don't see any reason to special-case Pocket in Readability.js, just like we don't special-case other pages that already have nice readable content (e.g. Medium).
