### ISSUE TITLE
Blank page when trying to open http://www.teslamotors.com/powerwall in reader mode

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#202]
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/7457388/f69c1958-f240-11e4-9e00-8163adaca952.png)

### Step to reproduce:
1. Go to http://www.teslamotors.com/powerwall
2. CLick the reader mode button in the address bar.

### Actual results:
Blank page. Tab title says:

> #### _"Failed to load article from page"_

![failed_to_load_article_from_page](https://cloud.githubusercontent.com/assets/557895/7457409/32689e16-f241-11e4-9d60-439fb2ed8a8c.png)

### Expected results:
Scraped content, or no reader mode button available.

**Comment by n1k0** [comment]
Fixed using latest fx-team+latest master:

![screen shot 2015-05-04 at 18 44 09](https://cloud.githubusercontent.com/assets/41547/7457554/a391a42e-f28d-11e4-990e-39b04cdf193c.png)

**Comment by pdehaan** [comment]
@n1k0 

Should I be testing with something other than FF Nightly?

Before I file a new bug, is this working in fx-team+latest master, or different issue?
https://www.kickstarter.com/projects/prtyny/disco-dog-the-smartphone-controlled-led-dog-vest/updates

**Comment by n1k0** [comment]
> Should I be testing with something other than FF Nightly?

Testing with latest readability files would help, indeed. You can try replacing both `Readability.js` and `JSDOMParser.js` files under the `toolkit/components/reader` directory of your FFx instance with latest versions from this repo. Using a freshly version compiled from the *fx-team* branch would probably help too.

**Comment by n1k0** [comment]
> Before I file a new bug, is this working in fx-team+latest master, or different issue?
> https://www.kickstarter.com/projects/prtyny/disco-dog-the-smartphone-controlled-led-dog-vest/updates

Reader mode fails at parsing this page, you can safely file an issue :) (thanks!)

**Comment by pdehaan** [comment]
> Reader mode fails at parsing this page, you can safely file an issue (as it shouldn't be detected as readerable)

Filed as #214
