### ISSUE TITLE
Intermittent parse issues in Nightly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#205]
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/7477675/42f8d92a-f30a-11e4-8bad-c275be7f1ae3.png)

I don't expect there is much we can do with this, but wanted to file it regardless #seesomethingfilesomething

I started up today's FF Nightly build and randomly went to ESPN and saw there was a reader mode icon for http://espn.go.com/blog/marc-stein/post/_/id/3816/summer-scoop-san-antonio-spurs

When I clicked the reader mode button, the UI said that there was no reader mode available, but clicking it again showed a readability version of the page. Not sure why it failed to parse the first time...

![failed_to_load_article_from_page](https://cloud.githubusercontent.com/assets/557895/7477689/54e1d65a-f30a-11e4-8295-495cd45be80c.png)

![stein_s_scoop__next_for_duncan__spurs__-_marc_stein_-_espn](https://cloud.githubusercontent.com/assets/557895/7477700/6690cdac-f30a-11e4-9237-ea781911d9e9.png)

**Comment by n1k0** [comment]
> When I clicked the reader mode button, the UI said that there was no reader mode available, but clicking it again showed a readability version of the page. Not sure why it failed to parse the first time...

I remember having experienced something similar a few times (rarely though). I wonder if we shouldn't "wait a little" for contents being fully loaded/generated before actually sending serialized contents to the worker. Maybe that's already the case btw, I'm didn't dig too far into the chrome part of things.

Also, I don't think this is an issue related to code hosted in this very repository, so I suspect you'd rather want to file it in Bugzilla.

**Comment by pdehaan** [comment]
Filed in "Toolkit::Reader Mode" as https://bugzilla.mozilla.org/show_bug.cgi?id=1162117

**Comment by n1k0** [comment]
Thanks. Closing this here.
