### ISSUE TITLE
m.thepaper.cn - text is not visible

### ISSUE THREAD

**Issue by karlcow** [mozilla/readability#210]
From https://github.com/webcompat/web-bugs/issues/1035

URL: http://m.thepaper.cn/newsDetail_forward_1325054
Browser / Version: Firefox Mobile 40.0
Operating System: Android
Problem type: Text is not visible

Steps to Reproduce
1) Navigate to: http://m.thepaper.cn/newsDetail_forward_1325054
2) …

Expected Behavior:阅读模式显示文章正文。

Actual Behavior:阅读模式下正文部分显示网站的用户协议。

**Translation**
Expected Behavior: Switch to Reader Mode, the content should be displayed correctly.
Actual Behavior: It displayed different content (some agreement document for registering this website) when user switch to Reader Mode.

**Comment by n1k0** [comment]
This page is no more detected as readerable (latest master+latest fxteam)

![screen shot 2015-05-06 at 14 44 37](https://cloud.githubusercontent.com/assets/41547/7493143/7ae2db3e-f3fe-11e4-93fb-e4e23b7d0a41.png)
