### ISSUE TITLE
Specific pages from washingtonpost.com are missing their byline information

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/readability#218]
Affected builds:
- Firefox 38.0.5 beta 1

Affected OS`s:
- Windows 7 64-bit
- Mac OS X 10.9.5
- Ubuntu 14.04 32-bit

STR:
1. Visit http://www.washingtonpost.com/opinions/david-camerons-wizardry-and-britains-uncertain-future/2015/05/10/cee108aa-f5d4-11e4-84a6-6d7c67c50db0_story.html?hpid=z2
See byline: By E.J. Dionne Jr
2. Enter reader view

Expected results: 
Byline is present in reader view

Actual results: 
No byline present in reader view

**Comment by gijsk** [comment]
This seems to work now. :-)
