### ISSUE TITLE
Image is scaled differently for same washingtonpost article

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/readability#219]
Affected builds:
- Firefox 38.0.5 beta 1

Affected OS`s:
- Windows 7 64-bit
- Mac OS X 10.9.5
- Ubuntu 14.04 32-bit

STR:
1. Visit http://www.washingtonpost.com/opinions/david-camerons-wizardry-and-britains-uncertain-future/2015/05/10/cee108aa-f5d4-11e4-84a6-6d7c67c50db0_story.html?hpid=z2
2. Enter reader view
3. Click the second image (the small one)
4. Hit back button

Expected results:
Image is scaled the same as first time. Or maybe the image is badly scaled the first time and right the second time.

Actual results: 
Image scaled differently on the same article.

**Comment by gijsk** [comment]
Unfortunately, it seems the article has changed, and there isn't a second image anymore, so not a lot we can do here anymore
