### ISSUE TITLE
 Photos in Reader View do not render on iPhone

### ISSUE THREAD

**Issue by st3fan** [mozilla/readability#221]
Moved from https://bugzilla.mozilla.org/show_bug.cgi?id=1141708

The URL in question is http://www.nytimes.com/2015/03/10/opinion/elusive-justice-in-wisconsin.html?_r=0

**Comment by gijsk** [comment]
This works on desktop (38 beta). Any idea what's different on iPhone and what to make of the original report's indication this works on iPads but not iPhones? Somewhat seems like a webview/iOS issue to me...

**Comment by gijsk** [comment]
(or perhaps the site does UA-based things that break us... we'd need the original HTML and how it differs from what Firefox for desktop gets served)

**Comment by gijsk** [comment]
Closing this out as there isn't enough info here to do anything.
