### ISSUE TITLE
Charts figures are displayed below the pictures on specific nytimes.com page 

### ISSUE THREAD

**Issue by petruta** [mozilla/readability#222]
Affected:
Firefox 38.0.5 beta 1 - build 2
latest Aurora 40.0a2 (2015-05-11)
latest Nightly 41.0a1 (2015-05-11)

Page: 
http://www.nytimes.com/2015/03/19/business/economy/fed-interest-rates-fomc-meeting.html?_r=0 

Result:

![3vmjjvs](https://cloud.githubusercontent.com/assets/41547/7609416/f774f19a-f972-11e4-88be-009978891a44.png)

**Comment by n1k0** [comment]
These charts are in the form:

```html
<div id="g-0319-web-FED-945-graphic">
  <img id="g-ai1-0" class="g-aiImg" …>
  <p class="g-aiPstyle0">Change in real G.D.P.</p>
  <p class="g-aiPstyle0">Unemployment rate</p>
  <p class="g-aiPstyle0">Inflation</p>
  <p class="g-aiPstyle1">+3.5</p>
  <p class="g-aiPstyle2">%</p>
  <p class="g-aiPstyle1">10</p>
  <p class="g-aiPstyle2">%</p>
  …
</div>
```

These `<p>`s aren't hidden, they actually define chart labels… Don't have a clue how we could solve this.

**Comment by n1k0** [comment]
Safari renders this:

![screen shot 2015-05-13 at 13 19 03](https://cloud.githubusercontent.com/assets/41547/7609379/bba435fe-f972-11e4-9eeb-e37bd3e99dbb.png)

It seems they strip `<p>`s with very few chars. I feel like taking this approach could break other valid use cases, though. Thoughts?

**Comment by gijsk** [comment]
Yeah, it seems too risky to follow Safari's lead here, in the last week before the final code drop (!). And even then - the Safari output isn't particularly amazing either.

**Comment by gijsk** [comment]
We now longer include the graph, but also don't include the other rubbish... so that's a win, I guess? Going to close this out as it's unclear what we'd improve here.
