### ISSUE TITLE
reader mode offered for restmail.net JSON blob

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#225]
## Steps to reproduce:
1. Open https://restmail.net/mail/trypocket_es
## Actual results:

Reader mode icon appears in address bar. The screenshot didn't capture it, but it was also the first time I'd encountered reader mode (brand new profile), so it threw up some tour-esque UI.

![mozilla_firefox](https://cloud.githubusercontent.com/assets/557895/7622656/441cb060-f986-11e4-8261-689390993596.png)
## Expected results:

It looks like a JSON blob, not sure why that comes off as readerable.

**Comment by gijsk** [comment]
Because it ends up in a <pre> and the text is long enough, that is why.

**Comment by gijsk** [comment]
Happily, now that we also offer a json viewer, this no longer happens, I think.
