### ISSUE TITLE
Huffington-post article is not correctly displayed in reader view

### ISSUE THREAD

**Issue by petruta** [mozilla/readability#226]
Affected: 
Firefox 38.0.5 beta 3
latest Aurora 40.0a2 2015-05-18
latest Nightly 41.0a1 2015-05-18

Source: http://www.huffingtonpost.com/2015/05/18/hillary-clinton-emails_n_7310278.html

Result: http://i.imgur.com/rWGphk7.png - all the categories are shown and "Around the web" section.

**Comment by gijsk** [comment]
The article is a 404.
