### ISSUE TITLE
Reader View is available for various websites although it shouldn't

### ISSUE THREAD

**Issue by adalucinet** [mozilla/readability#227]
Reproducible on:
Beta 38.0.5 beta 3 - build1 (20150518141916)
Affected platforms: Windows 7 x86, Windows 8.1 x64, Mac OS X 10.9.5 and Ubuntu 14.04 x64 

Steps to reproduce:
1. Navigate to http://espn.go.com/
2. Click on any article
3. Hit Back button
Actual result: Enter Reader View button is visible in URL bar for espn.com homepage
4. Click on Enter Reader View button
Actual result: 'Failed to load article from page'

Sample pages showing this issue:
* http://www.usatoday.com/
* https://www.youtube.com/
* http://espn.go.com/

**Comment by gijsk** [comment]
This should have been filed on bugzilla. Anyway, let's investigate here because this looks very broken. @leibovic , ideas on what's going on here? :-(

**Comment by gijsk** [comment]
So the page does some unholy replaceState magic and we seem to get 0 pagehide/pageshow events - just an `onLocationChange` in the browser that asks us to update the reader button.

At this stage I am too scared to make onLocationChange always reset `browser.isArticle` to `false` - it might break other stuff. I also do not understand why there is no `pageshow/pagehide` event.

**Comment by gijsk** [comment]
Closing in favour of https://bugzilla.mozilla.org/show_bug.cgi?id=1166771 .
