### ISSUE TITLE
Previously reader view page is displayed when switching through youtube playlist videos

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/readability#229]
Affected builds:
Firefox 38.0.5 beta 3

Affected OS`s:
Windows 7 32-bit
Windows 8.1 64-bit
Mac OS X 10.9.5
Ubuntu 14.04 64-bit

STR:
1. Open a youtube playlist. (eg: https://www.youtube.com/watch?v=i_kF4zLNKio&index=2&list=PL55713C70BA91BD6E)
2. Enter reader view.
3. Exit reader view.
4. Click on another video from the playlist.
5. Enter reader view.

Expected results:
The right content is displayed.

Actual results: 
Content from previous video is displayed. Exiting reader view and opening reader view a second time will display the right content.

**Comment by gijsk** [comment]
We no longer offer reader view for these.
