### ISSUE TITLE
Mobile reader article doesn't reflow correctly

### ISSUE THREAD

**Issue by arusahni** [mozilla/readability#231]
When reading [this distrowatch article](http://distrowatch.com/weekly.php?issue=20150525#kubuntu), the page content doesn't fit the viewport.  It appears to be due to the images included in the article.

![screenshot_2015-05-25-16-27-12](https://cloud.githubusercontent.com/assets/139487/7802026/26edaefc-02fc-11e5-9300-34c44326f621.png)

This is happening on the latest Fennec Aurora builds.

**Comment by leibovic** [comment]
Thanks for the report! This looks like an issue with the reader view CSS on Firefox for Android (not an issue with Readability.js), so I filed a Firefox for Android bug about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1168850.

**Comment by arusahni** [comment]
Sorry for the misfile!
