### ISSUE TITLE
Article text/media all missing in Reader View (Firefox for iOS)

### ISSUE THREAD

**Issue by AaronMT** [mozilla/readability#235]
Filed over at https://bugzilla.mozilla.org/show_bug.cgi?id=1182260

URL: http://m-yahoo.thepostgame.com/blog/heroes-villains/201507/brock-lesnar-tears-door-car-accidentally-throws-it-young-wwe-fan

Article in reader-view is missing all content

**Comment by gijsk** [comment]
The URL redirects infinitely on desktop, and without details about what's going wrong on iOS here (offending markup or whatever), there's little we can do.
