### ISSUE TITLE
Bad readability detection on nvidia.com

### ISSUE THREAD

**Issue by AaronMT** [mozilla/readability#240]
Visit nvidia.com, desktop-optimized country select page. We should not offer reader here.

![screen shot 2015-07-28 at 2 14 31 pm](https://cloud.githubusercontent.com/assets/102331/8939538/f94498bc-3532-11e5-871b-34365263f44a.png)

**Comment by leibovic** [comment]
@st3fan is iOS using `isProbablyReaderable` or just using the `parse` output?

**Comment by gijsk** [comment]
If this were bugzilla, I'd close this "incomplete". It's not clear where any issue is, and nvidia seems to have changed their website since then...
