### ISSUE TITLE
Bad readability on cbc.ca

### ISSUE THREAD

**Issue by AaronMT** [mozilla/readability#241]
Visit cbc.ca, I get reader-view.

![screen shot 2015-07-29 at 10 30 36 am](https://cloud.githubusercontent.com/assets/102331/8960200/dd0b4e8e-35dc-11e5-8473-13816a81d9a3.png)

Visit an actual article, and I get nothing.

![screen shot 2015-07-29 at 10 30 59 am](https://cloud.githubusercontent.com/assets/102331/8960221/ec054278-35dc-11e5-85bc-87403eabd687.png)

**Comment by st3fan** [comment]
Not sure what the CBC is doing but this also does not work in Safari or Firefox.

**Comment by gijsk** [comment]
I no longer get reader view offered on the homepage, and at a glance [an article](https://www.cbc.ca/radio/asithappens/as-it-happens-thursday-edition-1.5056337/ex-yale-admissions-dean-worries-college-scandal-will-keep-underprivileged-kids-from-applying-1.5056345) offers reader mode correctly, and that seems to work fine.
