### ISSUE TITLE
Parse appears to fail on SF Gate mobile article

### ISSUE THREAD

**Issue by mcomella** [mozilla/readability#244]
Bug originally [from Bugzilla:](https://bugzilla.mozilla.org/show_bug.cgi?id=1195312)

Title: _SF gate article prompts for reader but fails to load article_

_Go to [the SF Gate article](http://m.sfgate.com/news/article/San-Francisco-sees-spike-in-car-break-ins-6447584.php) and try to open reader - see title._

Margaret made some suggestions in comment 2:

_This also happens on desktop Firefox. This issue would be caused by Readability. Either we should make sure `isProbablyReaderable` returns false, or we should look more closely into why `parse` is failing. Given that this is an article, it's probably the `parse` method that should be improved._

**Comment by gijsk** [comment]
The link in the initial comment is a 404 now, and a random article I tried on sfgate.com seems to work correctly now, so closing this out.
