### ISSUE TITLE
Reader View of page is wider than original, adding a horizontal scroll bar

### ISSUE THREAD

**Issue by cpeterso** [mozilla/readability#245]
Opening the following page in Firefox for iOS version 1.0.1 (44) Reader View widens the page so it has a horizontal scroll bar in Reader View when the original page did not.

https://hamidreza-s.github.io/erlang%20garbage%20collection%20memory%20layout%20soft%20realtime/2015/08/24/erlang-garbage-collection-details-and-why-it-matters.html

**Comment by gijsk** [comment]
I don't have an iDevice, but looking on desktop, I presume this is just the text size that we use for the <tt>monospace</tt> text ? If so, I'm not sure what we should do about that from the readability perspective - we could change the stylesheet that gets applied to it, but that would be an iOS bug.

**Comment by gijsk** [comment]
Going to close this out because it's not clear this is actually a readability issue; it's more likely an iOS styling issue, and I have no way of helping get it fixed beyond pinging the iOS team, which already happened here.
