### ISSUE TITLE
cannot parse www.geek.com

### ISSUE THREAD

**Issue by mcepl** [mozilla/readability#249]
Is this the right place to report that the Reader View on Firefox for Android 41 doesn’t seem to be able to parse page http://www.geek.com/android/meet-focal-the-new-camera-app-for-cyanogenmod-1563506/ ?

**Comment by gijsk** [comment]
It could be - but it works for me on desktop. Is this mobile-specific for you?

**Comment by mcepl** [comment]
Hmm, true the desktop 43 FF doesn't have problem, desktop 41 on Android does.

**Comment by gijsk** [comment]
@leibovic do you have ideas? Is the mobile website different in a way that causes us to fail to parse it correctly?

**Comment by xuhdev** [comment]
It works good for me on firefox for android 44.

**Comment by gijsk** [comment]
Closing this per the last comment.
