### ISSUE TITLE
The parse function scrambles the document

### ISSUE THREAD

**Issue by hsemarap** [mozilla/readability#250]
When I run 
`var article = new Readability(uri, document).parse();`

the parse() function scrambles the document by removing various content in the page, for instance the main article, images. 

Screenshots:
Before:
![before readability](https://cloud.githubusercontent.com/assets/2169155/10539466/6742b276-741d-11e5-8994-164b1b7b67d6.png)
After:
![after readability](https://cloud.githubusercontent.com/assets/2169155/10539471/6cd2d770-741d-11e5-9131-9925830d0a2d.png)

From what I understand, readability works by removing these elements from the DOM.
Is there a way to avoid scrambling the page apart from simply reloading ?

**Comment by gijsk** [comment]
I don't actually understand what you mean. Are you saying you want readability to do nothing? Or to somehow do its job but not remove elements? Or something else?

**Comment by hsemarap** [comment]
Is it possible to pass some sort of clone of the document object to the parse() function so that it runs without modifying the user's view of the web page ?

**Comment by gijsk** [comment]
Of course that's possible - you can create the clone and pass that to readability instead. There is no need for it to be the document that is currently displayed... it's still not clear to me what you're actually asking for! :-)

**Comment by gijsk** [comment]
(oh, though I should mention that in terms of decisions made using visibility information, having a document that is currently laid out will work better...

**Comment by hsemarap** [comment]
Cloning the document worked, Thanks !!
