### ISSUE TITLE
iab.com article has Reader View button but displays "Failed to load article from page" error

### ISSUE THREAD

**Issue by cpeterso** [mozilla/readability#251]
STR:
0. I am using Firefox Nightly 44 on OS X 10.11.
1. Load http://www.iab.com/news/lean/ ("Getting LEAN with Digital Ad UX" article)
2. Click the Reader View button.

RESULT:
The Reader View page is blank except for a "Failed to load article from page" error

**Comment by gijsk** [comment]
This works when the document is requested via XHR (so if you close the "failed" tab, and then reopen the tab, it works). I expect the ads are somehow breaking things. I don't have time to investigate why right now.

**Comment by gijsk** [comment]
This is working on fx-team tip which has the changes from #252, so I'm closing this. :-)
