### ISSUE TITLE
Is it possible to disable Readability for my website?

### ISSUE THREAD

**Issue by Radiohead99** [mozilla/readability#257]
Is it possible to disable Readability for my website http://siriusblack.org ?
Because I don't want people to use this because users see my website a way I don't want to. 
Moreover people can easily copy/paste content as an other webmaster ask there => https://github.com/mozilla/readability/pull/255

**Comment by gijsk** [comment]
No, it is not possible. See the replies in #255 for the reasoning here.

**Comment by Radiohead99** [comment]
Gijsk,

Speaking to a Dev, he said it must be really easy to add something on the "header", to avoid this problem!

I read all your answer about https://github.com/mozilla/readability/pull/255 , but as a webmaster I disagree. With "Readibility" you help people to stole our content. Of course, they are always plenty of possibility to stole content as you said, BUT "Readibility" is by far the New best easy way to stole content! You told to Lancomega to contact the appropriate court, for each article copy/paste? Are serious??? Could you even imagine the time needed to create articles and to be with law courts for each people having copy/paste your content??

No offense, I respect your work, but you are really not helping webmasters, and even if you think you help users, don't forget to remember that Webmasters are doing the web what is like. Hope this message will follow to all people working on the project, and I think you will only undertand what webmasters like me and Lancomega said, the day you will have your own website with big contents.
