### ISSUE TITLE
Failed to parse texinfo generated pages

### ISSUE THREAD

**Issue by xuhdev** [mozilla/readability#264]
For exampl this page: http://www.gnu.org/software/emacs/manual/html_node/elisp/Lisp-History.html#Lisp-History

Although it's clean for desktop, it still helps a lot on a mobile device.

**Comment by gijsk** [comment]
If I put:

```
about:reader?url=http://www.gnu.org/software/emacs/manual/html_node/elisp/Lisp-History.html
```
in my URL bar and hit enter, it works for me. So it seems like we're just not seeing the content as readerable? There might just not be enough text on the page for that to work...

**Comment by xuhdev** [comment]
Thanks! How can I adjust the length of text for the button to show... I think it's long enough for a mobile device.

**Comment by gijsk** [comment]
There isn't currently a way to change the length via a preference or something.

We should probably adjust the algorithm to take the total length of the page into account somehow. I'm not sure off-hand how to do that: we don't have access to the length in bytes of the network transfer, and obviously getting .innerHTML or something just to determine their length will be quite slow for large pages. It's also not clear to me what bits should 'count' anyway... @leibovic or @n1k0 , do you have thoughts about what we could do here?

**Comment by gijsk** [comment]
We've relaxed some of the restrictions here now so this is working, AFAICT.
