### ISSUE TITLE
Not working properly in "https://www.linkedin.com/pulse".

### ISSUE THREAD

**Issue by MrNikunjPatel** [mozilla/readability#265]
This module is not responding properly with "https://www.linkedin.com/pulse" and "http://timesofindia.indiatimes.com/india/Modi-has-delivered-results-despite-oppns-negativity-BJP/articleshow/50799865.cms"

As result, It shows random content from listed news instead of current URL. 
URL changed for both when I'm scrolling.

Hope, There should be a solution, as both sites are popular and really need "Readability".

**Comment by gijsk** [comment]
The first gives me a 404, the second seems to work, so going to close this out.
