### ISSUE TITLE
Reader mode not proposed for site bortzmeyer.org

### ISSUE THREAD

**Issue by OlivierJaquemet** [mozilla/readability#269]
Accessed the following URL :
http://www.bortzmeyer.org/drown.html

Actual results:
No "reader mode" icon visible in toolbar

![Firefox for Android screenshot](https://bug1254036.bmoattachments.org/attachment.cgi?id=8727303)

Expected results:
Expecting "reader mode" icon visible in toolbar since site is not suitable for proper reading on mobile

(bug initialy entered at https://bugzilla.mozilla.org/show_bug.cgi?id=1254036)

**Comment by gijsk** [comment]
The markup is a bit suboptimal (`<div class="para">`) but there are nested `<p>`s available so I don't actually know off-hand why our detection algorithm is failing...

**Comment by gijsk** [comment]
So `isProbablyReaderable` returns true. It works with e10s on, stops working on the same profile with e10s off (this is all on desktop). Still no idea why. :-\

**Comment by gijsk** [comment]
OK, this seems to be because for some reason when we request bounds for all of the elements on this page, they're all 0, even though a MozAfterPaint event has fired. That's a gecko issue. It doesn't happen in e10s mode. Which means we go back to bugzilla, because this can't be fixed in Readability.

**Comment by gijsk** [comment]
I put up a patch in bugzilla, so I'm going to close this issue. Thanks, and sorry for the run-around in terms of where to file reports... I noticed you filed another issue earlier today, and it seems fairly likely that one should indeed be here. Just to keep it confusing. :-(

**Comment by OlivierJaquemet** [comment]
Thank you @gijsk for your work. There is absolutely no problem regarding the issue filling. As a developper dealing with many projects, I completely understand it happens more frequently that we want to ;)
