### ISSUE TITLE
Reader View not displaying BBC news articles as expected (only on iOS)

### ISSUE THREAD

**Issue by krudnitski** [mozilla/readability#271]
Filed a [bug in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1255357), but also posting the issue here. 

Running Firefox for iOS Beta (3.0). 

Go to: bbc.co.uk/news/uk-politics-35762443

The header image is very large, whilst the header text (title text) and article text are much smaller as a result. This actually looks like a regression. It behaves as expected on version 2.1 (14). 

Firefox for Android behaves better and Safari behaves really nicely.

![img_4136](https://cloud.githubusercontent.com/assets/5297048/13667740/dfdbf738-e6af-11e5-9d40-18fa68b7f0ef.PNG)

**Comment by gijsk** [comment]
If this works on android + desktop then I suspect it's an iOS CSS-for-reader-mode, or potentially a webkit-CSS-implementation-related issue. I don't have an iDevice and don't really know much about how iOS uses Readability right now... @st3fan or @rnewman, can you help?

**Comment by gijsk** [comment]
Oh, that or the BBC sends us 'special' markup for iOS that causes this issue... which would be another 'fun' possibility, but it'd need someone to look at what's actually going wrong on their iDevice.

**Comment by st3fan** [comment]
http://www.bbc.com/news/world-europe-35772206 looks pretty much the same as in Safari for me. 

Same with http://www.bbc.com/news/world-europe-35771292

**Comment by krudnitski** [comment]
With bbc.co.uk/news/businses-35770754, same problem. On Fx iOS Beta 3.0, it formats like my previous example. But on Safari, it looks great (see attached)
![img_4137_fxiosbb](https://cloud.githubusercontent.com/assets/5297048/13671247/b2ac83e2-e6c6-11e5-8200-af44460bbcdd.PNG)
![img_4138_safari](https://cloud.githubusercontent.com/assets/5297048/13671248/b2ae625c-e6c6-11e5-812f-f80eae19429f.PNG)

**Comment by st3fan** [comment]
I don’t see this when I enable Reader Mode for that specific article. For me it looks pretty much similar to Safari.

Can you try the following: change your phone to landscape and back and see if that helps.

Try to change the Reader Mode settings (font size) and see if that makes a difference.

Does it happen for other articles on BBC News too? Or just this one?

 S.

**Comment by st3fan** [comment]
I see it too now …

Karen, do you run a Content Blocker? Like Focus?

I think Safari blocks something on the page that makes the difference.

(Reader Mode pages are cached, so it is hard to turn content blocking off and then reload - that wont show a diff)

 S.

**Comment by krudnitski** [comment]
You responded before I hit send! J



Glad you see it, too! It happens on all of my BBC articles, and I was
trying to see what Safari was doing for articles on the Telegraph and NY
Times, but for some reason, Safari has given up trying to connect (!!) so
I’m currently rebooting the device.



Yes, I do have Focus (I installed it and forgotten about it) which would
affect Safari!



You are so clever.



*From:* Stefan Arentz [mailto:notifications@github.com]
*Sent:* 10 March 2016 14:04
*To:* mozilla/readability <readability@noreply.github.com>
*Cc:* krudnitski <krudnitski@mozilla.com>
*Subject:* Re: [readability] Reader View not displaying BBC news articles
as expected (only on iOS) (#271)



I see it too now …

Karen, do you run a Content Blocker? Like Focus?

I think Safari blocks something on the page that makes the difference.

(Reader Mode pages are cached, so it is hard to turn content blocking off
and then reload - that wont show a diff)

S.

> On Mar 10, 2016, at 8:51 AM, Stefan Arentz <sarentz@mozilla.com> wrote:
>
> I don’t see this when I enable Reader Mode for that specific article. For
me it looks pretty much similar to Safari.
>
> Can you try the following: change your phone to landscape and back and
see if that helps.
>
> Try to change the Reader Mode settings (font size) and see if that makes
a difference.
>
> Does it happen for other articles on BBC News too? Or just this one?
>
> S.
>
>> On Mar 10, 2016, at 8:48 AM, krudnitski <notifications@github.com
<mailto:notifications@github.com>> wrote:
>>
>> With bbc.co.uk/news/businses-35770754 <
http://bbc.co.uk/news/businses-35770754>, same problem. On Fx iOS Beta 3.0,
it formats like my previous example. But on Safari, it looks great (see
attached)
>> <
https://cloud.githubusercontent.com/assets/5297048/13671247/b2ac83e2-e6c6-11e5-8200-af44460bbcdd.PNG
>
>> <
https://cloud.githubusercontent.com/assets/5297048/13671248/b2ae625c-e6c6-11e5-812f-f80eae19429f.PNG
>
>> —
>> Reply to this email directly or view it on GitHub <
https://github.com/mozilla/readability/issues/271#issuecomment-194846913>.
>>
>


—
Reply to this email directly or view it on GitHub
<https://github.com/mozilla/readability/issues/271#issuecomment-194857629>.[image:
Image removed by sender.]

**Comment by st3fan** [comment]
@gijsk I see a lot of weird content in the readerized page. Like there is advertisement JS in there and a bunch of other stuff that I think should be filtered out?
[bbc.txt](https://github.com/mozilla/readability/files/167265/bbc.txt)

**Comment by gijsk** [comment]
Yeah, I don't know why that wouldn't be filtered out. What kind of DOM are you giving readability? We strip out `<script>` tags in `parse` here: https://github.com/mozilla/readability/blob/master/Readability.js#L1782

**Comment by gijsk** [comment]
@st3fan - can you post the source that goes into that as well? I have a suspicion of what might be the issue here... `removeScripts` uses `Array.prototype.forEach.apply` to iterate over the node list - but if whatever DOM you're using implements a live node list, and implements `forEach` by index... half the script nodes are going to get missed... I don't have an iOS device and so I can't test this hypothesis, but if you can confirm that that's it, or if saving the document you're feeding into readability without the script tags gets you the 'right' result, I can look at fixing this.

**Comment by gijsk** [comment]
The diagnosis from my previous comment seems to now have been independently filed as issue #280 .

**Comment by gijsk** [comment]
Fixed by #300, I expect. It'd be useful if @st3fan could confirm (I don't have an iDevice)?
