### ISSUE TITLE
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#273]
I just casually noticed this while trolling through some verbose logs on ActivityStream...

> console.log: activity-streams: [JavaScript Warning: "SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function" {file: "resource://gre/modules/ReaderMode.jsm -> resource://gre/modules/reader/Readability.js" line: 69 column: 13 source: "    function logEl(e) {
> "}]

It looks like this is coming from the following code, [./Readability.js:63](https://github.com/mozilla/readability/blob/edfe703a418baa2d03e4200b8efb891f087f3df3/Readability.js#L63) which seems to be trying to define a function within an `if` block. I'm guessing that strict mode prefers to not do that, as the function would probably be hoisted and possibly lead to some confusing behavior.

See:
1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Paving_the_way_for_future_ECMAScript_versions
2. http://whereswalden.com/2011/01/24/new-es5-strict-mode-requirement-function-statements-not-at-top-level-of-a-program-or-function-are-prohibited/

**Comment by gijsk** [comment]
Yeah, seems like we could either move the helper out of the block scope or use a function expression instead. Want to do a pull request? :-)

**Comment by pdehaan** [comment]
Done in PR #274.

**Comment by gijsk** [comment]
Annnnd I missed the eslint remark. @pdehaan , looks like http://eslint.org/docs/rules/no-inner-declarations is what we want? Or am I misreading that?

**Comment by pdehaan** [comment]
@gijsk Great catch! That indeed looks like the rule. I'll do another PR shortly to add that rule to the .eslintrc file.

```sh
$ npm run lint

> readability@0.0.1 lint /Users/pdehaan/dev/github/readability
> eslint .


/Users/pdehaan/dev/github/readability/Readability.js
  63:5  error  Move function declaration to function body root  no-inner-declarations

✖ 1 problem (1 error, 0 warnings)
```
