### ISSUE TITLE
<br> breaks readability

### ISSUE THREAD

**Issue by doublex** [mozilla/readability#276]
Hello,
Testcase:
https://gist.githubusercontent.com/doublex/6798788388187479f46e/raw/c654ca8a7278528572ade338a54177d4853fde38/readability.html
If if remove the "<br>" - the text is recognized as probably readerable.
Thanks

**Comment by gijsk** [comment]
How are you testing this? With Firefox, or are you using Readability.js yourself from code?

I copied your testcase to http://output.jsbin.com/qibequfugo and it seems to work for me in recent versions of Firefox.

If you're using Readability.js yourself, did you ensure the HTML you pass it is valid XML?

**Comment by doublex** [comment]
You are right.
I have cleaned the HTML via:
````
    var doc = jsdom.jsdom( source, {
        features: {
            FetchExternalResources: false,
            ProcessExternalResources: false
        }
    });
    removeCommentNodesRecursively( doc );
    var cleaned = jsdom.serializeDocument( doc );
````

And this broke the detection.
