### ISSUE TITLE
Nearly identical markup on two pages. One fails to render, wonder why?

### ISSUE THREAD

**Issue by un33k** [mozilla/readability#277]
There are two pages that are rendered via the same template code.  The are nearly identically as far as the markup goes.

#1 - https://simplyfound.com/article/6d733be2aef4/apple-pay-slow-and-steady-wins-the-race

The above works very well when clicking on the READER icon.

#2 - https://simplyfound.com/article/eb9a5e137034/raspberry-pi-3-the-credit-card-sized-pc-that-cost-only-35-all-time-bestselling-computer-in-uk

The above fails with the "**Failed to load article from page**" message.

Same logic produces both pages, but one works and the other does not.

It would be cool to have a errorno of some sort displayed alongside the error message for debugging purposes.

**Comment by gijsk** [comment]
Fixed by #278
