### ISSUE TITLE
First paragraph not rendered for nytimes.com

### ISSUE THREAD

**Issue by petard** [mozilla/readability#286]
Running on pages from NYTimes like [this one](http://www.nytimes.com/2016/04/13/science/alpha-centauri-breakthrough-starshot-yuri-milner-stephen-hawking.html) the first paragraph is not rendered.

The article.content then starts half-way into the text.

**Comment by jjdelc** [comment]
Here is another [page from NYTimes that also skips the first 4 paragraphs](https://www.nytimes.com/2017/02/22/technology/trump-news-media-ignore.html?smprod=nytcore-iphone&smid=nytcore-iphone-share&_r=0)

* https://pageshot.net/qbSyzzYub1PeH1dO/www.nytimes.com
* https://pageshot.net/Lgb1JjAPKk0NaBVl/about

**Comment by jjdelc** [comment]
@gijsk The screenshot is from nightly. Although from 2017-02-06. Updating to nightliest and checking again.

**Comment by jjdelc** [comment]
Confirm that it works now with nightly 2017-02-23! Thanks!

**Comment by gijsk** [comment]
Closing per the latest comments. :-)
