### ISSUE TITLE
reader mode button not offered on Firefox for Android for article

### ISSUE THREAD

**Issue by msujaws** [mozilla/readability#291]
The button is offered on desktop Firefox but not on Firefox for Android.

http://www.dailybreeze.com/social-affairs/20160509/owners-of-closed-torrance-bakery-accused-of-human-trafficking-ordered-to-pay-workers-152-million

I think it may be because the article is loaded through some XHR request.

**Comment by msujaws** [comment]
This was reported at https://www.reddit.com/r/firefox/comments/4io50x/is_there_a_night_mode_for_firefox/d323nk2

**Comment by gijsk** [comment]
Seems to work in 66 beta on my android today. \o/
