### ISSUE TITLE
The title of the article is truncated on some webpages

### ISSUE THREAD

**Issue by TPXP** [mozilla/readability#295]
Hello!

I noticed that, in reader mode, one of the articles published on my personal blog (in French, sorry!) is not correctly rendered in reader mode on Firefox. https://tpxp.ddns.net/article.php?id=55d3971de00fc8ff098b4567

This is not the case with my other article, which reader mode displays the title correctly : https://tpxp.ddns.net/article.php?id=553d4dc9e00fc817018b4567 .

Could there be a problem with the "ARM :" string ? I think it is not that much uncommon to use acronyms on the internet (for example WHO for World Health Organization), so this bug might be worth some investigation. :wink: 

Thank you for your help.

Thomas P.

**Comment by Farbdose** [comment]
@TPXP Ping
The referenced domain [is down](http://downforeveryoneorjustme.com/tpxp.ddns.net/) is this temporary or permanent?

**Comment by TPXP** [comment]
This is a temporary down, I'm having troubles with the hosting of this website but will do my best to bring it back up as soon as possible.

**Comment by tigt** [comment]
It's probably the logic that extracts the "page title" from `<title>` elements that contain the page title and the site title joined with separators, like `:`.

There's another instance of this happening [on the Mozilla blog](https://hacks.mozilla.org/2017/04/fathom-a-framework-for-understanding-web-pages/#comment-21132), fittingly about readability's possible replacement. (?)

**Comment by gijsk** [comment]
This is all because we have to deal with titles like:

"Publisher: some title"

or

"Publication - some title"

or

"Author - some title"

or the reverse (with the publisher/publication/author as a suffix instead of a prefix).

If there's a reasonable way to improve this [code](https://github.com/mozilla/readability/blob/master/Readability.js#L304) so that it works better for the minority of cases where the *actual* title includes a colon, dash or some other similar separator, I would be happy to take pull requests, but I can't think of anything off the top of my head.

**Comment by tigt** [comment]
Yeah, I don't think it's possible. I guess I wonder what's worse: extraneous information in the title, or losing information?

**Comment by Farbdose** [comment]
We could add a flag to let the user decide. Basically two main modes: 

1. If the algorithm is unsure, stay with the longer version so the user has at least all the information he may want
2. Aggressive: use-case would be for users that read many pages mainly from the same site so they don't want to know who wrote this article for example. Second use-case would be for users that use readability.js in third party applications and ... dunno are using the title as preview for the article.

On a second note: I think the current approach of extracting the title first and then deleting possible second titles we find while extracting the main content is not able to handle everything thats out there. 
I would try the other way around:

1. get the main content and extract everything that might be a title
2. collect the opengraph meta-data
3. look for the title in the obvious places
4. take all these together, perform magic, decide what will be the main title and whats actually normal content we extracted be accident
5. put the title on top of the page, and the "actually content" parts back into the main content

**Comment by gijsk** [comment]
This is better now - we're prioritizing metadata and are less aggressive about pruning "Foo" from "Foo: Bar" titles.
