### ISSUE TITLE
How is it supposed to work in nodejs? (Readability is not a constructor)

### ISSUE THREAD

**Issue by malcommac** [mozilla/readability#297]
Hi,
I would to use readability in my node app.
That's my code (I've used parse-url and jsdom to get the URL object and the document of the page).
However when I try to create a new Readability object I get this error:
`"Readability is not a constructor"`
```javascript
		       var parseUrl = require("parse-url");
			var jsdom = require("jsdom");
			var loc = parseUrl(urlString);
			jsdom.env({
				url: url,
				done: function (err, window) {
					var document = window.document;
					try {
						var Readability = require("readability");
						var article = new Readability(loc, document).parse();
						...
					} catch(err) {
						console.log(err);
					}
				}
			});

```

Thanks a lot

**Comment by gijsk** [comment]
Gah, sorry for the delay, this got lost.

Off the top of my head, I think you want:
```js
var readabilityLib = require("readability");
var Readability = readability.Readability;
var article = new Readability(loc, document).parse();
```

See e.g. https://github.com/mozilla/readability/blob/1a12befa41367f0405ad6963746f7c87d523bf13/test/test-readability.js#L6-L8
