### ISSUE TITLE
How do I assess if a link isProbablyReaderable?

### ISSUE THREAD

**Issue by luizv** [mozilla/readability#304]
Hi. I'm trying to learn with this code, adapting it to an iOS application.
How do I assess if isProbablyReaderable flags true? Or, in other words, how do I decide if I should present the real version or the readability version of the webpage?

I can't find anywhere explaining it or another useful question about it.
 
Thx!

**Comment by gijsk** [comment]
I don't understand what the question is. At a guess: you need to parse a DOM (with `jsdom` or the supplied `JSDOMParser`) and run something like:

```
var readability = new Readability(doc, url);
var isReaderable = readability.isProbablyReaderable();
```

There is no way to determine whether a page is readerable solely from a URL (ie without the document).
