### ISSUE TITLE
Articles on Zerohedge should be readerable

### ISSUE THREAD

**Issue by chr15m** [mozilla/readability#305]
As mentioned in this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1300028

The following URL is not readerable:

http://www.zerohedge.com/news/2016-08-31/deutsche-bank-refuses-delivery-physical-gold-upon-demand

**Comment by evanxd** [comment]
I could not reproduce this bug. See the below attachments. The reader mode button is shown, and the result is good.

<img width="1277" alt="issue-305-2" src="https://cloud.githubusercontent.com/assets/3013038/22195214/c7bfa604-e181-11e6-9a0a-bba3f43cd699.png">
<img width="1111" alt="issue-305-1" src="https://cloud.githubusercontent.com/assets/3013038/22195215/c7c58650-e181-11e6-90b6-fe3ed15f6c79.png">

**Comment by chr15m** [comment]
:+1: works for me in latest firefox, thanks.
