### ISSUE TITLE
 www.eternalgod.org - see bug description

### ISSUE THREAD

**Issue by armenzg** [mozilla/readability#318]
URL: http://www.eternalgod.org/lit/booklets/healing_txt.htm
Browser / Version: Firefox Mobile 53.0
Operating System: Android 5.1.1
Problem type: Something else - I'll add details below

Steps to Reproduce

    Navigate to: http://www.eternalgod.org/lit/booklets/healing_txt.htm
    Tap on reader view

Expected Behavior:
See optimized text for reading

Actual Behavior:
I get this message:
Failed to load article from page

From @adamopenweb (https://github.com/webcompat/web-bugs/issues/3703#event-860349656):
Thanks @armenzg. Doesn't work on desktop either. But it does in Safari's reader mode.

I don't think this should be considered a web compatibility issue, but an issue with the Firefox reader mode.

**Comment by gijsk** [comment]
This seems to be working now. \o/
