### ISSUE TITLE
Author and title correct but wrong article text is shown for newstatesman.com where page shows two articles

### ISSUE THREAD

**Issue by timwaters** [mozilla/readability#321]
New Statesman article pages shows two stories - one at the top which the URL refers to and then another one under that. Readability appears to show the correct Author and Title for the target top article but shows the second article body text.

For example
http://www.newstatesman.com/world/2016/11/iron-law-oligarchy
With readability - This will show the Title as "The iron law of oligarchy" and Author as "John Gray", with the first paragraph starting with the words "This summer saw our Labour Party engaged in another lengthy period of introspection...." however this and subsequent paragraphs belong to the other story entitled "The "conditions for Labour's previous successes are falling apart. Where do we go from here?"
By Bridget Phillipson. 
 
Example URLS
http://www.newstatesman.com/world/2016/11/iron-law-oligarchy
http://www.newstatesman.com/world/2016/11/mass-democracy-has-failed-its-time-seek-humane-alternative

Showing top of site with reader view off
![readability-off](https://cloud.githubusercontent.com/assets/48941/20502641/e9dc4df4-b036-11e6-899b-a39e27baf328.png)

Showing with reader view on 
![readability](https://cloud.githubusercontent.com/assets/48941/20502447/fb92df50-b035-11e6-840b-3c6b0502b248.png)

This behaviour is the same when tested with http://readable-proxy.herokuapp.com/

**Comment by gijsk** [comment]
The website seems to have stopped its infinite scrolling type malarkey, and so this works correctly now...
