### ISSUE TITLE
Entertainment Weekly hack no longer needed?

### ISSUE THREAD

**Issue by tigt** [mozilla/readability#322]
[Lines 1223–1226:](https://github.com/mozilla/readability/blob/master/Readability.js#L1223-L1226)

```js
// EW-CMS specific segment replacement. Ugly.
// Example: http://www.ew.com/ew/article/0,,20313460_20369436,00.html
if (segment.indexOf(',00') !== -1)
  segment = segment.replace(',00', '');
```

The example URL now redirects to a more typical URL structure. [Google’s indexed URLs for EW containing `00`](https://www.google.com/search?q=inurl:%2200%22+entertainment+weekly) all seem to be dead, or listings that aren’t articles. It might be safe to remove this code.

**Comment by evanxd** [comment]
Removed and fixed. Thanks for reporting the bug, @tigt.
