### ISSUE TITLE
blogger testcase: test run returns readerable: true, but generate-testcase.js returns readerable: false

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/readability#325]
readerable can be false in the generated metadata because [the generate script checks myReader.isProbablyReaderable()](https://github.com/mozilla/readability/blob/master/test/generate-testcase.js#L114) but that points (at least here) to the iframe for commenting which doesn't contain much text and so [fails the checks for readerbility](https://github.com/mozilla/readability/blob/master/Readability.js#L1785-L1810).

**Comment by gijsk** [comment]
What does "points to the iframe" mean?

**Comment by Archaeopteryx** [comment]
Sorry, I had run Readability.js and logged the textContent of the nodes in the isProbablyReaderable call which contained 'Post a comment' and is next to an iframe and scripts, so I assumed these would inject into the iframe.

Anyway, the reason that it readerable is false is that

>   /**
>    * Decides whether or not the document is reader-able without parsing the whole thing.
>    *
>    * @return boolean Whether or not we suspect parse() will suceeed at returning an article object.
>    */
>   isProbablyReaderable: function(helperIsVisible) {
>     var nodes = this._getAllNodesWithTag(this._doc, ["p", "pre"]);

There are only 3 small <p>s in the 'blogger' document, so this doesn't score enough.

**Comment by gijsk** [comment]
So are you saying this isn't passing on tip? Why isn't it breaking the automated tests?

**Comment by Archaeopteryx** [comment]
Yes, it's not passing on tip if you regenerate the testcase, even on the revision for which the blogger testcase got checked in. It doesn't break tests because the expected-metadata.json contains true as value for readerable and not false like the testcase generation does (manually edited metadata after it got generated?)

In generate-testcase.js, isProbablyReaderable() yields false. test-readability.js calculates readerable: true.

**Comment by gijsk** [comment]
> In generate-testcase.js, isProbablyReaderable() yields false. test-readability.js calculates readerable: true.

What's the difference? They should both effectively be doing the same thing...

**Comment by Archaeopteryx** [comment]
So the DOM structures passed to isProbablyReaderable are different.
1. generate-testcase.js finds only the 3 p nodes in isProbablyReaderable, the linebreaks are without a slash. These linebreaks in divs aren't found and cause readerable: false
2. When the tests get run, isProbablyReaderable gets a doc which has the the paragraphs immediately closed by some fixup and the linebreaks with slash. The divs with linebreaks are found, contain much text, so readerable is true.

**Comment by gijsk** [comment]
What does "line breaks without a slash" mean? In fact, what are line breaks here? Just `\n`, or `<br>` or something else?

**Comment by Archaeopteryx** [comment]
> What does "line breaks without a slash" mean? In fact, what are line breaks here? Just \n, or <br> or something else?

`<br>`, else I'd have mentioned a backslash.

So if I add these three logging statements to Readability.js' isProbablyReadable

```isProbablyReaderable: function(helperIsVisible) {
    console.log(this._doc.body.innerHTML);

    var nodes = this._getAllNodesWithTag(this._doc, ["p", "pre"]);
    console.log("<p> and <pre> nodes length: " + nodes.length);



    // Get <div> nodes which have <br> node(s) and append them into the `nodes` variable.

    // Some articles' DOM structures might look like

    // <div>

    //   Sentences<br>

    //   <br>

    //   Sentences<br>

    // </div>

    var brNodes = this._getAllNodesWithTag(this._doc, ["div > br"]);

    console.log("div > br nodes length: " + brNodes.length);

    if (brNodes.length) {

      var set = new Set();

      [].forEach.call(brNodes, function(node) {

        set.add(node.parentNode);

      });

      nodes = [].concat.apply(Array.from(set), nodes);

    }

```

`node test/generate-testcase.js` prints a log which contains:
````...
                                                                            <div class="post-body entry-content" id="post-body-932306423056216142" itemprop="description articleBody">
                                                                                I've written a couple of posts in the past few months but they were all for <a href="http://blog.ioactive.com/search/label/Andrew%20Zonenberg">the blog at work</a> so I figured I'm long overdue for one on Silicon Exposed.<br/>
                                                                                <br/>
...
                                                                            <p class="comment-footer">
                                                                                <div class="comment-form">
...
<p> and <pre> nodes length: 3
div > br nodes length: 0```

On the other hand, this is in the output of `mocha test/test-*.js`:
```...
                                                                            <div class="post-body entry-content" id="post-body-932306423056216142" itemprop="description articleBody">
                                                                                I've written a couple of posts in the past few months but they were all for <a href="http://blog.ioactive.com/search/label/Andrew%20Zonenberg">the blog at work</a> so I figured I'm long overdue for one on Silicon Exposed.<br>
                                                                                <br>
...
                                                                            <p class="comment-footer">
                                                                                </p><div class="comment-form">
...
<p> and <pre> nodes length: 4
div > br nodes length: 75```
