### ISSUE TITLE
Update videos regex to allow for optional https

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#33]
Randomly noticed while trolling code: [./Readability.js:100](https://github.com/mozilla/readability/blob/a907fce85ea4d770dea1508a22d980192d397abd/Readability.js#L100)

It'd be nice if the regex supported http:// and https:// (both of which are supported by youtubes and vimeo).

**Comment by gijsk** [comment]
See #34.

**Comment by gijsk** [comment]
Fixed!
