### ISSUE TITLE
New York Times article is missing the first few paragraphs. 

### ISSUE THREAD

**Issue by fiveNinePlusR** [mozilla/readability#333]
http://www.nytimes.com/2016/12/18/books/review-debriefing-the-president-tears-into-the-cia.html

**Comment by evanxd** [comment]
This looks like a same issue we already addressed on a [Bugzilla issue]
[bugzilla]. We will fix there. Thanks for reporting the issue. :)

[bugzilla]: https://bugzilla.mozilla.org/show_bug.cgi?id=1300697

**Comment by evanxd** [comment]
@gijsk , Could add a new label, like `top-website-issue` to address this issue and web website ones? Thanks. :)
