### ISSUE TITLE
Breitbart.com

### ISSUE THREAD

**Issue by lauren-elise-thomas** [mozilla/readability#334]
Reader mode is available on breitbart.com but fails to load articles

**Comment by evanxd** [comment]
We can reproduce on the the page http://www.breitbart.com/video/2017/01/10/franken-im-troubled-by-sessions-exaggerating-misrepresenting-his-civil-rights-history/ .

**Comment by lauren-elise-thomas** [comment]
Reader mode detects and loads that article for me, bet fails on this article and others. http://www.breitbart.com/tech/2016/03/29/an-establishment-conservatives-guide-to-the-alt-right/

**Comment by AmarOk1412** [comment]
This is the stack trace I've got for the first URL (http://www.breitbart.com/video/2017/01/10/franken-im-troubled-by-sessions-exaggerating-misrepresenting-his-civil-rights-history/):
```
JSDOMParser error: expected '</head>' and got </scrip
JSDOMParser error: expected '</html>' and got </scrip
[Child 18531] WARNING: Not same origin error!: file /home/worker/workspace/build/src/dom/base/nsJSEnvironment.cpp, line 460
JavaScript error: http://us-ads.openx.net/w/1.0/jstag, line 9: Error: Permission denied to access property "realvu"
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: this._doc.documentElement is undefined
Full stack: parse@resource://gre/modules/reader/Readability.js:1855:9
parseDocument@resource://gre/modules/reader/ReaderWorker.js:48:12
worker.dispatch@resource://gre/modules/reader/ReaderWorker.js:21:24
handleMessage@resource://gre/modules/workers/PromiseWorker.js:122:16
@resource://gre/modules/reader/ReaderWorker.js:35:41
EventListener.handleEvent*@resource://gre/modules/reader/ReaderWorker.js:35:1

*************************
```

**Comment by AmarOk1412** [comment]
Btw, for http://www.breitbart.com/radio/2017/01/10/breitbart-news-daily-long-goodbye/, the article is too short and the score is not > 20. The first paragraph is a h2 tag.

**Comment by evanxd** [comment]
Found the root cause, which seems to be the JSDOMParser issue, and added tests[1] for it.

When I run the test for the page[2], it caused the below error and it could be passed with `jsdom` parser.
```
JSDOMParser error: expected '</head>' and got </scrip

JSDOMParser error: expected '</html>' and got </scrip

Parsing this DOM caused errors: expected '</head>' and got </scrip
expected '</html>' and got </scrip

        1) "before all" hook


  6 passing (2s)
  1 failing

  1) Test pages breitbart JSDOMParser "before all" hook:
     TypeError: Cannot read property 'documentElement' of null
      at Readability.parse (Readability.js:1878:25)
      at Context.<anonymous> (test/test-readability.js:65:27)
```

Looks like something wrong in JSDOMParser module.

[1]: https://github.com/evanxd/readability/commit/26c9d349292e03cc582e9de3a4a099416a8189a6
[2]: http://www.breitbart.com/tech/2016/12/22/neutral-snopes-fact-checker-david-emery-un-angry-trump-supporters/

**Comment by evanxd** [comment]
Other "Failed to load article from page" issues, like #308  might be caused by same reason.

**Comment by gijsk** [comment]
@evanxd was there a fix (on a PR?) for the JSDOMParser issue? I can't find one from the test you wrote. Or a diagnosis of what exactly is broken?

Note that in Firefox (both Android + Desktop) we serialize as XHTML before passing to JSDOMParser. We should probably check what's going on with that output that is making JSDOMParser choke.

**Comment by evanxd** [comment]
I haven't sent the PR yet until now. I added the tests in PR #345 but not including solution yet. I'll continue to work on this. You can check the failure report on the [page][page].

```
Note that in Firefox (both Android + Desktop) we serialize as XHTML before passing to JSDOMParser. We should probably check what's going on with that output that is making JSDOMParser choke.
```
Thanks for suggestions. I'll check this.

[page]: https://travis-ci.org/mozilla/readability/builds/194420173
