### ISSUE TITLE
How can I use this in iOS with Objective-C?

### ISSUE THREAD

**Issue by vomako** [mozilla/readability#335]
I tried to evaluate the JavaScript using the code below, but I don't get anything back in "data". What am I doing wrong?

     [webView_ evaluateJavaScript:@"var loc = document.location;" completionHandler:^(NSString *html, NSError *error)
         {
             if (error != nil)
             {
                 NSLog(@"ERROR1: %@", error.localizedDescription);
                 [self safariReaderViewNotAvailable];
             }
             
             [webView_ evaluateJavaScript:@"var uri = {spec: loc.href, host: loc.host, prePath: loc.protocol + \"//\" + loc.host, scheme: loc.protocol.substr(0, loc.protocol.indexOf(\":\")), pathBase: loc.protocol + \"//\" + loc.host + loc.pathname.substr(0, loc.pathname.lastIndexOf(\"/\") + 1)};" completionHandler:^(NSString *html, NSError *error)
              {
                  if (error != nil)
                  {
                      NSLog(@"ERROR1: %@", error.localizedDescription);
                      [self safariReaderViewNotAvailable];
                  }
                  
                  
                  
                  [webView_ evaluateJavaScript:@"var article = new Readability(uri, document).parse();" completionHandler:^(NSData *data, NSError *error)
                   {
                       if (error != nil)
                       {
                           NSLog(@"ERROR2: %@", error.localizedDescription);
                           [self safariReaderViewNotAvailable];
                       }
                       
                        // process data...
                       
                   }];
                  
              }];
         }];

**Comment by gijsk** [comment]
I don't know (given that I don't know iOS and whatever dialect of obj-c this is), and this is a bugtracker, not a place to get help, sorry. Consider asking somewhere like stackoverflow instead.
