### ISSUE TITLE
Feature request: highlighting

### ISSUE THREAD

**Issue by marcelopm** [mozilla/readability#341]
It would be great to be able to highlight parts of text once using the Reader View mode.

Ideally, the highlighting would be save into local storage and maybe have the possibility of being include as part of FF's inbuilt sync.

Would also be great to be able to see a list of highlighted texts per page and globally.  

Cheers

**Comment by gijsk** [comment]
Thank you for your report. Because this would need to be implemented in Firefox rather than in readability's core, I've reported it in the relevant bugzilla component and am closing this issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1331941

**Comment by marcelopm** [comment]
:+1: 
Sorry for posting it here, thanks

**Comment by gijsk** [comment]
No problem, it's super confusing that the bugtracking systems are separate, even though there are reasons.
