### ISSUE TITLE
Help me to understand where `iframe` is removed

### ISSUE THREAD

**Issue by bazi** [mozilla/readability#360]
Based on definition of [_clean](https://github.com/mozilla/readability/blob/master/Readability.js#L1704-L1725) function (commit 3e07e06b1cbb076fe565750273f095b13394d699, head of master as of now), `iframe` tags containing YouTube links are not cleaned up. That's a really useful and necessary check for us but we are not getting `iframe` tags with YouTube links in our reader view HTMLs.

For example, following HTML fragment is taken from [this](http://www.makeuseof.com/tag/unity-explained-ubuntu-default-desktop-environment/) link and it is being stripped out.

    <p><iframe width="500" height="281" src="https://www.youtube.com/embed/OVHE6C3XQy0?feature=oembed" frameborder="0" allowfullscreen></iframe></p>

Tried to comment out [these lines](https://github.com/mozilla/readability/blob/master/Readability.js#L534-L543) but the result is the same.

Would appreciate if anyone could point me to the source where such fragments are removed.

**Comment by gijsk** [comment]
The easiest way to determine where this happens is to turn on debug mode locally - toggle https://github.com/mozilla/readability/blob/master/Readability.js#L40 , and check the debug output.
