### ISSUE TITLE
No readability results on www.psmag.com

### ISSUE THREAD

**Issue by st3fan** [mozilla/readability#38]
Exact url is http://www.psmag.com/health-and-behavior/why-is-there-no-generic-insulin

I am processing the mobile version as served to Mobile Safari

**Comment by gijsk** [comment]
So on desktop I don't even see an icon. Don't know why. Apparently even on iOS if you force it to show in reader mode it doesn't work?

**Comment by gijsk** [comment]
FWIW, if you force this on via the browser console in desktop, it does work.

**Comment by n1k0** [comment]
Look at this article page source… how are we supposed to parse contents generated by js?

**Comment by gijsk** [comment]
This wfm on current desktop Firefox.
