### ISSUE TITLE
Deficient article content

### ISSUE THREAD

**Issue by seraphim2** [mozilla/readability#384]
Only some paragraph is visible after I generate reader view for this article:  http://www.jbc.org/content/290/8/4573.full
Suspect is the too deep nested divs.
However everithing is ok, when I use the firefox built-in feature.

**Comment by gijsk** [comment]
If this works in the browser, this report is going to need more details to be actionable. What is missing? Have you tried passing in the debug flag to see if you can get useful output that indicates why we might be removing it?

**Comment by seraphim2** [comment]
I've found a problem: I used npm to install and it resolves a very old (v0.1.0) version. Everything is working fine if I checkout the latest commit from github.
Thx.

**Comment by gijsk** [comment]
OK, closing given that, then. I don't know how the npm story even works given #43 .
