### ISSUE TITLE
Node is not defined

### ISSUE THREAD

**Issue by Praveena0989** [mozilla/readability#387]
I am running Readability in my `Node.js` server using `JSDOM` but I am getting this error as soon as I construct `Readability` object. -- `Node is not defined `

As of now I am solving this issue by modifying `readability` code

`      function Readability(uri, doc, Node,options) {`
        `   options = options || {};`
          `this.Node=Node;`
           
And I am passing `Node` like this 
 `new Readability( uri, document, dom.window.Node ).parse( );`

Is there any right way to do it?

**Comment by gijsk** [comment]
Use the `index.js` file (ie just `var Readability = require("readability").Readability;` should work, AIUI) to ensure Readability.js loads in a scope that has a Node instance to work with.

**Comment by Praveena0989** [comment]
@gijsk  I had to make one more change in package.json
`"main": "Readability.js"`
This will give same error So I changed it

**Comment by lazharichir** [comment]
How have you guys fixed it, got the very same error...

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const Readability = require('readability');

process.on('unhandledRejection', r => console.log(r));
//const url = 'https://engineering.linkedin.com/blog/2017/11/improving-resiliency-and-stability-of-a-large-scale-api';

const url = "https://engineering.quora.com/Machine-Learning-Workshop-Combatting-Abuse-Online";

JSDOM.fromURL(url).then(function( dom ) {

	var mydocument = dom.window.document;

	// console.log(mydocument.querySelector("p").textContent);

	var article = new Readability (url,dom.window.Node, { debug: true } ).parse();

	console.log(article.title);
});
```
