### ISSUE TITLE
No readability results on www.visir.is

### ISSUE THREAD

**Issue by st3fan** [mozilla/readability#39]
Exact url is http://www.visir.is/the-pirate-party-is-now-measured-as-the-biggest-party-in-iceland/article/2015150318848

**Comment by n1k0** [comment]
In this case it seems JSDOMParser is at fault, because the document it creates has no body at all, while it obviously exists in the original page HTML.

**Comment by st3fan** [comment]
Just a quick note that on iOS I use the native `DOMParser`. Maybe that means that the document in general is malformed?

**Comment by gijsk** [comment]
This isn't currently marked as Readerable, and I don't know why.

**Comment by n1k0** [comment]
This is now fixed (page is properly detected as readerable, and extracted contents look just fine.)
