### ISSUE TITLE
Suggestion: Configurable Word Threshold?

### ISSUE THREAD

**Issue by iq-dot** [mozilla/readability#390]
I noticed that the library has a fixed minimum 500 characters word count threshold, is it possible to have this configurable so that the default is 500 but can be overridden when passed in?

I can make a PR if required.

**Comment by gijsk** [comment]
This seems like a fine idea, a PR would be appreciated, thank you!

**Comment by iq-dot** [comment]
Sorry for the delay, I forgot about this.

PR added: https://github.com/mozilla/readability/pull/399

**Comment by gijsk** [comment]
Closed via #390. Thanks again!
