### ISSUE TITLE
WordPress emoji are enormous on Android

### ISSUE THREAD

**Issue by tigt** [mozilla/readability#398]
URL (but it may not be relevant): https://blog.shiftyjelly.com/2011/08/02/amazon-app-store-rotten-to-the-core/

When reading on my phone, it seems either WordPress (or Firefox itself?) is shimming emoji with Twitter's twemoji library. Unfortunately, something's up with the scaling:

![The emoji is rendered at 100% the width of the page, taking up most of the screen.](https://user-images.githubusercontent.com/8072522/30325876-7836e0ba-9794-11e7-9d0f-bdb7d116384d.png)

The URL of the emoji itself is https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/1f609.svg

Is this an issue with Readability, or should I file a bug with FF?

**Comment by gijsk** [comment]
I can reproduce this, but yeah, the output from readability is fine... it's not an image, it's just an emoji char, so how that gets rendered is up to gecko. I dunno why it's doing anything fancy here at all... Please [file an issue against Firefox for Android](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android). Thank you!

**Comment by tigt** [comment]
Gotcha. [Bug #1399616](https://bugzilla.mozilla.org/show_bug.cgi?id=1399616) filed.
