### ISSUE TITLE
Title is wrong

### ISSUE THREAD

**Issue by Praveena0989** [mozilla/readability#400]
I am trying run readability on this [link](https://www.ndtv.com/india-news/surgical-strikes-a-message-to-pakistan-more-if-necessary-army-chief-general-bipin-rawat-1755007)  It works perfectly but the problem is with the title. I am running `readability` using `JSDOM` and `document.title` gives me title `Surgical Strikes A Message To Pakistan, More If Necessary: Army Chief General Bipin Rawat` but `Readability` giving me `Army Chief General Bipin Rawat` even in firefox browser reader view

**Comment by gijsk** [comment]
This is now (via #409) fixed both in Readability the library and in Firefox Nightly (59).
