### ISSUE TITLE
On the web

### ISSUE THREAD

**Issue by Announcement** [mozilla/readability#402]
Maybe I'm misunderstanding something, but why is the usage of things like JSDom Parser even necessary? I'm pulling a document from `XMLHttpRequest` where `requestType` is set to `document` and the output is already a parsed **DOM**, I don't see why we would need to reparse that with something like JSDom or whatever, why not just use the browser implementation or whatever?

**Comment by gijsk** [comment]
It's not necessary in that case, no. It's not clear what gave you the impression it *is* necessary, though, so there's not much I can do with this issue besides closing it... The `README` already states:

```
If you're using Readability on the web, you will likely be able to use a document reference from elsewhere (e.g. fetched via XMLHttpRequest, in a same-origin <iframe> you have access to, etc.). 
```

which seems pretty clear to me.
