### ISSUE TITLE
"node.className.split is not a function"

### ISSUE THREAD

**Issue by bittlingmayer** [mozilla/readability#412]
Some URLs (eg https://www.cnet.com/es/noticias/twitter-lite-america-latina/#ftag=ESPdf5230a) yield the following error:

```
TypeError: node.className.split is not a function
    at Object._cleanClasses (/user_code/node_modules/readability/Readability.js:246:8)
    at Object._cleanClasses (/user_code/node_modules/readability/Readability.js:259:12)
    at Object._cleanClasses (/user_code/node_modules/readability/Readability.js:259:12)
    at Object._cleanClasses (/user_code/node_modules/readability/Readability.js:259:12)
    at Object._postProcessContent (/user_code/node_modules/readability/Readability.js:141:10)
    at Object.parse (/user_code/node_modules/readability/Readability.js:1723:10)
    ...
```

I believe a potential fix would be to check if `node.className` is actually a string.

**Comment by gijsk** [comment]
What kind of node is that (ie node type), what DOM implementation generated it (ie is this from within Firefox, or in an application where you're using readability, and if so with what DOM library - JSDOMParser in this repo, or `jsdom`, or something else?), and what is `node.className` ?

AFAICT the only nodes that are supposed to be passed to this method will be article content nodes, which will be elements, and their element descendants. Similarly, at least in Firefox's DOM, `node.className` seems to always be a string for elements - at worst it'll be an empty string, which should still have a `split` method.

**Comment by bittlingmayer** [comment]
Here is a gist to test locally:

https://gist.github.com/bittlingmayer/15dfeb44e8b5108d1a3f5107d4adc50d

**Comment by bittlingmayer** [comment]
I added the following at the top of `_cleanClasses` in Readability.js so:
```
    if (node.className == null || node.className == undefined) {
      console.log("!node.className:", node.tagName);
      console.log(node);
    } else if (!node.className.split) {
      console.log("!node.className.split", node.tagName);
      console.log(node);
    }
```

The relevant bit of the output was:
```
!node.className.split svg
SVGSVGElement {
  [Symbol(SameObject caches)]: 
   { attributes: NamedNodeMap { '0': Attr {} },
     childNodes: 
      NodeList {
        '0': [Object],
        '1': [Object],
        '2': [Object],
        '3': [Object],
        '4': [Object],
        '5': [Object],
        '6': [Object],
        '7': [Object] },
     className: SVGAnimatedString {} } }
```

**Comment by gijsk** [comment]
Thanks, the gist is super helpful.

Running with:

```
node --debug-brk test.js
```

and attaching the chrome devtools, then enabling 'break on exception' and running the script tells us that the `node` with which this happens is: `<svg class="svg-symbol playerControls"><symbol id="play" viewBox="0 0 26.6 32">`, and looking at https://developer.mozilla.org/en-US/docs/Web/API/Element/className#Notes yields:

> `className` can also be an instance of `SVGAnimatedString` if the element is an `SVGElement`. It is better to get/set the `className` of an element using `Element.getAttribute` and `Element.setAttribute` if you are dealing with SVG elements

Well. Today I learned.

**Comment by gijsk** [comment]
and you just wrote the same - why is it that github sometimes does and sometimes doesn't update comments while looking at an issue? Oh well. I'll do a PR to fix, anyway. :)

**Comment by bittlingmayer** [comment]
Great, thank you very much!

> `className` can also be an instance of `SVGAnimatedString` if ...

!!!

**Comment by gijsk** [comment]
Hi @bittlingmayer , if you have a moment, could you comment on the PR ( #413 ) to say if the fix there works for you? Thanks!
