### ISSUE TITLE
Reader View makes it impossible to use sign-up form

### ISSUE THREAD

**Issue by Sprachprofi** [mozilla/readability#418]
For some reason Twitter is deciding that https://diem25.org/join should automatically be displayed in the Reader View, which means that the sign-up form is simply not rendered even though that's the reason people are on that page. Is there a tag I can use to force rendering of forms / force disable Reader View?

**Comment by gijsk** [comment]
I'm going to close this issue because it's not clear to me there's an issue with the readability library itself. Happy to keep discussing this here if that's helpful, just trying to make sure the open issues are actionable. :-)
