### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by DavidBruant** [mozilla/readability#43]
So that other projects can install it via 
`npm install pick-your-name`

**Comment by gijsk** [comment]
Considering the script itself isn't at all usable through node, I'm not convinced this is a good idea, at least right now...

**Comment by DavidBruant** [comment]
> Considering the script itself isn't at all usable through node

You've got [Travis running the tests for Node 0.10](https://github.com/mozilla/readability/blob/master/.travis.yml), so in one way or another, the code is usable in Node (unless I missed some part where Firefox is started from Node to run the tests).

Also, looking at https://github.com/mozilla/readability/blob/d0df9d8479f40189fb39037c78574cc5c420f075/test/index.js#L11-L29 it looks like it would be fairly easy to wrap the existing code to make it work in Node (just isolate these lines in their own file, make this new file the `main` endpoint in `package.json` and publish that).
... wait... I'll just do it and send a PR...

**Comment by gijsk** [comment]
Yeah, I mean that the vm stuff isn't particularly "nice"... you can't require("readability.js") or whatever.

**Comment by DavidBruant** [comment]
I need this sort of things in a project I'm working on. Something that works would be better than nothing at all. The thing we use now is the [Readability Parser API](https://www.readability.com/developers/api/parser). As you can imagine, the vm stuff will certainly be a major improvement over this HTTP API in terms of perfs.

**Comment by pdehaan** [comment]
If we put it on **npm** (YAY!!) can we please put it on **bower** too?

**Comment by asbjornenge** [comment]
What is the status on this? Quite a lot of us are now using `npm` for client side package management.

**Comment by gijsk** [comment]
I no longer think this is a bad idea, but equally I don't have time to push this forward significantly. @pdehaan, what would need to happen to get this listed on npm/bower as a mozilla thing?

**Comment by pdehaan** [comment]
@gijsk Make sure you're logged into npm in your Terminal. Type `npm publish` in your local repo folder. That should do it for npm. Not sure about bower, I haven't published there in a while -- but I can take a look.

**Comment by pdehaan** [comment]
Actually, the [**readability**](https://www.npmjs.com/package/readability) name is already used by arc90's module on npm, so we'd have to rename our module to avoid a naming conflict.
We could use something like **moz-readability**, or whatever.

**Comment by gijsk** [comment]
Is there no way to associate the published module with Mozilla-the-org rather than with my personal NPM username ?

**Comment by pdehaan** [comment]
I've never used npm orgs. But I'd probably just associate with your personal npm username and then add additional collaborators as appropriate (see https://www.npmjs.com/package/jpm or https://www.npmjs.com/package/convict or other Mozilla-based npm modules). That would give you better control of exactly who can publish new versions to npm.

**Comment by asbjornenge** [comment]
You can publish public scoped module using an organization on npm. I'm not 100% sure organization can be set up without a subscription, but I think so. https://docs.npmjs.com/orgs/what-are-orgs

**Comment by asbjornenge** [comment]
Yeah yeah, you just log in and hit "Create an organization" - https://www.npmjs.com/org/create

**Comment by weblancaster** [comment]
@gijsk I would check (looks like Mozilla has an private account for they packages) if there is a Mozilla account/organization you can use and push under that account otherwise check with your colleagues in SF how they are publishing.

**Comment by weblancaster** [comment]
And for those that want to use now.. you can install from github using npm here some examples `npm install githubname/reponame` or `npm install git+https://isaacs@github.com/npm/npm.git`

**Comment by sveinburne** [comment]
+1, would love to use this in my project as a classic npm dependency. 
The trick I have found now is to use `"readability":"file:./local_modules/readability"` in my package.json `dependency` field.

**Comment by pdehaan** [comment]
@sveinburne Couldn't you also do `$ npm i mozilla/readability -S` to install it directly from GitHub and save to your package.json / node_modules?

**Comment by sveinburne** [comment]
@pdehaan I have discovered thanks to this thread that I could! But I want to stick to a specific commit to have a consistent dependency, do you know if I can achieve this with a git+https uri ?

**Comment by pdehaan** [comment]
I think you can just pin the SHA at the end of a Git URL. We do that [here](https://github.com/mozilla/fxa-js-client/blob/f98d579f9ec834639fa2815adbbb6d8c7dcf0d95/package.json#L41) in **mozilla/fxa-js-client**:

```js
"grunt-build-control": "git://github.com/robwierzbowski/grunt-build-control#274952",
...
```

**Comment by sveinburne** [comment]
@pdehaan thanks, that will make it cleaner !

**Comment by danburzo** [comment]
To my mind, Readability is ready to be published on `npm` under `@mozilla/readability`. I'd like to help iron out any other blocking issues.

**Comment by e-e-e** [comment]
I would also like to raise my hand to help with this, is there any thing I can do to help this happen?

**Comment by gijsk** [comment]
> I would also like to raise my hand to help with this, is there any thing I can do to help this happen?

I think we need to make it so that `require("readability")` only gets you readability and not JSDOMParser (which will mean https://github.com/mozilla/readability/blob/master/index.js needs changing, and potentially other things that depend on it being included today). The hackery in there with `vm.runInNewContext` needs to go away - if we need to plug in dump/console.log, it should be possible to do that only in the test code given that https://github.com/mozilla/readability/blob/master/Readability.js#L59 already deals with it in Readability.js .

The other question is how to integrate https://github.com/mozilla/readability/blob/master/Readability-readerable.js in such an arrangement.

**Comment by mariotacke** [comment]
Just came across this project. Are you still planning to release a version on npm? I'm trying to use it with node (and JSDOM if necessary).

**Comment by gijsk** [comment]
We would like to, but so far we lack someone who has the time as well as knowledge of NPM as well as the ability to fix up the last few issues with the codebase. That last part is a bit annoying, but I believe will impact how the module is `used/usable,` and it seems counterproductive to put it up and fix it afterwards as it'll be a breaking change (and, imo, usage isn't particularly intuitive/natural the way things are right now).

**Comment by boramalper** [comment]
For those looking for a solution:

**package.json**
```json
{
  ...
  "dependencies": {
    "readability": "github:mozilla/readability",
    "request-promise-native": "latest"
  }
}
```

in the source:
```javascript
const Readability = require("readability");
const requestPromise = require("request-promise-native");


async function main() {
    const doc = new JSDOM(body, {
        url: url,
    });
    const reader = new Readability(doc.window.document);
    const article = reader.parse();

    ...
}
```

**Comment by TehShrike** [comment]
> The other question is how to integrate master/Readability-readerable.js in such an arrangement.

@gijsk if you don't want readerable to be implicitly loaded when someone runs `require('@mozilla/readability)` in node, my preference would be to rename the file to `readerable.js` and document that consumers run `require('@mozilla/readability/readerable')` if they want `isProbablyReaderable`.

**Comment by gijsk** [comment]
With many, *many*, thanks to @danburzo who really did like 99% of the work that remained in #608...

It's aliiiiiiive!

https://www.npmjs.com/package/@mozilla/readability

Gonna close this out and have a drink of choice now.

PS: I probably screwed something up with the actual publishing, like there's this ominous "keywords: none" and maybe I excluded files I shouldn't have or included ones that should have been left out. I spent a good amount of time trying to search the web for details of what the "right" thing was and didn't find a whole lot of hard and fast rules. Please do file issues you see with the package, and I'll try and look at them as soon as I can.

**Comment by danburzo** [comment]
Cheers, @gijsk! It has taken me [less than 2 years](https://github.com/mozilla/readability/issues/43#issuecomment-431814613) to make good on my offer :-P

I've also taken the opportunity to switch Readability to the npm version in [`percollate@0.8.0`](https://github.com/danburzo/percollate/releases/tag/v0.8.0), and everything works as expected!

Going forward, I think it'll be useful to keep a Changelog — either as a CHANGELOG.md, or on the Releases tab on GitHub, or both — so that people know what to expect when upgrading from one version to another.
