### ISSUE TITLE
eBay search result pages show up as reader-mode friendly

### ISSUE THREAD

**Issue by msujaws** [mozilla/readability#433]
See for example this URL:
https://www.ebay.com/sch/i.html?isRefine=true&_nkw&_sacat=0&_udlo&_udhi&_ftrt=901&_ftrv=1&_samilow&_samihi&_sadis=15&_stpos=11205-4376&_fss=1&_fsradio=%26LH_SpecificSeller%3D1&_saslop=1&_sasl=cocolucerne&_dmd=1&_ipg=200&_mwBanner=1&LH_Complete=1&LH_Sold=1&rt=nc&_sop=13

Clicking on the Reader Mode button there doesn't provide a useful page.

**Comment by gijsk** [comment]
Thanks!
