### ISSUE TITLE
"Cannot read property tagName of null" for this blog

### ISSUE THREAD

**Issue by lazharichir** [mozilla/readability#435]
I am running Node 8.x and JSDOM. All of this website's blog articles result in the below error:

```
info: User function triggered, starting execution

error: TypeError: Cannot read property 'tagName' of null
    at Readability._grabArticle (/Users/Lazhar/project/services/leadgen-from-url/node_modules/readability/Readability.js:951:37)
    at Readability.parse (/Users/Lazhar/project/services/leadgen-from-url/node_modules/readability/Readability.js:1727:31)
    at axios.get.then.then.pageSource (/Users/Lazhar/project/services/leadgen-from-url/index.js:103:72)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

info: Execution took 900 ms, user function completed successfully
```
Some links to try out:

- https://www.aclu.org/blog/executive-branch/crime-fraud-exception-michael-cohen-case
- https://www.aclu.org/blog/privacy-technology/internet-privacy/facebook-tracking-me-even-though-im-not-facebook

Nothing special to retrieve the source and DOM:
```
// Download the source
axios.get(cargo.location.href)
    .then(response => response.data)

    // Readability
    .then(pageSource => {

        var dom = new JSDOM(pageSource, { url: cargo.location.href })
        Node = dom.window.Node

        articleUri = {
            spec: cargo.location.href,
            host: cargo.location.host,
            prePath: cargo.location.protocol + "//" + cargo.location.host,
            scheme: cargo.location.protocol.substr(0, cargo.location.protocol.indexOf(":")),
            pathBase: cargo.location.protocol + "//" + cargo.location.host + cargo.location.pathname.substr(0, cargo.location.pathname.lastIndexOf("/") + 1)
        };

        article = new Readability(articleUri, dom.window.document).parse()

        return article
    })
```
Any other website's blog articles worked well so far.

It seems that if I remove the first `<p>` element, right after the `<body>`, that has has two `<a>` elements as children, it stops throwing the error.

**Comment by gijsk** [comment]
(Sorry for the slow response.)

Just to be clear, are you using `jsdom` as in https://github.com/tmpvar/jsdom/ ?

I'm not really sure what's going on here. It breaks in Firefox (60 beta) as well, though there it says `parentOfTopCandidate is null` . I need to debug this some more to figure out exactly what is wrong, and if that's the same issue you're seeing, and I haven't had time to do this yet... hopefully I will manage sometime this week.

**Comment by lazharichir** [comment]
No worries for delay :) And yes, that exact `jsdom` package. I am on Node.js 9.4 (tried on Node.js 8 LTS too). Weird, weird!

**Comment by davidar** [comment]
It looks like `topCandidate` is being set to the entire `<html>` node here, which doesn't have a parent hence the `null`.

**Comment by gijsk** [comment]
> It looks like `topCandidate` is being set to the entire `<html>` node here, which doesn't have a parent hence the `null`.

Huh. I mean, a bunch of nullchecks will fix the error, but how do we end up in that situation? We shouldn't be including the `<head>` so shouldn't really go past `<body>` for anything...
