### ISSUE TITLE
Mobile Wikipedia site is broken

### ISSUE THREAD

**Issue by justindarc** [mozilla/readability#436]
It seems as though all `m.wikipedia.org` mobile pages are unable to be parsed by readability.js. For example: https://en.m.wikipedia.org/wiki/Mozilla

<img width="259" alt="screen shot 2018-04-18 at 12 17 03 pm" src="https://user-images.githubusercontent.com/207595/38944792-bb124586-4302-11e8-9eaa-3e6f398fe950.png">

**Comment by gijsk** [comment]
Can't reproduce with a quick check using desktop 60 beta. Also can't reproduce on Android (also 60 beta). Are you seeing this on iOS? Any chance you can gather more diagnostics? I don't have an iOS device myself...

**Comment by justindarc** [comment]
Yeah, this is in Firefox for iOS. I see no errors or anything in the web console. Maybe it’s only with certain pages? It definitely happens every time with the mobile version of the Mozilla entry: https://en.m.wikipedia.org/wiki/Mozilla

**Comment by justindarc** [comment]
Do you have a Mac by any chance? If so, you can reproduce in the iOS Simulator.

**Comment by csuciu** [comment]
This issue is specific to iOS 11. On iOS 10.3, the reader mode works fine on wikipedia.

**Comment by gijsk** [comment]
> Do you have a Mac by any chance? If so, you can reproduce in the iOS Simulator.

I have a mac, but I don't know how to install Firefox for iOS in the Simulator. I don't have disk space, time or brain cycles to build it from scratch, there's no store in the simulator, and it's not obvious how to download an iOS app from the store on my mac, and then install it into the simulator (or something). Even if I did know how to do all that, I don't know how to debug what's going on inside the iOS app.

What version of readability is the iOS app using? Is it the same as what's on android/desktop? Does a previous version work? If you change the UA string, does that help? If you put the same markup we get from android/desktop devices on your own webpage and try to use it with that, does that work?

> This issue is specific to iOS 11. On iOS 10.3, the reader mode works fine on wikipedia.

This makes it sound like either a UA sniffing issue in (mobile) wikipedia where they return different content that somehow then doesn't work, or an issue with the iOS app...

**Comment by gijsk** [comment]
Perhaps you can toggle the debug switch and get the debug output from readability, with a copy of the markup that's causing it to create wrong output, and that combination might help figure out what's going on here? Without being able to reproduce, it's very difficult for me to determine where the issue is...

**Comment by justindarc** [comment]
Debug output 2/3:

<img width="556" alt="screen shot 2018-04-19 at 12 00 32 pm" src="https://user-images.githubusercontent.com/207595/39003744-8249f006-43c9-11e8-9044-b4a13ca1c300.png">

**Comment by justindarc** [comment]
Debug output 3/3:

<img width="556" alt="screen shot 2018-04-19 at 12 01 23 pm" src="https://user-images.githubusercontent.com/207595/39003758-8acd6064-43c9-11e8-88d5-5d33edc5e2e1.png">

**Comment by justindarc** [comment]
@gijsk is that sufficient to see what's going on? Let me know if there's anything else I can do on my end. Thanks!

**Comment by justindarc** [comment]
I think I've solved the problem. We were on commit 8525c6af36d3badbe27c4672a6f2dd99ddb4097f. Updating to latest master seems to have fixed the result, although some things seem off like the "Edit" links next to the section headlines.
<img width="259" alt="screen shot 2018-04-19 at 12 16 31 pm" src="https://user-images.githubusercontent.com/207595/39004540-96f5f606-43cb-11e8-811f-1f68952328a3.png">
