### ISSUE TITLE
Reader View mode removes top images from Guardian articles

### ISSUE THREAD

**Issue by laurent22** [mozilla/readability#450]
For example on:

https://www.theguardian.com/world/2018/may/16/vatican-advises-nuns-not-to-overindulge-in-social-media

I would expect the top image of the nun to be included, but it's not.

**Comment by marcorichetta** [comment]
I can view it.
It's not rendered like on the article but it seems good. [Link](https://i.imgur.com/QZ0LIgQ.png)

**Comment by gijsk** [comment]
Thanks for the comment - yes, this seems to work now... will go ahead and close this for now.
