### ISSUE TITLE
Reader mode shows "Failed to load article from page" for Economist

### ISSUE THREAD

**Issue by tricalnikhil** [mozilla/readability#463]
Example: This page https://www.economist.com/open-future/2018/06/18/why-collaborative-thinking-beats-individual-smarts shows the error: "Failed to load article from page"

On Firefox 60.0.2 (64-bit)

**Comment by gijsk** [comment]
Yep, this was tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1394941 . It was an issue specific to Firefox for desktop/android, and it's fixed in Firefox 62, which is going into beta in the next few weeks - or you can try out nightly at https://nightly.mozilla.org/ .

**Comment by tricalnikhil** [comment]
Verified Fixed in Version 62.0
