### ISSUE TITLE
H1 tags within the article's body are removed

### ISSUE THREAD

**Issue by lazharichir** [mozilla/readability#464]
The target page I am trying to use Readability on is: https://topicseed.com/content-depth-for-seo/

The article's body is correctly identified, yet, all of these H1 tags are not appearing in the parsed content:
- Assess How Deep Is Your Content
- Rewrite With Content Depth In Mind
- Yes, Content Depth and Breadth Overlap
- Depth of Content = Quality + Frequency

The paragraphs before and after these are correctly present in the parsed content. No idea what could be causing this as it is nothing extraordinary?

Config:
- nodejs 9 + jsdom
- package.json imports `"readability": "github:mozilla/readability"`

**Comment by lazharichir** [comment]
Alright, some trials later... It seems like:
- changing H1 tags to H2 in the source makes it work
- reverting back to the original H1 tags does not work

**Comment by gijsk** [comment]
Yeah this is https://bugzilla.mozilla.org/show_bug.cgi?id=1198731 - there's some context in the bug. It'd be nice to fix this.

**Comment by lazharichir** [comment]
@gijsk indeed, the bug has been reported a very long time ago and not much was done to fix it since then. Perhaps it is too complicated - I tried to replace all H1 to H2, and H2 with H3, etc... but then most other articles start their article body's outline with H2 so I end up with H3 instead.

Tough cookie... Do you have any pointer or idea?

**Comment by ivnnv** [comment]
I can confirm this stills an issue.
This jsdom document html:
```
<div class="rte" itemprop="articleBody">
  <h1>Mobile at Shopify 2020+</h1>
  <p>bla bla bla we are so cool</p>
  <p>bla bla bla</p>
  <h1>Partnering and Open Source</h1>
  <p>bla bla bla</p>
  <p>bla bla bla but we dont know basic html markup</p>
</div>`
```

Result into this html after new `new Readability(h1TestDom.window.document).parse()`
```
<div id="readability-page-1" class="page">
  <div itemprop="articleBody">
    <p>bla bla bla we are so cool</p>
    <p>bla bla bla</p>
    <p>bla bla bla</p>
    <p>bla bla bla but we dont know basic html markup</p>
  </div>
</div>
```

And passing the whole website html on `https://engineering.shopify.com/blogs/engineering/react-native-future-mobile-shopify` actually gets the proper h1 article title fine, but still removing the rest of intermediate h1s (we all know that this is not proper html markup, but there should be an option to wether or not having the extra h1s removed or transformed into h2s.

**Comment by jakubriedl** [comment]
This is quite big issue for us. For temporary fix I've monkey patched `_clean` function to remove only first `h1` which solves it until proper fix lands.
```typescript
  const dom = new JSDOM($.html(), { url, virtualConsole: new VirtualConsole() })
  const reader = new Readability(dom.window.document)

  reader._clean = (e: HTMLElement, tag: string) => {
    const isEmbed = ['object', 'embed', 'iframe'].indexOf(tag) !== -1
    const nodes = reader._getAllNodesWithTag(e, [tag])
    const nodesToRemove = tag === 'h1' && nodes.length > 1 ? [nodes[0]] : nodes

    reader._removeNodes(nodesToRemove, function (element: HTMLElement) {
      // Allow youtube and vimeo videos through as people usually want to see those.
      if (isEmbed) {
        // First, check the elements attributes to see if any of them contain youtube or vimeo
        for (let i = 0; i < element.attributes.length; i++) {
          if (reader.REGEXPS.videos.test(element.attributes[i].value)) {
            return false
          }
        }

        // For embed with <object> tag, check inner HTML as well.
        if (element.tagName === 'object' && reader.REGEXPS.videos.test(element.innerHTML)) {
          return false
        }
      }

      return true
    })
  }
  return reader.parse()
```
_there are few minor changes in the code to pass our typescript & liner. But you get the idea._

**Comment by jakubriedl** [comment]
@gijsk I can work on fixing this issue more holistically, because its coming back to us repeatedly. Do you have some idea direction that I should go with this?

I was thinking about keeping the headers in the document during the process (use tweaked `_cleanConditionally` on them) and then at the end remove only one that is textually similar to title.
How does it sound to you?

**Comment by gijsk** [comment]
@jakubriedl thanks, much appreciated! I left some comments on the PR.
