### ISSUE TITLE
Page not getting formatted after parsing the Readability object

### ISSUE THREAD

**Issue by felix-vs** [mozilla/readability#467]
Hi, I was following instructions on README.md
re: 

> To parse a document, you must create a new Readability object from a document object, and then call parse(). Here's an example:

> `var article = new Readability(document).parse();`

I was doing following steps:
1. set-up a local HTTP server (SimpleHTTPServer: http://2ality.com/2014/06/simple-http-server.html) to host the Readability repository files, which I downloaded with Git clone from the main branch here.
2. set-up a simple HTML file [page.html.zip](https://github.com/mozilla/readability/files/2153195/page.html.zip)
3. render the HTML file at local URL using Firefox 60 stable.
3. using Firefox 60 stable Javascript Console as client, sending the following Javascript commands:
`scriptElement = document.createElement('script');
scriptElement.src =
"http://localhost:8000/PATH/TO/FILE/Readability.js";
document.head.append(scriptElement);`
`var article = new Readability(document).parse();`

retrieving the data on the object article by sending command `article` gives:
`byline: null`
`content: "<div id=\"readability-page-1\" class=\"page\">\n\n<p>Just some paragraph bla bla lorem ipsum hehe</p>\n\n\n</div>"`
`dir: null`
`excerpt: "Just some paragraph bla bla lorem ipsum hehe"`
`length: 49`
`textContent: "\n\nJust some paragraph bla bla lorem ipsum hehe\n\n\n"`
`title: ""`

the issue is that the web page doesn't get formatted: no horizontal margins, no CSS etc. (which Reader View mode on FF does for me).

i'm probably doing something wrong here since i'm inexperienced with these tools/JS, so please if I am, try to point out the mistakes and solutions / better ways , if you see them. thanks

**Comment by gijsk** [comment]
The library here is explicitly meant just to produce the relevant markup, not the styling, sidebar, etc.

The remainder of the code is also open-source, and available via the `mozilla-central` mercurial (hg) repository on https://hg.mozilla.org/mozilla-central/ (github mirror at https://github.com/mozilla/gecko-dev ) , but it's pretty tightly integrated with Firefox and Firefox for Android, so it would be tricky to integrate that code into this repository. I'm actually not sure how Firefox for iOS uses the library, but they wrote their own wrapper, CSS etc., as far as I'm aware. From a very, very quick look, it looks like parts of it live here: https://github.com/mozilla-mobile/firefox-ios/blob/13186294f11b9bfc3279f94d7497ffcf6691a7a8/Client/Frontend/Reader/Reader.html .

We have no plans to integrate the styling aspects, or the functionality in the sidebar (desktop) or thumb-y-button (Android; no idea what the right word is), into this repository - sorry!
