### ISSUE TITLE
Hide section on read mode

### ISSUE THREAD

**Issue by Mte90** [mozilla/readability#484]
I received a request from one of my customer about a why to hide specific content in reader mode.
In my example it is a tooltip injected in html that is hidden with CSS and show on mouse hover but with reader mode is printed creating a mess.
I was thinking that maybe add a class specific enable to not show that text in the read mode.

**Comment by gijsk** [comment]
Inline style as well as HTML5 attributes like `hidden` should work. In Firefox, common classes like `.hidden` will also work. Without an example, I'm assuming this isn't actually a bug in the readability library... We have other issues on file about detecting hidden nodes better, but readability is effectively passed a DOM where it can't assume that visibility information on the original DOM is available, so we can't "just" check what nodes are visible "live", ie taking all of CSS into account.

**Comment by Mte90** [comment]
I can confirm that adding `.hidden` fix the issue!
There is a documentation about this behaviour of that library?

**Comment by gijsk** [comment]
There isn't documentation for specifics, no. Effectively that would boil down to writing and rewriting prose that exactly describes what the code checks for, and ultimately I don't think that's helpful.

I wouldn't mind if someone proposed a "guide for content editors" with generic guidelines ("use semantic markup", "don't use script to generate your main content"), or something like that, but I don't think it's productive to over-specify what the library does and doesn't recognize -- that's a moving target, some of the specifics are hard to analyze manually or optimize for when writing content (e.g. content scoring) and it would encourage people to "write for" the current implementation, which would make it harder to change that implementation.

**Comment by Mte90** [comment]
Well in my case discover that was helpful to fix a problem in a website for my test case.
So have this can improve also the UX on that mode.
