### ISSUE TITLE
Datatables with more than one picture are removed

### ISSUE THREAD

**Issue by eldk** [mozilla/readability#491]
Hello,

When there is more than one picture in a 5x4 datatable, all dataset is removed.

This happened with Firefox 62 and 63 (Desktop)

These source is displayed in reader mode (only one picture in dataset) : 

```
<table summary="The summary">
            <caption>The caption</caption>
            <tbody>
            <tr>
                <td>Columns : </td>
                <td>Data set 1</td>
                <td>Data set 2</td>
                <td>Data set 3</td>
                <td>Data set 4</td>
            </tr>
            <tr>
                <td>Translations : </td>
                <td>Translation 1</td>
                <td>Translation 2</td>
                <td>Translation 3</td>
                <td>Translation 4</td>
            </tr>
            <tr>
                <td>Ref : </td>
                <td>Ref 1</td>
                <td>Ref 2</td>
                <td>Ref 3</td>
                <td>Ref 4</td>
            </tr>
            <tr>
                <td>
                     Schemas :
               </td>
                <td>
                    <img src='img1.jpg' width='100' height='75' alt=''>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
            </tr>
            </tbody>
        </table>
```

These source is not displayed in reader mode (4 pictures, one for each columns ) : 

```
<table summary="The summary">
            <caption>The caption</caption>
            <tbody>
            <tr>
                <td>Columns : </td>
                <td>Data set 1</td>
                <td>Data set 2</td>
                <td>Data set 3</td>
                <td>Data set 4</td>
           </tr>
            <tr>
                <td>Translations : </td>
                <td>Translation 1</td>
                <td>Translation 2</td>
                <td>Translation 3</td>
                <td>Translation 4</td>
            </tr>
            <tr>
                <td>Ref : </td>
                <td>Ref 1</td>
                <td>Ref 2</td>
                <td>Ref 3</td>
                <td>Ref 4</td>
            </tr>
            <tr>
                <td>
                     Schemas :
               </td>
                <td>
                    <img src='img1.jpg' width='100' height='75' alt=''>
                </td>
                <td>
                     <img src='img2.jpg' width='100' height='75' alt=''>
                </td>
                <td>
                    <img src='img3.jpg' width='100' height='75' alt=''>
                </td>     
                 <td>
                     <img src='img4.jpg' width='100' height='75' alt=''>
                 </td> 
              </tr>
            </tbody>
        </table>
```

Thanks,
Eric

**Comment by EvsChen** [comment]
> all dataset is removed

I tested your html locally but it seems nothing is removed. Can you elaborate on what you mean by that? Or can you provide a url for us to test? 
Thanks!

**Comment by eldk** [comment]
Hello,

If there is only one picture in dataset : when you switch to reader mode : dataset is displayed.

If there is more than one picture in dataset : when you switch to reader mode : dataset is removed.

This was tested with both Firefox 62 and 63. It's maybe solved now ?

I will recheck with Firefox 65.

Thanks,

Eric

**Comment by gijsk** [comment]
(FWIW, a link to a complete testcase that shows the issue would help.)

**Comment by eldk** [comment]
I'm preparing them. Should I send links by private mail ?

**Comment by gijsk** [comment]
If you're comfortable posting them here that would be preferred.

**Comment by eldk** [comment]
I can't, testcase is ready. How should we do ?

**Comment by gijsk** [comment]
Email to gijs [at] mozilla.com and I'll try and get an anonymized/generic version attached here.

**Comment by gijsk** [comment]
(I'm assuming from your comments that it's not fixed on Firefox 65)

**Comment by eldk** [comment]
The link is sent. 

I have just checked with Firefox 65 : same result : 
- one picture : dataset is displayed
- more than one (here four) : dataset is not displayed.

Thanks

**Comment by gijsk** [comment]
This seems to have been fixed by #66 . I'll update with a link to a nightly build that includes the fix once I get around to updating readability in Firefox (might be Monday).

**Comment by eldk** [comment]
Thanks @gijsk  : tested today with Firefox nightly : solved

**Comment by gijsk** [comment]
Thank you! (And sorry for neglecting to update this with the link like I said I would...)
