### ISSUE TITLE
Sorting relies on a boolean return value

### ISSUE THREAD

**Issue by jemrobinson** [mozilla/readability#496]
As described here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description) the `compareFunction` argument to `sort` discriminates based on whether its input is less than, equal to or greater than 0. When passing this a boolean, true and false are evaluated to 1 and 0, with 0 then leaving

> a and b unchanged with respect to each other

This means that the details of the sort function used become important. In the move from Node.js 10.13 to Node.js 11.3 the sort behaviour has changed and thus the output of standalone Readability.js has changed on trivial inputs like:

```
<html>
    <head></head>
    <body>No article here!</body>
</html>
```

With Node 10.13 this returns

`{"title":"","byline":null,"dir":null,"content":"<div id=\"readability-page-1\" class=\"page\">No article here!\n</div>","textContent":"No article here!\n","length":17}`

while with Node 11.1 this returns:

`null`

I have made a pull request which restores the behaviour from 10.13 in 11.1 by changing the `compareFunction`.

**Comment by gijsk** [comment]
Closing thanks to the fix in #497. Thank you!
