### ISSUE TITLE
readable with standalone but not with Firefox?

### ISSUE THREAD

**Issue by mlda065** [mozilla/readability#506]
My website is https://supermarket.mdavis.xyz

After the response I got to issue #502, I went and ran the script offline with `debug` mode on. 

When I run the script offline it returns True for `isProbablyReaderable`, and manages to correctly `parse` the file.

However when I view that link in Firefox, the "Reading Mode" button does _not_ appear.

What's going on? Are all those inline hyperlinks diluting the score? Is there anything else different between Firefox and this repo?

**Comment by gijsk** [comment]
As a performance/correctness optimization, Firefox does not show the reader mode button at all for "homepages" (ie URLs without a `path` or `query` component). Generally, they're overview pages (with lots of links and no primary text) and so we don't even bother running the `isProbablyReaderable` algorithm. That explains the difference here.

**Comment by mlda065** [comment]
I've moved it from supermarket.mdavis.xyz to www.mdavis.xyz/supermarket

Now Firefox reader mode does appear. Thanks
