### ISSUE TITLE
Reader view returns cookie privacy policy instead of article for this site:

### ISSUE THREAD

**Issue by daf121** [mozilla/readability#514]
https://www.medicalnewstoday.com/articles/318674.php

**Comment by gijsk** [comment]
Accepting the cookie banner makes this work correctly for me.

In terms of fixes, off-hand it looks like this may have regressed with #415 . Perhaps we can add `modal-dialog` back to the list, or something. @andreskrey , is this something you'd be able to look at?

**Comment by andreskrey** [comment]
Sure, I'll take a look this weekend.

Maybe we could add something to remove divs with the class name `gdpr*` and have a broader approach for this problem.

**Comment by andreskrey** [comment]
Fixed via https://github.com/mozilla/readability/pull/516
