### ISSUE TITLE
Replace deprecated methods used in generate-testcase.js

### ISSUE THREAD

**Issue by EvsChen** [mozilla/readability#517]
Hi, I'm new to this repo. I was trying to use Readability to parse document from some url. I found the `test/generate-testcase.js` handy and tried using it. However, I found several deprecated methods being used in the tool.

1. `serializeDocument` of JSDOM seems to be replaced by `new JSDOM(...).serialize`
2. `isProbablyReaderable` is now checked using a stand alone file
3. `JSDOMParser` can be replaced by JSDOM? not sure about it

I wonder if you guys still want to keep this tool. If so, I could make a PR to fix it.

**Comment by gijsk** [comment]
> Hi, I'm new to this repo.
Welcome!

> I was trying to use Readability to parse document from some url. I found the `test/generate-testcase.js` handy and tried using it. However, I found several deprecated methods being used in the tool.

Uh-oh.

>     1. `serializeDocument` of JSDOM seems to be replaced by `new JSDOM(...).serialize`

Oh, that's interesting. I looked at the changelog for jsdom and didn't see this mentioned - only "document.innerHTML and document.outerHTML: use the new jsdom.serializeDocument to include the DOCTYPE, or use document.documentElement.outerHTML to omit it." at the introduction, way back in 1.0.0-pre.1 . So I'm a little confused when it disappeared. Anyway, I agree we should update to something that works with recent versions. We'll need to update the package.json to require whatever version introduced the `serialize` method, I guess.

> 
>     2. `isProbablyReaderable` is now checked using a stand alone file

D'oh, I thought I fixed this but I clearly didn't. Good point.

>     3. `JSDOMParser` can be replaced by JSDOM? not sure about it

I don't know either. I think it would work for this script, hopefully. If switching this could be a separate commit that would be super helpful.

> I wonder if you guys still want to keep this tool.

Yes. It's useful to generate testcases from webpages without having to manually fetch the HTML, manually make it XHTML-compatible so JSDOMParser doesn't choke, and set up the directory and source/expected structure that the automated test framework expects.

> If so, I could make a PR to fix it.

Yes please, that would be great!

**Comment by EvsChen** [comment]
I looked through the commit history of JSDom and found that in [Remove the old API!](https://github.com/jsdom/jsdom/commit/67eb73efc22d85b2aa3c7b0237be58ac5129b584) they removed the `serializeDocument` api. And in [Overhaul the public jsdom API](https://github.com/jsdom/jsdom/commit/58a7028d0d5b6aacc5b435daee9fd8f9eacbb14c) they added the new api.

So according to the tag, `serialize` method is available since v10.0.0 and `serializeDocument` is deprecated since v12.0.0 (if I'm using grep correctly). I think we are safe now to use the new one.

**Comment by gijsk** [comment]
Sounds great! Let me know if you run into any issues or need help with the PR.

**Comment by EvsChen** [comment]
Hi, @gijsk I've submitted a PR. Please review. Thanks!

For the `JSDOMParser`, I think I'll further investigate and leave it to another PR. Currently the tool works fine with it.

**Comment by gijsk** [comment]
Fixed by #519, thanks!
