### ISSUE TITLE
Using Readability is not a function in Node

### ISSUE THREAD

**Issue by jerry94test** [mozilla/readability#520]
var JSDOM = require('jsdom').JSDOM;
var  Readability =  require('moz-readability-node')
var doc = new JSDOM("<body>Here's a bunch of text</body>", {
    url: "https://github.com/mozilla/readability",
});
let reader = Readability(doc.window.document,{});
let article = reader.parse();

let reader = Readability(doc.window.document,{});
             ^

TypeError: Readability is not a function

How can I solve this problem?

**Comment by gijsk** [comment]
What's "moz-readability-node" ?

**Comment by EvsChen** [comment]
If you're referring to the npm repo [moz-readability-node](https://www.npmjs.com/package/moz-readability-node), you need to go to their repo and post issues. It's not maintained here.

But actually you don't need to go that far. To use Readability on node, just clone and cd into the repo here
```js
var index = require('./index');
var Readability = index.Readability;
```
And everything else is exactly the same.

**Comment by jerry94test** [comment]
Thank you for installing the wrong package.
