### ISSUE TITLE
Some seemingly-random small portions of large GNU manual pages are omitted

### ISSUE THREAD

**Issue by gijsk** [mozilla/readability#528]
Cf. https://www.gnu.org/software/grub/manual/grub/grub.html

Omits the

```
# grub-install /dev/sda
```

example at the top of section 3 (and a few other ones).

Not sure off-hand what's causing that, it might be related to the `<kbd>` tags in use there.

**Comment by PalmerAL** [comment]
The portions that are getting removed don't necessarily have any kbd tags, for example:
```
<div class="example">
<pre class="example">(fd0)
</pre></div>
```

It looks like the parts that are getting removed all have <25 characters, I'm guessing it may be related to this line in _cleanConditionally: https://github.com/mozilla/readability/blob/master/Readability.js#L1682a

**Comment by gijsk** [comment]
Looks like this is a dupe of #374 .
