### ISSUE TITLE
[Accessibility - Visually Impaired] Text-to-speech feature not available when displaying PDF files

### ISSUE THREAD

**Issue by gentilmente** [mozilla/readability#529]
In **reader mode** you have text-to-speech feature but in **pdf viewer** you don't.
I work with students visually impaired that would love to have this feature. They think this as a preview before they download the pdf to use in any text-to-speech system they have in the OS.
But maybe they don't even need to download the pdf. ;-)

**Comment by gijsk** [comment]
Hi! Unfortunately, this isn't the right place to file this issue - this tracker is for the code that transforms HTML webpage content into reader view, and it doesn't/can't support PDFs. The narrate functionality (and all other user interface for reader mode) isn't in this repository either, it lives exclusively in the Firefox source code.

We're tracking this request in Mozilla's bugzilla as a feature for Firefox's PDF viewer: https://bugzilla.mozilla.org/show_bug.cgi?id=1530020 .
