### ISSUE TITLE
Embedded images are wrongly aligned with text

### ISSUE THREAD

**Issue by xcffl** [mozilla/readability#531]
Embedded images are left-aligned with text, which allows the reader view horizontally scrollable. However, from the width of images it seems that images should fully occupy screen width. 

Example: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_boxes/Box_model_recap

**Comment by gijsk** [comment]
Can you post a screenshot of what you're seeing, and check against a clean Firefox profile (perhaps there are additional steps necessary)? I don't see anything wrong with the link you provided when opened in reader mode - the images are as wide as the text. Perhaps you've customized the default text width or something else that might influence this bug?

**Comment by xcffl** [comment]
Sorry for the ambiguity. The problem happens in Firefox for Android, where the screen width is small.

**Comment by xcffl** [comment]
The images are out of boundary of the screen
![photo_2019-03-13_17-14-11](https://user-images.githubusercontent.com/2216902/54267066-79956b80-4570-11e9-8e71-26eaefde9dfd.jpg)

And scrolling to the right is allowed, which seems that the image width is aligned with the screen width:
![photo_2019-03-13_17-12-39](https://user-images.githubusercontent.com/2216902/54267063-769a7b00-4570-11e9-8fa4-577ee06bb903.jpg)

**Comment by gijsk** [comment]
Ah, OK! Thanks for clarifying. This is an issue with reader mode on android, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1534942 and will close this one. The code in this github repository is only responsible for extracting the content from the original page; all the subsequent transformation and styling lives in Firefox for Desktop and Firefox for Android's own codebases, so will need fixing there.
