### ISSUE TITLE
Missing images on The Guardian

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/readability#534]
On https://www.theguardian.com/us-news/2019/mar/22/uber-lyft-ipo-drivers-unionize-low-pay-expenses, the two images inside the article are removed.

The reason is that the images are inside an element with "share" in the class, resulting in the same issue as #466, and don't have sufficient text content to be fixed by #527:

```
<figure itemprop="associatedMedia image" itemscope="" itemtype="http://schema.org/ImageObject" data-component="image" class="element element-image img--landscape  fig--narrow-caption fig--has-shares " data-media-id="f2a65a345e22d705bfc5c65a780f42f8ac2f7286" id="img-2">
...
```

I see a couple of potential solutions to this:
* Decrease the share element threshold.
    * The figure in the article has 260 characters of text, so 250 might be a reasonable threshold.
* Make the removal of sharing elements also depend on other factors (tag name, etc.)
* Try to come up with a more specific list of selectors, rather than just "share", since that seems to match a lot of things that aren't actually sharing-related.

@gijsk What do you think?

**Comment by gijsk** [comment]
The list of selectors seems like the most promising thing... That will help us be more specific about what we're removing, whereas the 250 vs 260 thing will just mean we'll find another case where there isn't enough content for images. The tag name filter also feels like we're likely to keep missing tags that then also shouldn't be removed.

In other words, both of the other 2 alternatives involve removing "not quite as much", and hoping that we correctly scope that out. But ultimately, false negatives here are much more benign than false positives - if we remove content that matches the filter but "shouldn't" (like these images) the result is much less good. If we accidentally leave in some share buttons, well, we've accidentally left some junk in there but on the whole, readability still works and the user gets all the content they need.

So I think instead, we should look at the current corpus of test pages and where/when we remove "share" elements, and then adjust the regex so we only remove the things we need to remove. We probably also want to add a testcase for the Guardian item here.

**Comment by PalmerAL** [comment]
That makes sense, I'll try to come up with a more specific list when I have time.
