### ISSUE TITLE
Close old issues

### ISSUE THREAD

**Issue by RadhiFadlillah** [mozilla/readability#536]
As title said, we should close old issues which have already been fixed, either because Readability.js has been improved since then, or the website markup has been changed :

- #97
- #106
- #137
- #151
- #153
- #154
- #234
- #295
- #308 (test site is not exist anymore)
- #321
- #403

For #106, it's solved in current Readability that shipped with Firefox. However, once #523 landed in stable, the info box table will shown again. IMHO it's fine though, because that info box is a valid data table, so it shouldn't be removed.

**Comment by gijsk** [comment]
#154 and #106 still have work left to do, so I left them open.

In future, please comment directly on the issues that you can't reproduce anymore. Thank you for helping audit the older issues!
