### ISSUE TITLE
Incorrect title on Medium articles

### ISSUE THREAD

**Issue by leibovic** [mozilla/readability#54]
https://medium.com/backchannel/first-alan-adler-invented-the-aerobie-now-he-s-created-the-perfect-cup-of-coffee-c5e94ccc538e

**Comment by gijsk** [comment]
If this is a general medium issue (sidebar-open-28px ?) then I fixed this late yesterday (on phone right now, so can't find the pr). Florian reviewed. See the medium-2 testcase.

**Comment by leibovic** [comment]
Nice! I filed this when I saw it on Nightly, which didn't have the most recent changes. I'll close this out then :)
