### ISSUE TITLE
Make lazy loaded images detection optional

### ISSUE THREAD

**Issue by jvandenaardweg** [mozilla/readability#544]
I recently noticed this commit: https://github.com/mozilla/readability/commit/814f0a3884350b6f1adfdebb79ca3599e9806605

And ran the latest master version against my code's snapshot tests.

But it does not give me the result i'm looking for. As it replaces larger images with smaller ones.

I have to say: i got JS rendered HTML. So, the images inside the "src" are already lazy loaded for me. I use readability to extract article data from completely rendered HTML with Javascript.

**Previous version (result good):**
https://codepen.io/jvandenaardweg/pen/YbGGpQ

```html
<img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/-1x-1.png" alt="U.S. stock futures have had a rocky ride since last weekend" data-native-src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/-1x-1.png" data-img-type="chart">
```
[image](https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/-1x-1.png)

**Current version (result not good):**
https://codepen.io/jvandenaardweg/pen/mYrrOq

```html
<img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/60x-1.png" alt="U.S. stock futures have had a rocky ride since last weekend" data-native-src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/-1x-1.png" data-img-type="chart">
```
[image](https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/60x-1.png)

(probaby because it uses `data-native-src`, which is not in the detection script, and is not really a standarized attribute...)

Source:
https://www.bloomberg.com/news/articles/2019-05-12/trade-war-scenarios-force-investors-to-rewrite-playbook?srnd=premium-europe

This is the image/figure without JS loaded:
```html
<figure data-type="image" data-id="337481040" data-image-type="chart" data-image-size="full" data-align="center" style="max-width: 1200px;" class="figure-expandable">
    <div class="image" tabindex="0" role="button" aria-label="Open image in viewer">
        <div id="lazy-img-337481040" class="lazy-img">
            <style>#lazy-img-337481040:before{padding-top:56.25%;}</style>
            <img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/60x-1.png" alt="U.S. stock futures have had a rocky ride since last weekend" data-native-src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iJY.subbhi7Q/v2/pidjEfPlU1QWZop3vfGKsrX.ke8XuWirGYh1PKgEw44kE/-1x-1.png" class="lazy-img__image" data-img-type="chart">
        </div>
    </div>
</figure>
```

So, would love to see this detection made optional if possible, so i can disable it :-)

For now i've worked around it to just strip data attributes from images/figure's before giving it to readability to parse.

**Comment by gijsk** [comment]
This is a bit confusing because my understanding is that the code we have at the moment shouldn't overwrite existing `src`/`srcset` attributes. What is the source HTML you're feeding readability?

**Comment by PalmerAL** [comment]
@jvandenaardweg Sorry for breaking that!

Currently, the code will overwrite an existing `src` attribute if the image has "lazy" in the classname. The reason for this is that some sites (like the seattletimes testcase) do the opposite, and have a placholder image in the actual src atttribute that gets replaced with a larger image:

```
<img class='lazy ' src='https://www.seattletimes.com/wp-content/themes/st_refresh/img/lazy-loading-14x9.png' data-src ='https://static.seattletimes.com/wp-content/uploads/2019/04/120109-1020x680.jpg' />
```

Without actually loading the images, I don't think there's any good way to figure out which one is the placeholder, so if it turns out that the bloomerg behavior is more common, then it probably would be better to not overwrite `src` as a default, but without a larger set of testcases I'm not sure how to tell which one is more likely to be correct.

Either way, I'm happy to make this an option as well.

**Comment by jvandenaardweg** [comment]
Thanks for the replies!

I thought about it, but i think its better to just let the user decide on his test cases. In my case i’ve found a working solution that seems to work for all the test cases I have, which is: just strip the attributes the lazy image feature is using, so it does not try to replace the src

I’ll close the issue
