### ISSUE TITLE
Reader View fails on thepointsguy.com

### ISSUE THREAD

**Issue by Luke-Tech** [mozilla/readability#547]
When enabling the Reader View on any article in https://thepointsguy.com, it doesn't render the article text. It should pull text from the div named "article-body-content" yet appears to pull from the div "footer-disclosure."

The behavior is the same on the Windows, Linux, and Android versions of Firefox.

Thank you for looking into this!

**Comment by gijsk** [comment]
Example URL: https://thepointsguy.com/guides/last-chance-international-aa-flights-6000-ur-points/ .

**Comment by Luke-Tech** [comment]
This now works, thank you very much!
