### ISSUE TITLE
Ancestor scoring logic looks wrong

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/readability#549]
The comment here: https://github.com/mozilla/readability/blob/9092b2a29c6ad3ce7f9a9e1e4e3ee74a56abd304/Readability.js#L919-L929

implies that each level above the great-grandparent will recieve a successively smaller score. However, when the ancestors are actually selected, anything higher than three levels is ignored: https://github.com/mozilla/readability/blob/9092b2a29c6ad3ce7f9a9e1e4e3ee74a56abd304/Readability.js#L894

This seems to be what causes https://bugzilla.mozilla.org/show_bug.cgi?id=1553313: the site has markup that looks like this:
```
<div class="section">
  <div>
    <div>
      <div>
        <div>
          <p> text </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div>
    <div>
      <div>
        <div>
          <p> text </p>
        </div>
      </div>
    </div>
  </div>
</div>
```

The paragraphs are scored, but because the main section elements are more than 3 levels up, they never receive a score. Then, one of the sections is picked as a top candidate, but because none of the other sections have a score, they won't be merged in, even though they are adjacent siblings and should be candidates themselves.

I briefly tried changing _getNodeAncestors to use 5 levels instead, and it seems to improve things on some sites (and fix the linked bug), but also make things slightly worse on others by including unrelated content, so I'm not sure whether this is worth doing or not. 5 is also just as arbitrary as 3 is; I'm not sure what the correct number is.

@gijsk If increasing this sounds reasonable to you, I'm happy to make a PR for it.

**Comment by PalmerAL** [comment]
Also, I'm guessing that increasing this is probably going to cause performance regressions in most cases - how much does parsing time actually matter?

**Comment by gijsk** [comment]
Yeah, the ancestor stuff... we've tried fixing this before (I can't find the PR/issue discussion atm, github's search is... not great) and it's always been really hairy.

I wonder if it's worth looking at the logic that removes divs that contain single `<p>` tags. Perhaps we can likewise remove divs that only contain a single other `<div>`, if the div that we'd scrub has no classes/ids that positively/negatively affect scoring, and perhaps that'd bring us within the 3/5 threshold here without too many other ill effects?

As for the unrelated content inclusion, it's possible we can compensate for that in other ways (e.g. negatively correlating classes/ids on that content).

> Also, I'm guessing that increasing this is probably going to cause performance regressions in most cases - how much does parsing time actually matter?

I think parsing time should be kept in check, so doubling it (or increasing it by 50% or whatever) is likely not acceptable, but a few percentage points increase shouldn't matter. There are some node benchmarks in the tree that can help with assessing this.

**Comment by gijsk** [comment]
I guess we should close this based on #611, so that's what I'll do - @PalmerAL , let me know if you think there's more that needs to happen here.

**Comment by PalmerAL** [comment]
I think it's good.
