### ISSUE TITLE
JSDOMParser doesn't handle boolean attributes

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#55]
In the example below, `allowfullscreen` is what the html spec calls a [boolean attribute](http://www.w3.org/TR/REC-html40/intro/sgmltut.html#h-3.3.4.2):

``` html
<iframe width="560" height="315" 
  src="https://www.youtube-nocookie.com/embed/zOduYvDupXQ" 
  frameborder="0" 
  allowfullscreen></iframe>
```

Trying to parse this brings:

```
JSDOMParser error: expected '</iframe>'
```

Switching to

``` html
<iframe width="560" height="315" 
  src="https://www.youtube-nocookie.com/embed/zOduYvDupXQ" 
  frameborder="0" 
  allowfullscreen="allowfullscreen"></iframe>
```

makes it pass. We should probably support boolean attributes as they're widely used.

**Comment by gijsk** [comment]
This is dealt with by Firefox's XML serializer which turns them into the quoted form, and runs before we pass things to JSDOMParser... I guess that the `serializeDocument` call from jsdom doesn't do this?

We could try to fix the parser, but I'd be worried about regressing stuff. The parser also doesn't deal with optional closing tags well either, nor does it really deal with missing closing tags (invalid HTML) that the browser just pretends is OK. It seems like a pretty sizable task to fix these issues...

**Comment by n1k0** [comment]
>  I guess that the serializeDocument call from jsdom doesn't do this?

Seems it does:

```
> var jsdom = require("jsdom");
> var serializeDocument = jsdom.serializeDocument;
> serializeDocument(jsdom("<html><body><iframe allowfullscreen></iframe></body></html>"))
'<html><head></head><body><iframe allowfullscreen=""></iframe></body></html>'
```

**Comment by gijsk** [comment]
I think we won't end up doing this. If anything, I'm inclined to investigate how we can move away from using JSDOMParser. In the meantime, given the input and script story has all been sorted out, this isn't an immediate concern.
