### ISSUE TITLE
Interest check for separate readability project

### ISSUE THREAD

**Issue by olleharstedt** [mozilla/readability#557]
Hi!

I recently started to work on a small project to apply readability to *every* page on the web, by letting all traffic go through a separate socket, served by a daemon. The algorithm in your repo only serves "articles" in readability mode, but in my project, also algorithms would have to be deployed for a lot of different "web objects", like search engines, link lists, forums, and so on. Would anyone of your contributors be interested in such a project?

My repo is here: https://github.com/olleharstedt/zen-mode-daemon

If this is the wrong place to ask such a question, please let me know.

Kind regards
Olle

**Comment by gijsk** [comment]
I wish you the best of luck, but as filed this isn't an issue that readability can fix - it'd have to be rewritten from the ground up to, fundamentally, work quite differently, and at the moment there is no interest in doing so.
