### ISSUE TITLE
Wikipedia math rendering broken after #555

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/readability#561]
Example URL: https://en.wikipedia.org/wiki/Hermitian_matrix

Wikipedia renders math equations as MathML, followed by an image like the following:

```
<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/6ca00b61ff0e264e6c1e5adc9a00c0d2751feecf" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.338ex; width:32.194ex; height:3.509ex;" alt="{\displaystyle A{\text{ Hermitian}}\quad \iff \quad A={\overline {A^{\mathsf {T}}}}}"/>
```

Readability always removes the MathML nodes (I haven't investigated to find out why, but since they're not supported outside of Firefox, it's probably better not to rely them anyway), leaving the image as the only way to display the equation. Prior to #555, the image would be included in the readability output, but since the image has `aria-hidden`, it will now be removed, so there's no way to see the included math.

I don't see a good general solution to this problem, but Wikipedia is a popular enough site that I'm thinking it would be fine to just create a workaround for this particular instance - maybe look for "fallback image" and assume it should be visible.

**Comment by gijsk** [comment]
Ugh, this is an annoying problem. Also because I've just realized I've neglected to merge readability to mozilla-central for a bit so this doesn't reproduce in Firefox for now, as it probably doesn't have the code change from #555...

**Comment by PalmerAL** [comment]
@gijsk Would it be OK to revert this change?

Alternatively, I could write an exception for wikipedia if that would be better.

**Comment by gijsk** [comment]
@PalmerAL Thanks for pinging this issue, and sorry I haven't gotten to it. I think right now an exception for wikipedia would be preferable. I'm not sure to what degree this is can-of-worms type material (it doesn't look to me like it's easy to compartmentalize the per-domain logic here) but I guess there's only one way to find out, and I don't see a much better solution...
