### ISSUE TITLE
Blog http://ebb.org/bkuhn/blog removes most content in reader view due to `contentWithSidebar` id

### ISSUE THREAD

**Issue by yoasif** [mozilla/readability#564]
As reported on https://www.reddit.com/r/firefox/comments/djol05/why_does_reader_view_remove_the_entire_body_of/

STR:

1. Visit: http://ebb.org/bkuhn/blog/2019/10/15/fsf-rms.html
2. Enable Reader View

What happens:

Most page content is missing.

Comment from the reddit post:

>The main content is in this:
>
> `<div id="contentWithSidebar">...</div>`
>
>If I modify the id in the Inspector so it doesn't contain the entire word "sidebar" (for example, delete the r on the end) then Reader Mode shows that section.

**Comment by gijsk** [comment]
We could maybe check that `sidebar` appears at the start of an ID or individual class. That would probably lead to false negatives though (ie sidebars that no longer get identified as such). For instance, in our test set, the washington post uses:

```html
<div id="article-world_1409786978769_297" class="moat-trackable pb-feature pb-chained pb-f-most-sidebar pb-f-theme-normal">
```
which would no longer get identified correctly - but perhaps would be discarded anyway.

However, doing that inside the extant regex is a bit tricky. A simpler solution would perhaps be to add `content` to the `okMaybeItsACandidate` regex. It looks like that works, and as a side-effect slightly improves our byline detection in a few other pages, without other negative effects that I can see.
