### ISSUE TITLE
Under node: ReferenceError: document is not defined 

### ISSUE THREAD

**Issue by extricator** [mozilla/readability#566]
I'm having trouble parsing this [url](https://digital.library.upenn.edu/women/bly/madhouse/madhouse.html) under Nodejs using JSDOM. It occurs when executing the `parse` method. I get `ReferenceError: document is not defined` but I can see that the dom object was populated. It can also be parsed in the browser without issues. Any idea what could be the issue?

```
let doc = await DOM.fromURL(url);
    let reader = new readability(doc.window.document);
    let article = reader.parse();
```

**Comment by gijsk** [comment]
Is `doc.window.document` null? What version of readability are you using? Can you provide a full stack for the error you're quoting? And are you sure you have disabled JS loading/execution in `jsdom` for the page you're fetching and the error isn't coming from there?

**Comment by extricator** [comment]
I fixed it by updating to current master. It was referencing a document that was null but the reference wasn't present on master. Taken from a npm module of this library that was 8 commits behind. My apologies..
