### ISSUE TITLE
Numbered lists displayed as a one line text

### ISSUE THREAD

**Issue by joseproura** [mozilla/readability#573]
In this page https://www.unocero.com/smartphones/marcas-mala-gestion-apps-segundo-plano-android/ if I run Readiblity extract the text, in content section, list is extracted correctly, with "lo" and "li" elements. But if I get textContent only this list displayed as one line text.

I checked source code, and yes, the list is generated in one line and also numbers is set up as a css property in ol object.

Any way or tweak to fix it?

**Comment by gijsk** [comment]
You're using the DOM directly, so this has nothing to do with readability. Using only the DOM on a plain `<ol><li>Foo<li>Bar` bit of markup produces the same result, cf. https://jsbin.com/curewuwujo/edit?html,js,output .

In the DOM, the value of `textContent` that is returned from an ordered list is specified in the relevant HTML specs, ie https://dom.spec.whatwg.org/#concept-descendant-text-content:

> The descendant text content of a node node is the concatenation of the data of all the Text node descendants of node, in tree order.

Which means that any formatting is lost. `innerText` seems to produce slightly better results in this case (try it in the JS Bin) but still won't include the numbers.

If you want formatted text output based on HTML, look for a library that does that, e.g. https://www.google.com/search?q=convert+dom+to+formatted+text+npm offers a number of JS libraries. I don't know which one is better maintained or has the features you're interested in so can't make any more detailed recommendation.

**Comment by joseproura** [comment]
Thanks your response @gijsk. I understand but I'm not looking a formatted text output, what I'm looking only, that after executing readibility in a page, the text returned, if there's present some list, isthat list is listed with spaces between every element. 

But as you indicated behaviour of readability, using textContent is the expected following the standards

As you say, running readability in html you propose return the same result
