### ISSUE TITLE
kron4.com - Reader picked the privacy statement as the main article

### ISSUE THREAD

**Issue by Sguo12** [mozilla/readability#583]
On this page:
https://www.kron4.com/news/bay-area/santa-clara-county-lockdown-comes-as-number-of-coronavirus-cases-grows-rapidly/

This is shown:
--------------------------------------------------
Privacy Preference Center

Under the California Consumer Privacy Act, you have the right to opt-out of the sale of your personal information to third parties. These cookies collect information for analytics and to personalize your experience with targeted ads. You may exercise your right to opt out of the sale of personal information by using this toggle switch.

--------------------------------------------------

OS: Ubuntu 18.04.4 LTS
Firefox: 73.0.1 (64-bit)

**Comment by gijsk** [comment]
Can't tell if this is better on more recent readability because the website IP blocks European visitors. :-(

**Comment by jtellis** [comment]
It appears the main article is now shown.

Firefox 78.0b1 (64-bit)
___

<img width="426" alt="Screen Shot 2020-06-02 at 16 18 08" src="https://user-images.githubusercontent.com/506631/83566433-fd2cd680-a4ed-11ea-852a-ecda8bb1e99a.png">

**Comment by gijsk** [comment]
I suspect this may be because of https://bugzilla.mozilla.org/show_bug.cgi?id=1640490 , so it might re-regress. It'd be useful to know if this also works on 77. I still can't tell because the site still doesn't show any content in Europe. :(

**Comment by jtellis** [comment]
I just tested on 77.0 and 77.0.1, and they are displaying the article correctly.

**Comment by gijsk** [comment]
Thanks! Sounds like we can close this.
