### ISSUE TITLE
Wrong part of page selected for archiveofourown.org

### ISSUE THREAD

**Issue by tmarkov** [mozilla/readability#585]
archiveofouwown.org contains stories posted in chapters.
Many chapters are properly shows by readability, but on https://archiveofourown.org/works/11808918/chapters/26640231 (and multiple other chapters) the wrong parts of the page are shown.

In particular, on the wrong page I see the title/subtitle, and then a paragraph from the bottom of the page showing who liked the chapter, while the text itself is missing:

<ins>archiveofourown.org</ins>
# Conversations with a Cryptid - Chapter 1 - AMournfulHowlInTheNight - 僕のヒーローアカデミア | Boku no Hero Academia
_Organization for Transformative Works_
46-58 minutes

Ahriel_sinalas, Moonyshewolf, original_name_that_i_thought_of, Silkesukkermaas, 1existential_melon, Embrexial, sophiekwat, wisdoms_daughter, myabug01, TsukiNona, miraculousemily47, TheLivingParadox, white_goddess, heartofthetardis, Kitkat886, Soapdish, iStarryNights, LogicalChocolate, fukk_life, Color_Me_Curious, Alexhound, CrazyHope13, Domic6381, MPDPOP, AvelineGardener, kissmeoverthegardengate, Vnersacc, Meteora_Midoriya, HypnosThanatosTwin, EmberRose1434, xanmanmurc, variegated_fox, Severus_Prince_Slytherin, Happyowl626, Harper_warc, Even_the_darkest_light_shines, desertbrass, Aldwych, SomniumOfLight, Painter40, Shadowhope, Dragon_Inherited, qyootea, daeen, Anonymous_Nerb, FalseTale48, AsianAmu, Flashbunny, burningclaw2, blender_bros, and 3645 more users as well as 3336 guests left kudos on this work!

**Comment by gijsk** [comment]
(my apologies for not having looked at this yet; I want to actually run this locally to see what's going wrong, and I haven't been able to make time to do so yet)

**Comment by tmarkov** [comment]
Do you know when the fix will land in Firefox reader mode?

**Comment by gijsk** [comment]
> Do you know when the fix will land in Firefox reader mode?

Yeah, I'm sorry, I screwed up merging this into Firefox. It landed in Nightly a few days ago, so it'll be part of the 83 release. I just tested with a nightly (you can too: https://nightly.mozilla.org/ ) and it works correctly now.
