### ISSUE TITLE
_setNodeTag should handle nested tags properly

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#59]
Reference: https://github.com/mozilla/readability/pull/52#discussion_r26894597

We need to fix the `_setNodeTag` stuff for non-JSDOMParser, which will involve reparenting stuff (ie, below, move everything from a font tag into a different span tag and then replace the font with the span). This is unfortunate because if there are nested tags, we will be adding + removing things, which will mess up the loop. For instance:

``` html
<font><font>Hello</font></font>
```

We'll hit the first font first with the forEach loop, which then means we'll reparent the second one, which might mean we won't iterate over the second node? Not sure... :-\

Tested in Firefox's devtools console:

```
>>> f = document.documentElement.appendChild(document.createElement('font'));
<font>
>>> f.appendChild(document.createElement('font'))
<font>
>>> document.getElementsByTagName("font")
HTMLCollection [ <font>, <font> ]
>>> document.getElementsByTagName("font").forEach
undefined
>>> Array.prototype.forEach.call(document.getElementsByTagName("font"), function(f) {
>>>   var x = document.createElement("span");
>>>   Array.prototype.forEach.call(f.childNodes, function(fc) {
>>>      x.appendChild(fc);
>>>   });
>>>   f.parentNode.replaceChild(x, f);
>>> });
undefined
>>> document.getElementsByTagName("font")
HTMLCollection [ <font> ]
>>> document.getElementsByTagName("font")[0].parentNode
<span>
```

**Comment by gijsk** [comment]
So curiously, I didn't run into this in #80 . Maybe we should add a test?

**Comment by gijsk** [comment]
This already works, so I just updated an existing test to exercise this codepath to make sure we don't break it in future.
