### ISSUE TITLE
NodeJs Problems

### ISSUE THREAD

**Issue by reclusivebox** [mozilla/readability#591]
I'm trying to run this with NodeJS 12. At first I created a project and used yarn to add this package, jsdom an axios. Then I wrote the following script:
```js
const readability = require('readability')
const jsdom = require('jsdom')
const axios = require('axios')

const url = 'The Article URL'
const promise = axios.get(url)

promise.then(
  function (result) {
    let doc = new jsdom.JSDOM(result.data, { url: url })
    let reader = new readability.Readability(doc.window.document)
    console.log(reader.parse())
  }
).catch(
  (error) => console.log(error)
)
```

But I received the `TypeError: readability.Readability is not a constructor` Error. I've seen the #297 issue but this is a different case.

**Comment by reclusivebox** [comment]
I just found the solution and to be honest it's weird. The file `index.js` clearly exports an object. But Node only recognize the module `const readability = require('readability')` as a function so the solution is to just replace `let reader = new readability.Readability(doc.window.document)` with `let reader = new Readability(doc.window.document)` and it works like a charm, which is weird because it's exactly what the guy from #297 was doing... Anyway for those having the same problem as me look at the code below:
```js
const Readability = require('readability')
const jsdom = require('jsdom')
const axios = require('axios')

const url = 'The Article URL'
const promise = axios.get(url)

promise.then(
  function (result) {
    let doc = new jsdom.JSDOM(result.data, { url: url })
    let reader = new Readability(doc.window.document)
    console.log(reader.parse())
  }
).catch(
  (error) => console.log(error)
)
```

**Comment by gijsk** [comment]
It's because `package.json` lists `Readability.js` under `main`, see https://nodejs.org/api/modules.html#modules_folders_as_modules . So when you `require("readability")`, it's actually `Readability.js` which is imported, which exports a function.
