### ISSUE TITLE
Google security blog doesn't get parsed correctly

### ISSUE THREAD

**Issue by jjdelc** [mozilla/readability#595]
Example post: https://security.googleblog.com/2020/05/enhanced-safe-browsing-protection-now.html

When entering readability mode, the header section of the page gets detected as the content and the body is dismissed. So reader mode only shows the title and subtitle of the page.

Original post
![image](https://user-images.githubusercontent.com/59393/82510934-7df0d900-9ad1-11ea-93e7-38ee9204c9f3.png)

Rendered readbility
![image](https://user-images.githubusercontent.com/59393/82510949-877a4100-9ad1-11ea-8ee7-71dd69d10e0f.png)

**Comment by evilpie** [comment]
Not sure what changed, but this now seems to work correctly in the current Nightly.

**Comment by gijsk** [comment]
I suspect what changed is that their blog has stopped using `div` with `br` and switched to more reasonable markup. Anyway, glad it's working now - it's working in beta too, and we haven't changed readability in m-c for a while so I suspect it's just working in release now, too.
