### ISSUE TITLE
Bug: All data of SVG images will be removed by readability

### ISSUE THREAD

**Issue by imWildCat** [mozilla/readability#596]
Hi, I am writing to report a bug where all data of svg images will be removed.

Repro step:

1. Open https://mp.weixin.qq.com/s/JclyXLUygQBwlmjPqi7mhQ
2. Enable the readability mode of Firefox.

Actual:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/2396817/82757100-cf220500-9e10-11ea-867d-bd49fef3811b.png">

(The formula is removed)

Expected:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/2396817/82757090-c7faf700-9e10-11ea-9c18-1a827b7bd278.png">

**Comment by gijsk** [comment]
@imWildCat Could you clarify why you closed this report?

**Comment by imWildCat** [comment]
Oh sorry, I should have written about the reason:

The `<svg>` tag has `aria-hidden="true"` so that it is ignored by this algorithm:

```svg
<svg xmlns="http://www.w3.org/2000/svg" role="img" focusable="false" viewBox="0 -1149.5 21586 1799" aria-hidden="true" style="-webkit-overflow-scrolling: touch;vertical-align: -1.469ex;width: 48.837ex;height: 4.07ex;max-width: 300% !important;">
```

**Comment by gijsk** [comment]
Ah, yeah, that'd do it... It'd be nice for reader mode to do better here, but I'm not sure there's a good solution to achieve that...
