### ISSUE TITLE
How to use it in React or Angular

### ISSUE THREAD

**Issue by shikhardb** [mozilla/readability#601]
Is is usable within React or Angular?
Does it have any tutorial. 
I could do it with Node.js, but I would like to do that on frontend.

**Comment by gijsk** [comment]
There's a section in the readme about usage directly on the web, see https://github.com/mozilla/readability#usage-on-the-web . Does that help? If not, can you elaborate on what's missing?

**Comment by shikhardb** [comment]
I have tried that, but there seems to be a CORS error. What I'm trying to do is open another website into an iframe and then parse its contents to make it readable.
Is it possible, or CORS is strictly not allowed?

**Comment by gijsk** [comment]
If you're opening another website into an iframe, and you're not on the same origin, then you won't have access to the contents of that other website. See https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy for more details. It sounds like you're trying to get readability to work from website A on website B which is loaded in a frame. The browser's security model makes this impossible.

The only exception I can think of is if you also control website B, you could make some modifications in website B and use `postMessage` to convince website B to switch itself into reader mode, and/or you could make sure you send the requisite CORS headers so you can fetch its contents over a `fetch` or `XMLHttpRequest` call, and then load them as a separate document yourself.
If you do not control website B, you cannot do what you want on the web - you'd need a browser extension or other privileged API.

To be clear, all of this is a direct result of the web security model - the parent webpage can never access the DOM of the website loaded in the iframe, unless they are same-origin. Any tool that needs to talk to the content of the iframe will need such access, and if it was possible to gain such access without cooperation from the target website, it'd be a security issue in the browser / web APIs. There is nothing readability can do about this.

**Comment by daddou-ma** [comment]
@shikhardb  I was able to bypass the CORS issue using https://corsproxy.io/  this way`https://corsproxy.io/?[YOURLINK]`.
