### ISSUE TITLE
can I open in Read-View ,and after using the Extension Translate to another language? 

### ISSUE THREAD

**Issue by GreyRats** [mozilla/readability#612]
can I open in Read-View ,and after using the Extension translate to another language? mmm
https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/

**Comment by GreyRats** [comment]
as I understand it new-come-URL not allows

**Comment by gijsk** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1371786 .

I know it's confusing, but this bugtracker is for issues with the readability library, and not its integration with Firefox.

**Comment by GreyRats** [comment]
wow fast 
thanks. and it's so sadly
