### ISSUE TITLE
Add support for querySelectorAll() to JSDOMParser?

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#62]
That would ease a bunch performing batch operations, and do them in a much more efficient manner, eg.

``` js
[].forEach.call(doc.querySelectorAll("object,embed,iframe"), function(x) {x.remove()})
```

I suspect this is a bunch of work :(

**Comment by gijsk** [comment]
On the upside... I have a patch for this lying around. Will resurrect it at some point today or tomorrow. Not happy with how slow it is, though. :-)

**Comment by gijsk** [comment]
https://github.com/gijsk/readability/tree/implement-queryselectorall fwiw, need to rebase and clean up / improve perf.

**Comment by n1k0** [comment]
Ha, great!

**Comment by n1k0** [comment]
Any news from this front?

**Comment by gijsk** [comment]
I'm working on the live DOM stuff performance, and am almost done there. I can look at this next week, but be aware that my patch only implements selecting of an element or a set of elements using comma-separated id/class/tag selectors. It doesn't support child or descendant selectors, and adding those would complicate matters a lot.

If you are doing something that requires this, I would look at / discuss alternative ways of doing this.

**Comment by n1k0** [comment]
> It doesn't support child or descendant selectors, and adding those would complicate matters a lot.

Ah, that's indeed something I was after, unfortunately. I get this is a lot of work… I've stumbled upon [this project](https://github.com/termi/CSS_selector_engine), I wonder if we could use it along with JSDOMParser? I suspect that won't work magically, though I'll check and play around the idea.

**Comment by gijsk** [comment]
It's been nearly 4 years and we still haven't bothered doing this, so I'm going to assume we don't need/want it. I'd sooner get rid of the hack that is JSDOMParser in Firefox.
