### ISSUE TITLE
is it possible to get just the text only?

### ISSUE THREAD

**Issue by chovy** [mozilla/readability#635]
I've been just using `document.querySelectorAll('*')` and grabbing all the text on the page to run through deepai to produce summaries, but i get a ton of non-article related text.

Your lib seems to give me just the article which is great, but I'm wondering if there's a way to strip out html.

**Comment by dgellow** [comment]
Did you already check the attribute `textContent` from the object returned by `new Readability(documentClone).parse()`?

It doesn't seem to be documented in `README.md` but I believe that's what you want.

**Comment by chovy** [comment]
oh no. didn't see it in the readme. thanks.

**Comment by gijsk** [comment]
I added https://github.com/mozilla/readability/commit/22cff054fbb8d1f33491443aa9a95fc1159b8608 to make this more visible in the doc. Thanks for pointing it out and thanks @dgellow for the response!
