### ISSUE TITLE
Table of content removed

### ISSUE THREAD

**Issue by jakubriedl** [mozilla/readability#643]
**URL**: https://hakibenita.com/sql-anomaly-detection

On page mentioned above readability removes table of content which should stay there.
It is happening in `_cleanConditionally` because the list is wrapped in `<div>` and so `isList === false` and link density is way too high.

There might be 3 ways how this could be solved.
1) **consider the fact that it is inside `<details>`**
    which generally speaking might have higher relevance for content and it fixes this case but probably not many other TOCs
2) **add `toc|table-of-content` and similar classes to positive**
    that can solve that for many TOCs, but in this case it won't be enough as linkDensity is 0.95
3) **in `isList` check trim wrapping \<div\>s (or possibly all ALTER_TO_DIV_EXCEPTIONS)**
    that will improve overall detection of lists and possibly fix other cases where lists are removed just because they are wrapped

when authors indicate which option or combination of options is wanted I'm happy to raise a PR.

**Comment by gijsk** [comment]
Thank you for this report!

Option 3 sounds the most tempting if we can make it work easily? I don't know what the other ramifications would be - I imagine there's a tradeoff here between navigational lists that are page-relevant, and e.g. header-bar page lists which are also sometimes lists and which we *do* want to remove.

Perhaps we should treat links that are same-page / `#hash`-only links differently for link-density purposes?

**Comment by jakubriedl** [comment]
That actually sounds even better. Will prepare PRs for it.
- improve isList detection by removing wrappers (option 3)
- in `_getLinkDensity` don't count `#hash` links into density.

**Comment by jakubriedl** [comment]
@gijsk The PR with fix landed #646 . Please check it out when you got some time. Thanks a lot.
