### ISSUE TITLE
Readability does not display text from above the TOC

### ISSUE THREAD

**Issue by msujaws** [mozilla/readability#652]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1678850

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0

Steps to reproduce:

I went to https://plato.stanford.edu/entries/constructivism-metaethics/
I went into Reader Mode.

Actual results:

I don't see the text that is on the page above the Table of Contents.
Reader Mode was displayed, starting from the below text:

    What is Constructivism?

The term ‘constructivism’ entered debates in moral theory with John Rawls’ seminal Dewey Lectures “Kantian Constructivism in Moral Theory” (Rawls 1980)

Expected results:

I should see the text that is above the Table of Contents.
Reader Mode was supposed to open, but starting from the below text:

Metaethical constructivism is the view that insofar as there are normative truths, they are not fixed by normative facts that are independent of what rational agents would agree to under some specified conditions of choice.

**Comment by gijsk** [comment]
This was duplicated by #655 and investigated a bit there, so let's close this in favour of that issue.
