### ISSUE TITLE
isProbablyReaderable should include `article` tags

### ISSUE THREAD

**Issue by gijsk** [mozilla/readability#662]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1683445 

STR:

1. open e.g. https://blog.nightly.mozilla.org/2020/12/18/these-weeks-in-firefox-issue-85/ in Firefox

ER:
reader mode icon

AR:
no reader mode icon

This is because `isProbablyReaderable` discounts all the paragraphs as they're invisible or too short, and doesn't include the `article` content. The main content is all in `li` tags which are also ignored (and we probably don't want to change that).

**Comment by gijsk** [comment]
@ritik307 this may be a more suitable issue to look at? Basically, we need to add `article` to https://github.com/mozilla/readability/blob/2d358266560e669f13932d6197c6cff958bc3df6/Readability-readerable.js#L56 and add a test using the URL from my initial comment. Let me know if this works for you and/or if you have any questions about this. Thanks for wanting to contribute!

**Comment by tigleym** [comment]
We have an MSU student who will be helping us improve Reader Mode this semester. But I can't seem to assign them. @gijsk Would you be able to do that? Their username is: https://github.com/tthhtao

**Comment by gijsk** [comment]
@tigleym I think they need to comment here first, cf https://github.blog/2019-06-25-assign-issues-to-issue-commenters/

**Comment by tthhtao** [comment]
Hi, this is Jintao. I am interested in working on this bug.

**Comment by tigleym** [comment]
Fixed by #724
