### ISSUE TITLE
GDPR overlay/modal is selected instead of the actual meaningful content on the page

### ISSUE THREAD

**Issue by chovy** [mozilla/readability#666]
Getting to much GDPR crap when trying to use readability. A lot of the time its an overlay/modal that blocks the page content and that gets parsed rather than the content underneath.

Good example:
https://sputniknews.com/us/202012271081582626-investigators-say-bomber-identified-as-63-year-old-anthony-warner/

**Comment by gijsk** [comment]
We already filter out some of these overlays, using [a filter based on classes/ids](https://github.com/mozilla/readability/blob/2d358266560e669f13932d6197c6cff958bc3df6/Readability.js#L124).

I'm afraid that I don't see a GDPR/cookie/whatever overlay when opening that link in Firefox and using reader mode. I also don't see this when using readability's `generate-testcase.js` script with the URL - I get the right content. How are you using readability / can you provide a more detailed reproducible testcase?

**Comment by chovy** [comment]
probably some a/b test. i got it once or twice. then i didn't

**Comment by gijsk** [comment]
OK. If this happens again and you can save markup that reproduces the problem, that would be very useful. In the meantime, let's close this as we can't fix it without a reproducible test case. :-(
