### ISSUE TITLE
How to include full url of images when calling `.content`?

### ISSUE THREAD

**Issue by bradonomics** [mozilla/readability#671]
In instances where the markup includes only a relative path to a source, is there a way to prepend the full URL?

What I'm trying to achieve is to turn instances of `<img src="/images/image.jpg">` into `<img src="https://example.com/images/image.jpg">`.

**Comment by danburzo** [comment]
The `serializer` option controls how `content` is turned into a string. Pass it the identify function (`function (el) { return el; }`) to get the DOM element instead of a string.

If you're using JSDOM in Node.js, make sure you pass its constructor the `url` of your page.

```
[...content.querySelectorAll('img')].forEach(el => el.setAttribute('src', el.src))
```

(That is, set as its `src` attribute the absolute src of the image.)

--- 

Sorry for brevity, writing on my phone

**Comment by bradonomics** [comment]
I've been poking at this for an hour or more and was getting nothing but errors. Mostly `TypeError: doc.querySelectorAll is not a function or its return value is not iterable`.

> If you're using JSDOM in Node.js, make sure you pass its constructor the `url` of your page.

This note about passing the `url` made me realize I wasn't doing that. I was passing `var doc = new JSDOM(data);`. Once I called `var doc = new JSDOM(data, { url: fullUrl });`. Without any change other than adding the `url`, I'm getting what I was expecting.

@danburzo, my use case is solved (thanks for getting me pointed down the right path), but it might be good for posterity to add some notes for using this `querySelectorAll` loop.

**Comment by gijsk** [comment]
@bradonomics https://github.com/mozilla/readability#example explicitly uses the `url` property already, and the text before it also calls out that you should pass it:

> If you're using jsdom to create a DOM object, you should ensure that the page doesn't run (page) scripts (avoid fetching remote resources etc.) as well as passing it the page's URI as the url property of the options object you pass the JSDOM constructor.

How could we make it clearer?

**Comment by danburzo** [comment]
> Without any change other than adding the url, I'm getting what I was expecting.

Yes, on further thought (and access to a larger screen) I realized Readability already converts relative URLs to absolutes (and not the other way around 😅), so indeed providing the `url` to JSDOM is all that's needed.

> How could we make it clearer?

I think a note on how `url` affects serialization can help.
