### ISSUE TITLE
Bootstrap4 article page with multiple authors/contributors, makes a mess of it

### ISSUE THREAD

**Issue by awhileback** [mozilla/readability#699]
```
<div class="container">
            <div class="content-header">
                <h1 >Test Article</h1>
                <p class="lead">The quick brown fox jumped over the lazy dog.</p>
                    <span class="content-date">&bull; June 24, 2021</span>
                    <hr>
                <div class="row my-1">
                    <div class="col my-1">
                        <div class="content-author text-right mb-2">Some Guy
                        <img class="content-author-img rounded-circle ml-2 text-right" src="/media/avatar_images/avatar_444cf5fe-c607-40b3-8194-aed61363cd14_asdfas43e2wr.jpg">
                        </div>
                        <div class="content-author text-right">Some Otherguy
                        <img class="content-author-img rounded-circle ml-2 text-right" src="/media/avatar_images/avatar_444cf5fe-c607-40b3-8194-aed61363cd14_asdfas43e2wr.jpg">
                        </div>
                    </div>
                    <div class="col my-1">
                        <div class="content-author text-left"><img class="content-author-img rounded-circle mr-2" src="//www.gravatar.com/avatar/befd6273e274191bc2d9e7ae3e59512b?s=100&amp;d=mm">Test 123
                        </div>
                    </div>
                </div>
                <hr>
            </div>
            <div class="content-body">
                <div class="block-code"><p>Lorem ipsum dolor...</p</div></div>
```

Sorry the site is being worked on and doesn't exist in a public place yet.

The above code is an article page on a site I'm working on, in Django.

Safari omits the author block when it (presumably) can't make sense of who is who due to multiple authors and lack of a container identifying the authors content block.  Firefox does not, it attributes the first "content-author" as the credit and others beneath, but in its attempt to do a better job than Safari it makes the output worse, by doing a very bad job of rendering the avatar images.  It simply passes them without formatting in `<p>` tags, so giant ones are giant, small ones are small, and all of them have lost their alignment that was previously used in bootstrap to place them on the page.

I can already predict the reply: "we cannot support every CSS framework under the sun."  Okay, but in that case you could provide and document a means of omitting tags from the parser by class or ID.  If I could tag the avatar images with something that the Readability parser would see and omit, I would do so, and the output would be greatly improved here.

![image](https://user-images.githubusercontent.com/84097090/123300684-6d830d00-d4e0-11eb-8c19-a013dd348fec.png)

![image](https://user-images.githubusercontent.com/84097090/123300916-ad49f480-d4e0-11eb-8bc4-2c0c11d57816.png)

![image](https://user-images.githubusercontent.com/84097090/123301100-e08c8380-d4e0-11eb-9197-b5a8efb5bcd7.png)

**Comment by gijsk** [comment]
First of all, apologies that this got left so long. We've been... busy... with a bunch of other stuff. We aim to be more responsive on this tracker going forward.

> I can already predict the reply: "we cannot support every CSS framework under the sun."

Well, we don't preserve any CSS at all. We preserve and honour some trivial classes, like ones that hide content altogether, but that's about it.

> Okay, but in that case you could provide and document a means of omitting tags from the parser by class or ID.

If we did that then most big sites would be completely unreadable in reader mode tomorrow, because publishers prefer you read their sites with all the tracking and ads still present...

> If I could tag the avatar images with something that the Readability parser would see and omit, I would do so, and the output would be greatly improved here.

If you add any kind of tagging of authors via `<meta>` tags (facebook opengraph, twitter, JSON-LD, etc.) that will supersede the author parsing, I think.

If you're still seeing author gunk in the main document, after doing something like that, please provide a full HTML example and we can take another look (I'll reopen the ticket if you tag me).
