### ISSUE TITLE
https://www.cnet.com/news/ should not be renderable (navigational page)

### ISSUE THREAD

**Issue by vprelovac** [mozilla/readability#701]
https://www.cnet.com/news/ should not be readerable (It is a navigational page)

**Comment by gijsk** [comment]
This works for me (I don't get offered reader mode in Firefox, so `isProbablyReaderable` will have returned false). Are you testing the library separately, or are you using Firefox? What version of Firefox, and are you testing in private or normal browsing, and is there anything else that might affect the result here?

(I tested in private browsing on Firefox 91 beta, in the UK; I don't know if cnet sends different markup/scripts depending on geoip or whatever, this is quite plausible.)

**Comment by vprelovac** [comment]
I can confirm it works now, not sure where the glitch was.
