### ISSUE TITLE
Raw PDF contents shown as readable contents

### ISSUE THREAD

**Issue by pmorch** [mozilla/readability#703]
I'm trying to use readability to parse arbitrary URLs provided by an [RSS feed](https://hn.algolia.com/api/v1/search_by_date?tags=%28story,poll%29&numericFilters=points%3E100).

When the URL points to a PDF file (as in [this URL](https://www.imaginary.org/sites/default/files/taskbook_arnold_en_0.pdf)), the raw PDF binary contents are wrapped in

    <div id="readability-page-1" class="page">${rawPDF}</div>

But that clearly is not readable. See below for node.js script to reproduce it.

I know there is `isProbablyReaderable(document, options)` which makes a good guess about whether it is readerable before parsing, but is there a way to detect after parsing whether it actually was parsable?

What I try below (and am now using) is to consider

    ( parsed.title || parsed.byline || parsed.dir || parsed.excerpt || parsed.siteName )

as a truthy value to determine if `parse()` succeeded. But it would be nice to have a method or key in the return value that tells whether parsing was successful.

```
#!/usr/bin/node
'use strict'

// const fetch = require('node-fetch'); // 1.7.3
const axios = require('axios')
const { JSDOM } = require('jsdom')
const fs = require('fs')
const { Readability } = require('@mozilla/readability');

async function parse(url) {
    const response = await axios.get(url);
    const text = response.data;
    const document = new JSDOM(text).window.document
    let reader = new Readability(document);
    return reader.parse();
}

async function tryURL(url) {
    let parsed = await parse(url);

    // content and textContent both contain long strings. For demo purposes,
    // lets shorten them...
    for (let key of ['content', 'textContent']) {
        if (parsed[key])
            parsed[key] = parsed[key].substring(0,100)
    }

    console.log(
        url,
        // Does any of the metadata look valid?
        !!(
            parsed.title || parsed.byline || parsed.dir ||
            parsed.excerpt || parsed.siteName
        ),
        parsed,
    )
}

async function start() {
    await tryURL('https://www.imaginary.org/sites/default/files/taskbook_arnold_en_0.pdf')
    await tryURL('https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages')
}
start()
```

Output:
```
https://www.imaginary.org/sites/default/files/taskbook_arnold_en_0.pdf false {
  title: '',
  byline: null,
  dir: null,
  content: '<div id="readability-page-1" class="page">%PDF-1.4\n' +
    '%����\n' +
    '4 0 obj &lt;&lt;\n' +
    '/Length 206       \n' +
    '/Filter',
  textContent: '%PDF-1.4\n' +
    '%����\n' +
    '4 0 obj <<\n' +
    '/Length 206       \n' +
    '/Filter /FlateDecode\n' +
    '>>\n' +
    'stream\n' +
    'x�uPMK�@\f�ϯ�qzh6�̤�q�\u000f֓�',
  length: 602699,
  excerpt: undefined,
  siteName: null
}
https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages true {
  title: 'Firefox Reader View for clutter-free web pages',
  byline: null,
  dir: 'ltr',
  content: '<div id="readability-page-1" class="page"><div>\n' +
    '      \n' +
    '      \n' +
    '      \n' +
    '      <main role="main">\n' +
    '      ',
  textContent: '\n' +
    '      \n' +
    '      \n' +
    '      \n' +
    '      \n' +
    '      \n' +
    '      \n' +
    '  \n' +
    '    \n' +
    '      \n' +
    '          \n' +
    '          \n' +
    '            \n' +
    '       ',
  length: 1688,
  excerpt: 'Firefox Reader View removes web page clutter to improve readability. Recent Firefox versions can also read pages out loud.',
  siteName: null
}
```

**Comment by danburzo** [comment]
In this scenario, I would intervene much sooner, at the request level. JSDOM and Readability are designed to work with (X)HTML, anything else is mostly guaranteed to be gibberish (although JSDOM will dutifully try to parse any string you throw at it as HTML). So I'd look at the `Content-Type` response header and only accept these:

```
text/html
application/xhtml+xml
application/xml
```

**Comment by pmorch** [comment]
@danburzo Point taken. Adding something like this to `function parse()` after getting the `response`:

```
    if (! (response.headers['content-type'] && response.headers['content-type'].match(/html|xml/)))
        return null
```

I just also think readability should not return binary data, that clearly is not readable.

My personal itch has been scratched, so if you don't want to do anything here, feel free to close this issue.

**Comment by gijsk** [comment]
> I just also think readability should not return binary data, that clearly is not readable.

This is a valid point, though of course once we get to implementing something like this the obvious question is... what is "binary data", and when is something "clearly" not readable? Different encodings on the web and how to cope with them (and "mojibake" and all the other unfortunate outcomes from such attempts), as well as different languages, mean that it isn't actually trivial to decide between "this is meaningful markup and this isn't". HTML parsing is by its nature permissive - unlike XHTML, the failure mode is "do as best you can even with ridiculous input", not "throw your hands up as soon as someone forgot a closing `</p>` tag". Even raw PDF contents (when not compressed) will have text in it that will trip "this could plausibly be plaintext" filters.

Ultimately, I don't think trying to embed a "this-is-not-actually-supposed-to-be-HTML" detector algorithm inside readability is the right solution to this problem, so I'm going to close this issue.
