### ISSUE TITLE
Run our tests suite against a real-world DOMParser implementation

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#71]
JSDOMParser is Firefox specific, we should ensure that Readability works using other real-world implementations by running our current tests suite against other engines; I'm mostly thinking of iOS (some headless webkit might just do the trick though).

**Comment by gijsk** [comment]
We'll need to fix #72 to do this, and potentially other things.

**Comment by gijsk** [comment]
Does jsdom count?

**Comment by gijsk** [comment]
Going to go ahead and close this per our using jsdom.
