### ISSUE TITLE
any chance of getting this to work in Deno?

### ISSUE THREAD

**Issue by ralyodio** [mozilla/readability#714]

**Comment by danburzo** [comment]
Inasmuch as we can find a Deno-compatible DOM library, the rest should not be too challenging.

**Comment by danburzo** [comment]
It seems [JSDOM](https://github.com/denoland/deno/issues/6794#issuecomment-885593699) should work with Deno. @ralyodio can you share what kind of setup would you prefer Readability to support? It's my understanding you can either use [`createRequire`](https://deno.land/std@0.82.0/node#commonjs-module-loading) to use npm packages, or load them from a CDN, or have the module published on [deno.land/x](https://deno.land/x).

**Comment by ralyodio** [comment]
deno_dom library does not work :( I will try jsdom off esm.sh

**Comment by ralyodio** [comment]
deno_dom doesn't suiport `firstElementChild`

**Comment by ralyodio** [comment]
trying to figure out how to get jsdom over on https://esm.sh/jsdom

**Comment by ralyodio** [comment]
this was working but now its broken: https://esm.sh/moz-readability

**Comment by ralyodio** [comment]
deno-dom has been fixed. the jsdom guy refuses to support deno.
