### ISSUE TITLE
Why hasn't there been a release in the last year?

### ISSUE THREAD

**Issue by nsantacruz** [mozilla/readability#729]
Wondering why there hasn't been a release in the last year even though I see more commits on master. Is this library actively maintained?

**Comment by gijsk** [comment]
> Wondering why there hasn't been a release in the last year even though I see more commits on master.

When some of the first commits landed I expected more to follow, which didn't pan out.

> Is this library actively maintained?

Issues are looked at and pull requests merged, several in the past few weeks, so I'm going to say "yes".

We're hoping to get a release out in the next few weeks but we need to sort out some admin issues.

**Comment by gijsk** [comment]
s/next few weeks/today/, it turns out. :-)

**Comment by nsantacruz** [comment]
Yay! Didn't want to sound ungrateful. Thank you.

**Comment by fice-t** [comment]
@gijsk Not too important, but I noticed that 0.4.2 doesn't have a tag in git.
