### ISSUE TITLE
Wordpress and Dotclear blogging platforms, random or no reader mode

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/readability#73]
1/ Wordpress:

Reader mode not activating:
https://blog.mozilla.org/blog/2015/03/16/please-welcome-david-bryant-vice-president-of-platform-engineering/

Reader mode activating:
https://blog.mozilla.org/blog/2015/03/03/unity-5-ships-and-brings-one-click-webgl-export-to-legions-of-game-developers/

2/ Dotclear

Reader mode not activating:
http://blog.mozfr.org/post/2015/03/La-lune-eclipse-le-soleil

Reader mode activating:
http://blog.mozfr.org/post/2015/03/Il-y-a-26-ans-naissait-le-Web-Coup-d-oeil-dans-le-retro

**Comment by leibovic** [comment]
Ah, for performance reasons, we recently changed our logic to determine whether or not to show the reader button without doing a full parse:
https://bugzilla.mozilla.org/show_bug.cgi?id=1143844

We probably need to be less aggressive about this to show the button in these cases where it's not working.

**Comment by n1k0** [comment]
I suspect FFx reader button related bugs should be filed in Bugzilla, am I right?

**Comment by leibovic** [comment]
@n1k0 good call, I filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1147626
