### ISSUE TITLE
Public design documents or research

### ISSUE THREAD

**Issue by bockstaller** [mozilla/readability#731]
Are there any initial design documents, list of research or datasets used for creating this module which are publicly accessible?

 **Background:** I am currently shaping the topic for my master thesis at the University of Heidelberg. The group I am working with is automatically extracting articles from news outlets for NLP tasks and I'm tasked with making this process more resilient or at least detecting failures without manual intervention.

**Comment by gijsk** [comment]
Unfortunately no, not in a meaningful sense, or at least not that I'm aware of. As noted in the header of the `Readability.js` script,

```
/*
 * This code is heavily based on Arc90's readability.js (1.7.1) script
 * available at: http://code.google.com/p/arc90labs-readability
 */
```

There are also a bunch of testcases in this repository, but they are primarily aimed at noticing if the output of readability changes when we make changes to the library, and assessing whether any change in output for a given input (e.g. a nytimes article or such) is reasonable or not.

It is much more the result of exploration and gradual improvement based on cases that don't work, than on a systematic assessment of a given dataset, machine learning, or other similar "match up an algorithm to an organized database" technique. Sorry I'm not able to offer more help!
