### ISSUE TITLE
No readability results on www.dromble.com

### ISSUE THREAD

**Issue by st3fan** [mozilla/readability#74]
Exact url is http://www.dromble.com/2015/01/21/former-nintendo-executive-dan-adelman-discusses-nintendos-culture-third-party-support-and-much-more/

**Comment by leibovic** [comment]
This works for me on desktop on the latest fx-team. Have you tried pulling the most recent changes from this repo? Or maybe it's an issue with what's served to mobile?

**Comment by n1k0** [comment]
Fixed with latest master + latest.

![screen shot 2015-04-09 at 17 09 44](https://cloud.githubusercontent.com/assets/41547/7069823/4bdd78cc-dedb-11e4-8a41-4b9d11adbb4c.png)
