### ISSUE TITLE
Unable to apply reader mode on nytimes.com

### ISSUE THREAD

**Issue by kayjeiem** [mozilla/readability#761]

**Comment by gijsk** [comment]
Can you provide a concrete example of a page that does not work? As a quick test I went to https://www.nytimes.com/2022/08/30/us/navy-seal-training-death.html (current headline article for me), and reader mode was available there just fine.

It is expected (on Firefox) that we do not actively offer reader mode on the NY Times homepage - it is meant for individual articles, not for complicated index pages like the homepage.

**Comment by gijsk** [comment]
Unfortunately without more details we can't do very much here.
