### ISSUE TITLE
Use without NPM?

### ISSUE THREAD

**Issue by kj7rrv** [mozilla/readability#763]
How can I use Readability in my site without using NPM, by just adding a `<script>` tag?

**Comment by gijsk** [comment]
This is described in the [installation section of the readme](https://github.com/mozilla/readability#installation) - you just source the `Readability.js` script and then follow the rest of the instructions under "Usage" etc.

**Comment by kj7rrv** [comment]
Thank you! Where do I get the Readability.js script? Just `https://raw.githubusercontent.com/mozilla/readability/master/Readability.js`?

**Comment by gijsk** [comment]
I mean, I expect github will appreciate it if you make a copy yourself, and/or integrate it however you normally integrate external github repositories that your code depends on. But yes, that is the correct script.

**Comment by kj7rrv** [comment]
Thank you! Are there any non-bundled dependencies?

**Comment by gijsk** [comment]
No, not unless you want to use the "is this maybe parseable by readability" check in `isProbablyReaderable` (which I would suggest you don't unless you have some specific reason to do so).

**Comment by kj7rrv** [comment]
Thank you! I don't need that feature.
