### ISSUE TITLE
Library doesn't like pages with web components

### ISSUE THREAD

**Issue by ralyodio** [mozilla/readability#767]
I'm trying to parse a page with some  native web components. The parser is choking on them.
From what I can tell is its web components using the shadow dom that choke. I don'jt know if there's a way to ignore these compnents somehow Or do I have to manually delete them from the dom first.

I'm doing all this browser side. so I'm not using node.

**Comment by gijsk** [comment]
Can you elaborate on what "choking" means (are you getting errors? Exceptions from the JS call? No output? The wrong output? Something else?), what DOM parser you're using (the browser's or JSDOMParser or jsdom or something else? If the browser's, which browser's?), and do you have a sample page that reproduces the issue?

**Comment by mikeconley** [comment]
Going to wait for the reporter to respond before I try triaging this.

**Comment by gijsk** [comment]
Without more details it's difficult to do anything here, so going to close this for now. If we get more details we can reopen.

**Comment by ralyodio** [comment]
sorry i deleted the code and went another direction.
