### ISSUE TITLE
NYT articles with images duplicate the images

### ISSUE THREAD

**Issue by gijsk** [mozilla/readability#769]
[Originally filed on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1799239). Original report:

> Choose to view an article that has photos: https://www.nytimes.com/2022/11/04/arts/television/netflix-the-crown-elizabeth-debicki-dominic-west.html
> 
> Actual results:
> 
> Viewing articles with photos on NYTimes site shows duplicates in Reader mode on MacOS. Safari does not have that issue.
> 
> Expected results:
> 
> Photos should only show once.

Looks like you need a subscription to reproduce this - the limit of free articles is now 0 (I still can't get past their popup on a clean profile on a browser that has never visited their site before). Without a subscription, reader mode picks up the "you need a subscription" block instead. Loading the article into reader mode directly from the server doesn't have that problem but also doesn't reproduce the bug.

I assume it's something to do with lazy-loaded images from the JS on the page, but without being able to reproduce it's difficult to do something about it.

**Comment by steffen-stell** [comment]
Subscribers can gift 10 articles per month. [Here is an article with an image](https://www.nytimes.com/2023/01/31/opinion/ron-desantis-black-history.html?unlocked_article_code=vXEjE-mqafNq8s_LA3wKYI0ybMdKjDNincqDJw2qq6RKDfqkB6UPeWgjGqM9_0PU3QmgYgPsKZLUyMomu2TdlSYmq3oWqRBp1sSxcpj-Enc_NFqT7O8AufS5GZAs9xA1SsWXiwNqDLQAHvnQ6vaeg1qHmpoUsECoqfn2Brg97jCQ0NFAGpA4rX7YWTD_J6TAXvPCGjak8xCW5VU7gaAOCQycrnQnMInCODb1BwygxygmgiDGq4gY-q6CYeJ4SW0Kmouz0eXYHjg18mukcROR7dtSS5b2-2ciKxl63DjeOmQQk_UHtGl4dt4asRH03jmELsnU5GiuPJ60hSJEkvMAtvfPPVQH&smid=share-url). It should be accessible for 2 weeks.

**Comment by yev2000** [comment]
The root cause seems to be a second div below the main image with a visibility:hidden attribute.

**Comment by gijsk** [comment]
This should be fixed by #817, though we should doublecheck...
