### ISSUE TITLE
Don't Show display: none elements

### ISSUE THREAD

**Issue by scolby33** [mozilla/readability#780]
#283 seems to have regressed, or maybe my page hits a different edge case.

I have CSS like:
```css
.hidden-metadata {
    display: none;
}
```

And HTML like:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
        <link rel="stylesheet" href="main.css">
    </head>
    <body>
        <main>
            <article>
                <h1>Test</h1>
                <div class="hidden-metadata p-summary">
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                </div>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
            </article>
        </main>
     </body>
</html>
```

In normal view, I see the short paragraph followed by the long paragraph. When I enter readability view, I now see the short paragraph twice followed by the long paragraph.

Changing the class name to `.hidden` and removing the `.p-summary` class didn't change the result.

Is this a bug in readability? If not, how should I mark up the summary paragraph for the machine-readable `.p-summary` without exposing it to readability view?

![image](https://user-images.githubusercontent.com/9711846/213318867-1191b9c4-9294-4f12-8a83-3317101845ce.png)
<img width="656" alt="image" src="https://user-images.githubusercontent.com/9711846/213318910-75bd71b6-3b46-4131-a2b9-92914fb8d392.png">

**Comment by gijsk** [comment]
Readability only uses markup and inline styles, not CSS styles, because those aren't generally available.

This is the default visibility checker it uses: https://github.com/mozilla/readability/blob/8e8ec27cd2013940bc6f3cc609de10e35a1d9d86/Readability.js#L2221-L2227 .

You can pass a custom one as part of the options object. If you think there's strict improvements we can make here, I'd be happy to look at a PR - though historically we haven't been able to assume that classes that _contain_ `hidden` need to be removed, rather than just downgraded (they already match the `negative` regex that gets candidates scored down and thus prefers other content).

**Comment by scolby33** [comment]
Ahh, I see. I didn't realize that `node.style.display != "none"` only referred to inline styles and not those from CSS. I also didn't realize that the -25 weight from the class name was small enough that it could be overridden by the length of the contained content, which is what I think is happening here.

I've realized that in this case (a summary that's only there for metadata purposes and repeats text visible immediately below in the page), the `hidden` attribute is actually more appropriate than using `display: none`, since the content is not part of _any_ presentation of the page, not just currently hidden.

Unfortunately for the wider issue, I agree with you, there isn't a lot more to be done given the local information that is available.
