### ISSUE TITLE
Cannot read properties of undefined (reading 'concat')

### ISSUE THREAD

**Issue by suntong** [mozilla/readability#782]
For the following code:

```js
const axios = require("axios")
const jsd = require('jsdom')
const rd = require('@mozilla/readability')

let { data: rawData } = await axios.get("https://gist.github.com/fiamett/6754693a39f3cb4faa3db58e1b1942b1")
//console.log(rawData)
let doc = new jsd.JSDOM(rawData)
console.log(rd.Readability(doc.window.document).parse().content)
```

I'm getting:

`TypeError: Cannot read properties of undefined (reading 'concat')` (node v18)

or,

`TypeError: Cannot read property 'concat' of undefined` (node v14)

Tried in node v14, 16 & 18. All the same error, from the line of @mozilla/readability/Readability.js — line 51:

`  this._classesToPreserve = this.CLASSES_TO_PRESERVE.concat(options.classesToPreserve || []);`

**Comment by fchasen** [comment]
You'll need to pass `new` to create an instance of `Readability`:

```
new rd.Readability(doc.window.document).parse()
```

**Comment by suntong** [comment]
Thanks. 

I'm new to JS/Readability -- is it possible to do an assignment like

 `const rdp = new rd.Readability`

then do `rdp(doc.window.document).parse()`, or I have to do a `new` each time when I invoke `rd.Readability`? thx

**Comment by gijsk** [comment]
No, you'd need to call `new` each time. `rd.Readability` is a constructor, and the result of `new rd.Readability` is an object. You cannot then call that object as a function using `rdp(...)` as you suggest.
