### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by danielnazer** [mozilla/readability#783]
This Mozilla repository has been identified as lacking a LICENSE.md file. This repository does have licensing information in the README.md file. To make it easier for users (and scanning tools) to find licensing information please add a LICENSE.md file with that information to the root directory of the project.

Mozilla staff can access more information in our Software Licensing Runbook – search for “Licensing Runbook” in Confluence to find it.

If you have any questions you can contact Daniel Nazer who can be reached at dnazer on Mozilla email or Slack.

READMELIC-2023-01

**Comment by gijsk** [comment]
Closing this now that I've added a license file with a copy of the information in the readme.
