### ISSUE TITLE
i'm getting errors logged by the library even though I use try/catch

### ISSUE THREAD

**Issue by ralyodio** [mozilla/readability#795]
I think you have a console.log in your library somewhere. Please remove and throw an error if you need to so I can catch it. Some web pages won't parse, which is fine but I don't want a log sent.

```
Readability.js
84:        console.log.apply(console, args);

JSDOMParser.js
877:        console.log("JSDOMParser error: " + m + "\n");
```

i believe its the second one here causing the issue. You should `throw(error)` here instead.

**Comment by gijsk** [comment]
JSDOMParser isn't meant for outside consumption as it won't cope with non-XML-formed HTML. We recommend using `jsdom` or a similar parser instead.

Without a testcase that reproduces the problem it's difficult to do much here - the `console.log` in `Readability.js` is guarded by an internal-only `debug` bool which is false by default, and as I said, `JSDOMParser` isn't meant for outside consumption, so without steps to reproduce it's not clear to me how you're seeing console logging from the library.

**Comment by ralyodio** [comment]
I'm using jsdom.

**Comment by gijsk** [comment]
Can you share a snippet that reproduces the issue? Does the console.error not produce a stack trace that you can use to work out where exactly it's coming from? (Is it possible the console log is coming from web script, if you're letting that run when parsing with [`jsdom`](https://github.com/jsdom/jsdom)?

**Comment by ralyodio** [comment]
i think its an error event from `jsdom`. I opened up a ticket with them.
