### ISSUE TITLE
Images missing from medium.com articles

### ISSUE THREAD

**Issue by celina-liner** [mozilla/readability#803]
Images missing from medium.com articles
(ex.[Issue Link]( https://medium.com/getsomejoy/buttermilk-biscuits-and-michaela-coles-creative-process-fa2105f63573))

**medium has image tag**
<img width="1184" alt="image" src="https://github.com/mozilla/readability/assets/86952233/44d61ac2-d0de-4363-b39c-c28b9ec22436">

**my page has not release image tag**
<img width="1184" alt="image" src="https://github.com/mozilla/readability/assets/86952233/09c786d5-7d0b-4cbb-9ec1-82f7e8e062fc">

**Comment by gijsk** [comment]
@celina-liner why did you close this out?
