### ISSUE TITLE
anyway to include a list of keywords in output?

### ISSUE THREAD

**Issue by ralyodio** [mozilla/readability#815]
I am trying to get some keywords generated from an article (ie: tags). How should I do this?

**Comment by ralyodio** [comment]
possible to get article date too?

**Comment by gijsk** [comment]
I'm afraid I really don't know what you mean by "list of keywords". I don't think trying to find keywords in the text is something that should be part of readability; scraping through article text etc. should be done as a further step after feeding it readability's output.

Article dates are not always available and may be tricky to find, but in principle I'd be fine with pull requests to extract them explicitly.

**Comment by fchasen** [comment]
Going to close this for now as we are unclear on the keywords, please reopen if you have a website testcase for us to look at.
