### ISSUE TITLE
Why doesn't _isProbablyVisible check visibility: hidden?

### ISSUE THREAD

**Issue by mikesnare** [mozilla/readability#816]
We've run into this bug: https://github.com/mozilla/readability/issues/769 and the _reason_ seems to be that `visibility: hidden` isn't being checked in `_isProbablyVisible`.  The site has duplicate images hidden somewhere using that approach to hiding.

Since you're looking for `display: none`, it seems odd that you are not also looking for `visibility: hidden`.  But it's _so_ odd that I figure there must be a reason, so before I monkey patch I wanted to check to see what that reason might be.

Thanks!

**Comment by aehlke** [comment]
I tried looking through older tickets but couldn't find any leads on why this is omitted. I would recommend just adding it and checking test results.

**Comment by gijsk** [comment]
I think we've just not tried particularly hard. Once you go down the rabbithole (what about `opacity`? What about `overflow: hidden` combined with a 0 width/height? What about...) it's pretty deep.

I'v no objections to adding it, though.

**Comment by gijsk** [comment]
We merged #817 so let's close this out. Thanks!
