### ISSUE TITLE
spiegel.de not readerable any more

### ISSUE THREAD

**Issue by ilf** [mozilla/readability#872]
Recently (today?), most content on spiegel.de stopped being readerable.

Almost any article now only has this content in reader mode:

> Um das Surfen auf unserer Seite für Sie weiterhin so sicher wie möglich zu gestalten, werden wir am 6. Juni 2024 unsere Systeme und damit sogenannte Sicherheitszertifikate aktualisieren.
> Sie sehen diesen Hinweis, weil Sie unser Angebot mit einem veralteten Browser oder Betriebssystem besuchen, auf denen die neuen Zertifikate voraussichtlich nicht unterstützt werden, und Sie unser Angebot dann nicht mehr oder nur eingeschränkt nutzen können.
> Wir empfehlen Ihnen daher Ihren Browser und / oder Ihr Betriebssystem auf den neuesten Stand zu bringen.

Examples:
* https://www.spiegel.de/netzwelt/web/elon-musk-macht-aus-twitter-com-x-com-a-af968404-d392-4b78-a4d0-07ca5aff90eb
* https://www.spiegel.de/ausland/marine-le-pen-beendet-zusammenarbeit-mit-afd-im-europaparlament-a-e94ecdf2-3283-4e4c-8de4-f1f1100e837f
* https://www.spiegel.de/politik/klimaschutz-klage-erfolgreich-bundesregierung-muss-nachbessern-a-348d8f02-66ae-4d13-bea7-64e4498f6062

Reproduced in Firefox 126, Firefox 115.11 ESR, Firefox 125.3 Android and Feeder 2.6.24.

**Comment by recordverdaechtig** [comment]
Same behaviour. Disappeared for 1 day after updates of firefox and MacOS. The Problem reoccured afterwards. Updates did not help.

**Comment by ilf** [comment]
@ZachSaucier: Thanks for the test-case. But what you're reporting seems to be a different bug tracked at #776.

**Comment by cmkm** [comment]
@ilf Is this something you're still encountering? Could you also try Nightly and see if it's happening there, if so? 

I haven't been able to reproduce this. Since the error message is certificate related, I think there might be something else going on we need to narrow down.

**Comment by ilf** [comment]
@cmkm: No, this issue went away, probably around the "6 June 2024" date spiegel.de said.

But #776 still happens very regularly.
