### ISSUE TITLE
Crashes when encountering weird tags (<div 1>, <div 2>)

### ISSUE THREAD

**Issue by begilbert-sys** [mozilla/readability#886]
I was testing on random news articles and came across the following webpage:
[https://news.virginia.edu/content/dungeons-dragons-and-burgers-really-bad-outcomes-when-we-dont-grasp-fractions](url). 

It appears that the site has some weird div tags like `<div 1>` and `<div 2>`, and ended up crashing the parser. The error was the following: 

```
Error in event handler: Error: Failed to execute 'setAttribute' on 'Element': '2' is not a valid attribute name.
at Readability._simplifyNestedElements 
    at Readability._postProcessContent
    at Readability.parse 
```

Obviously this is more of the site's fault, but it would be nice to just ignore elements like this instead of breaking.

**Comment by gijsk** [comment]
Thanks for the report. This is fundamentally the same issue as #859 .

**Comment by gijsk** [comment]
(github somehow only has "not planned" and "fixed" as resolutions for a ticket? Anyway - conversations will continue in #859 I'm sure, and I do really appreciate the additional testcase + report!)
