### ISSUE TITLE
No readability results on www.mashable.com

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#92]
Was randomly surfing and noticed that http://mashable.com/2015/03/31/kale-smoothies-starbucks/ doesn't give me a readability view in Firefox (but does in Safari).

![you_can_now_get_your_starbucks_smoothie_with_a_dash_of_kale_and_new_issue_ _mozilla_readability_and_you_can_now_get_your_starbucks_smoothie_with_a_dash_of_kale](https://cloud.githubusercontent.com/assets/557895/6955737/a3170f6c-d897-11e4-87e7-35a34a4142ac.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/6955743/b9cbde5e-d897-11e4-9c32-c9ae290b89cc.png)

---

Browsing the same page in Safari gives me a Readability view:
![you_can_now_get_your_starbucks_smoothie_with_a_dash_of_kale_and_new_issue_ _mozilla_readability_and_you_can_now_get_your_starbucks_smoothie_with_a_dash_of_kale](https://cloud.githubusercontent.com/assets/557895/6955747/dc88580a-d897-11e4-96c9-e81071d1d154.png)

**Comment by n1k0** [comment]
WFM with latest fx-team & JSDOMParser+Readability

![screen shot 2015-04-02 at 09 40 10](https://cloud.githubusercontent.com/assets/41547/6959784/a46ad5e4-d91c-11e4-9eed-a0ecfe3fd3ac.png)

Though the Reader button didn't show up for this article, I had to use @leibovic's [trick](https://pastebin.mozilla.org/8827908) to get the readable view for that page.

**Comment by n1k0** [comment]
> Though the Reader button didn't show up for this article, I had to use @leibovic's trick to get the readable view for that page.

Definitely fixed since [Bug 1149859](https://bugzilla.mozilla.org/show_bug.cgi?id=1149859) has landed. Closing.
